### ISSUE TITLE
"A" vs. "An" grammar error in validation message

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#1]
Apologies if this is already fixed in the not-yet-released code, but I'm using the latest release from https://github.com/validator/validator.github.io

```
$ java -jar vnu.jar http://jsbin.com/giquho/2/
"http://jsbin.com/giquho/2":20.6-20.6: error: Stray start tag “body”.
"http://jsbin.com/giquho/2":20.6-20.6: error: An “body” start tag seen but an element of the same type was already open.
```
Note the `An “body”`, which is grammatically incorrect.

**Comment by cvrebert** [comment]
Is the Bugzilla patch still on your radar? Henri responded to your questions.

**Comment by sideshowbarker** [comment]
I've not landed the upstream Mozilla patch yet but anyway since we build the validator from a github mirror of the upstream repo and in the interest of getting the fix out into a release sooner, I went ahead and pushed the change to the mirror we build from; see https://github.com/validator/htmlparser/commit/ca49fe01cede03177f1e603ea1adbd56d3d77aab

I still need to get this fixed in parallel upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1096172 along with https://bugzilla.mozilla.org/show_bug.cgi?id=1077211

So for now I'll close this after I have a new jar release built with the fix. And cnce the fixes are both made upstream, I'll just force-push from upstream back to our github mirror then.

**Comment by sideshowbarker** [comment]
New jar just now released: https://github.com/validator/validator/releases/tag/20150216
