### ISSUE TITLE
Doesn't show outline block

### ISSUE THREAD

**Issue by demimurych** [validator/validator#1011]
URL: https://epsmm.com/
Validator URL: https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fepsmm.com%2F
### Result page dont show outline block

> ![Showing-results-for-https-epsmm-com-Nu-Html-Checker](https://user-images.githubusercontent.com/545828/90313854-6c746d00-df18-11ea-9070-4d437ea79ee0.png)

### If i upload html file directly - all works like expected

> ![Showing-results-for-index-html-Nu-Html-Checker](https://user-images.githubusercontent.com/545828/90313918-ca08b980-df18-11ea-8e42-0dc9c31e9505.png)

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. It’s an unintended consequence of the changes made in #999 and #1002. But I’ve made a change for it now and pushed the change to https://validator.w3.org/nu/

Note however that the change doesn’t actually cause the outline to be displayed; instead, it causes the checker to emit a warning explaining why the outline can’t be displayed.

In the case of the https://epsmm.com/, the root cause is that the response from the server violates the HTTP spec by not having a “closing chunk” in its chunked response. That’s unfortunately a common problem in many HTTP servers — but even more unfortunately, it’s a problem that the checker’s internal HTTP client is more strict about than browsers are. And so the result is that the lack of a closing chunk causes the checker internals to throw an exception, and that causes the checker to be unable to construct the outline.

**Comment by karemkadidola** [comment]
I think I have a similar problem on https://www.yourprivatedriver.be/ could you please tell me why I am unable to see the Outline block I have this warning but which is not clear. " Warning: Unable to show outline. (Most likely due to a malformed HTTP response from the server hosting the document that was checked.)

https://www.yourprivatedriver.be/" 
what can I do in order to be able to see the outline or what can I tell the support team of my hosting company to do ( if any setting has to be made on their side ) in order for me to see the outline as this is very important for me

best regards

**Comment by wwwXpert** [comment]
Hi... I posted this on another thread 8 days ago but didn't receive any responses so.

Earlier in the year, I was able to validate shopify sites with **outline** checked to review page structure according to header tags.

Currently, the validator spits out the same errors for **100% of sites hosted on shopify when outline is checked**.

 `Unable to show outline. (Most likely due to a malformed HTTP response from the server hosting the document that was checked.)`

OR

`Cannot recover after last error. Any further errors will be ignored.`

You can pick any from this site: https://www.oberlo.com/blog/shopify-stores

Examples:
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.taylorstitch.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.unconditional.uk.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fhelmboots.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fmillk.co%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.bando.com%2F#cl1960c2030
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.marcwenn.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.americancrew.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.fleshbeauty.com%2F#cl1960c203

**Comment by sideshowbarker** [comment]
> Validator URL: [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fepsmm.com%2F](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fepsmm.com%2F)

> Examples:
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.taylorstitch.com%2F#cl1960c203](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.taylorstitch.com%2F#cl1960c203)
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.unconditional.uk.com%2F#cl1960c203](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.unconditional.uk.com%2F#cl1960c203)
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fhelmboots.com%2F#cl1960c203](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fhelmboots.com%2F#cl1960c203)
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fmillk.co%2F#cl1960c203](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fmillk.co%2F#cl1960c203)
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.bando.com%2F#cl1960c2030](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.bando.com%2F#cl1960c2030)
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.marcwenn.com%2F#cl1960c203](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.marcwenn.com%2F#cl1960c203)
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.americancrew.com%2F#cl1960c203](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.americancrew.com%2F#cl1960c203)
> [validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.fleshbeauty.com%2F#cl1960c203](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.fleshbeauty.com%2F#cl1960c203)

Outlines should now be shown as expected for all of those, as a result of 6a41cff. Basically, I realized I could “fix” this just by making the checker use HTTP 1.0 rather than HTTP 1.1.

I don’t anticipate that switch will cause any regressions in the checker behavior — but if something unexpected does happen, I’ll need to revert 6a41cff and figure out some other fix.

Thank you all for your persistence in reporting and commenting on the problem — it helped to make me (finally) prioritize this enough to be able to think of a reasonable way to prevent the problem.

**Comment by demimurych** [comment]
Wow!!! 
I checked all my projects where there was this problem, and now everything is fine.
Let a lot of delicious beer fall on you.
Thank you so much
