### ISSUE TITLE
Git submodule https://github.com/validator/validator.wiki.git doesn't exist

### ISSUE THREAD

**Issue by yurivict** [validator/validator#1035]
It's referenced in ```.gitmodules```.

**Comment by sideshowbarker** [comment]
How are you testing for its existence?

It’s normal and expected that opening https://github.com/validator/validator.wiki is a browser will give you a 404. It’s only intended to be referenced within git — either as a submodule repository URL or for direct cloning:
```
$ git clone https://github.com/validator/validator.wiki
Cloning into 'validator.wiki'...
remote: Enumerating objects: 727, done.
remote: Total 727 (delta 0), reused 0 (delta 0), pack-reused 727
Receiving objects: 100% (727/727), 192.07 KiB | 492.00 KiB/s, done.
Resolving deltas: 100% (417/417), done.
```

**Comment by yurivict** [comment]
https://github.com/validator/validator.wiki returns the http code 404 - doesn't exist.

**Comment by sideshowbarker** [comment]
> https://github.com/validator/validator.wiki returns the http code 404 - doesn't exist.

Right. To repeat what I already wrote in my previous comment:

> It’s normal and expected that opening https://github.com/validator/validator.wiki is a browser will give you a 404. It’s only intended to be referenced within git — either as a submodule repository URL or for direct cloning

Is there some part of that explanation which is unclear?

**Comment by yurivict** [comment]
Aren't all github URLs supposed to end with .git and be viewable in a browser?

**Comment by sideshowbarker** [comment]
> Aren't all github URLs supposed to end with .git and be viewable in a browser?

I don’t know.

But the fact that `https://github.com/validator/validator.wiki` doesn’t end with .git and isn’t viewable in a browser is not a problem in practice for this project — because we’re not publishing that URL nor telling anybody to navigate to it. Instead it’s just being used internally, and for that purpose it’s working as expected. And I don’t what other URL we could change it to without breaking what it’s actually being used for.
