### ISSUE TITLE
Not accepting this format, format: matrix.to/#/#room_name

### ISSUE THREAD

**Issue by workwithALIASGAR** [validator/validator#1037]
**The W3 validator is not accepting this format, format: matrix.to/#/#room_name, and if we remove # from the format it will show an error link that this is not format. please write correct format.**

### ERROR CODE GIVEN BY W3 VASLIDATOR ON MATRIX.TO
Error: Bad value https://matrix.to/#/#whonix:tchncs.de for attribute href on element a: Illegal character in fragment: # is not allowed.

**Comment by sideshowbarker** [comment]
The message is correct. `https://matrix.to/#/#whonix:tchncs.de` isn’t a valid URL — it doesn’t conform to the requirements in the https://url.spec.whatwg.org/#url-writing section of the URL standard.

Specifically, a valid URL can’t have two `#` characters — a valid URL can only have one `#` character, after which every other character becomes part of the fragment part of the URL; and the fragment part of the URL can’t contain another `#` character. That’s exactly what the error message is saying.

So the fact that Matrix generates and depends on such invalid URLs is a bug in Matrix which should be reported to the Matrix maintainers so that they can fix it.

**Comment by aliasgarabidsabunwala** [comment]
ok. will notify them.
