### ISSUE TITLE
Missing </html> doesn't throw an error

### ISSUE THREAD

**Issue by ianhiatt** [validator/validator#1038]
When doing an upload/direct input no error is thrown if the </html> tag is missing. Example:

[hello_world.txt](https://github.com/validator/validator/files/5434716/hello_world.txt)

As most HTML is forgiving, this of course works. But best practice is to close all tags that are opened. This should throw an error/warning.

**Comment by cvrebert** [comment]
Duplicate of #658

Please search for relevant closed issues in the future when filing new issues.

**Comment by ianhiatt** [comment]
I did a search and the above didn't appear. Please don't assume laziness.

Shouldn't this still warrant a warning? Plenty of other warnings appear for "optional" things. You get warnings for images without alt tags for example.

**Comment by sideshowbarker** [comment]
We don’t warn about it because there are no problems that it causes. And the HTML language and browsers have from the beginning always allowed the `</html>` end tag to be omitted from document. There was never a time when either the HTML specification or browsers required the `</html>` end tag.

It’s true that XML and “XHTML” required every element to have an end tag, but HTML isn’t either XML. HTML is its own language, with its own rules — and “every element must have an end tag” is not one of its rules.
