### ISSUE TITLE
Outline and the situation around errors with it. I ask you very much to understand.

### ISSUE THREAD

**Issue by demimurych** [validator/validator#1063]
I'm talking about this error:
`Unable to show outline. (Most likely due to a malformed HTTP response from the server hosting the document that was checked.)`

For the last 4 years, I have used the validator very often. And between 2017 - 2020 I have never seen this msg.

In 2020, suddenly, this message began to appear with tremendous frequency. 
In fact, out of 10 sites that I checked in a week, 8 with this error. 
I can guarantee that these same sites were checked in 2018 and since then not a byte has changed on them.

Maybe you can somehow get around this problem and  show the outline? 
After all, until 2020 it was possible.

**Comment by sideshowbarker** [comment]
It wasn’t possible previously. The only thing that changed was that I added an explicit message to indicate that the outline couldn’t be shown. Previously it would just silently fail to show the outline.

**Comment by sideshowbarker** [comment]
> Previously it would just silently fail to show the outline.

Or actually rather I think it would report an IO error exception. What changed is that I now catch that exception and instead report that the outline can’t be shown.

**Comment by demimurych** [comment]
Thank you very much for your time.
But...

My ass tells me that there is something wrong with this message.

I'll try to figure it out myself.
Thanks again.

**Comment by sideshowbarker** [comment]
> I'll try to figure it out myself.

OK. But I see now that it seems like you already reported this previously in https://github.com/validator/validator/issues/1011. As I told you at that time, this is related to #999 and #1002. What happened since then is that I changed the code as shown in  https://github.com/validator/validator/commit/d5a31de5ba8ab67f8b476b70353f846c1314186e.

> This change causes the checker to emit a warning when the user has
> selected the “Show outline” option but the outline can’t be shown due to
> an exception being thrown (and caught internally).
> 
> Prior to 10a4c52, we had
> exposed exceptions to users as “Oops. That was not supposed to happen”
> errors — which made it obvious that something went wrong, and so the
> outline could not be displayed.
> 
> So, without this change to add back an indication to the user that
> something went wrong, the user has no idea why the outline did not
> display as expected.
>

**Comment by wwwXpert** [comment]
Earlier in the year, I was able to validate shopify sites with **outline** checked to review page structure according to header tags.

Currently, the validator spits out the same errors for 100% of sites hosted on shopify when outline is checked.

 `Unable to show outline. (Most likely due to a malformed HTTP response from the server hosting the document that was checked.)`

OR

`Cannot recover after last error. Any further errors will be ignored.`

You can pick any from this site: https://www.oberlo.com/blog/shopify-stores

Examples:
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.taylorstitch.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.unconditional.uk.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fhelmboots.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fmillk.co%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.bando.com%2F#cl1960c2030
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.marcwenn.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.americancrew.com%2F#cl1960c203
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.fleshbeauty.com%2F#cl1960c203

**Comment by sideshowbarker** [comment]
See https://github.com/validator/validator/issues/1011#issuecomment-766305223
