### ISSUE TITLE
Unrecognized `text` value for `background-clip` CSS property

### ISSUE THREAD

**Issue by virgofx** [validator/validator#1065]
```
Error: CSS: background-clip: text is not a background-clip value.
```
However, `text` is valid value for `background-clip` property.

![image](https://user-images.githubusercontent.com/739719/103488521-136f7d80-4dc2-11eb-84a7-7a35efab796c.png)

---
### [Reference - Mozilla Developer](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip)
![image](https://user-images.githubusercontent.com/739719/103488557-74975100-4dc2-11eb-83e0-2f524252e867.png)

![image](https://user-images.githubusercontent.com/739719/103488558-7bbe5f00-4dc2-11eb-9479-d44554c62505.png)

**Comment by nicolasalphonso** [comment]
I have just found the answer : you must use -webkit-background-clip and not background-clip

**Comment by sideshowbarker** [comment]
Thanks for reporting this — fixed in the sources and pushed to https://validator.w3.org/nu/

But as @nicolasalphonso notes in https://github.com/validator/validator/issues/1065#issuecomment-810899143, mos current browser engines don’t support `background-clip: text` — so to make things work as expected across all browsers, you currently need to use `-webkit-background-clip: text`

**Comment by QuentinFrc** [comment]
dont forget to put `background-clip : text;` after you're `background : linear-gradient(blue, red);`
Do 
` background: conic-gradient(from 270deg at 100% 100%, #1f005c, #5b0060, #870160, #ac255e, #ca485c, #e16b5c, #f39060, #ffb56b);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;`
      not 
` 
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
background: conic-gradient(from 270deg at 100% 100%, #1f005c, #5b0060, #870160, #ac255e, #ca485c, #e16b5c, #f39060, #ffb56b);`
