### ISSUE TITLE
nested <a> in <svg> pass

### ISSUE THREAD

**Issue by pkra** [validator/validator#1081]
Code to reproduce:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>nested links in svg</title>
</head>
<body>
<svg width="5cm" height="3cm" viewBox="0 0 5 3" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
  <desc>Example link01 - a link on an ellipse
  </desc>
  <a href="http://www.svgwg.org">
    <rect x=".01" y=".01" width="4.98" height="2.98" 
          fill="none" stroke="blue"  stroke-width=".03"/>
    <a href="http://www.w3.org">
      <ellipse cx="2.5" cy="1.5" rx="2" ry="1"
               fill="red" />
    </a>
  </a>
</svg>
</body>
</html>
```

This sample passes at https://validator.w3.org/nu/#textarea

If I understand the spec situation correctly, it should have an error for nested anchors. (Or at least https://html.spec.whatwg.org/#svg-0 links to https://svgwg.org/svg2-draft/ which says [nested anchors are no allowed](https://svgwg.org/svg2-draft/linking.html#Links).)

**Comment by sideshowbarker** [comment]
The `a` elements in the document shown in the issue description aren’t HTML `a` elements but instead SVG `a` elements. They’re in the SVG namespace. The HTML spec’s nesting prohibitions apply only to HTML elements, in the HTML namespace.

It probably makes sense for SVG elements to have the same prohibitions. But the place to state those would be in the SVG spec, not in the HTML spec. The HTML spec doesn’t attempt to define requirements for elements inside SVG documents.

To put it in other terms, the requirements that need to be considered are the same as if the `svg` subtree shown in the question were a completely separate standalone SVG document; that is, this:

```xml
<svg width="5cm" height="3cm" viewBox="0 0 5 3" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
  <desc>Example link01 - a link on an ellipse
  </desc>
  <a href="http://www.svgwg.org">
    <rect x=".01" y=".01" width="4.98" height="2.98" 
          fill="none" stroke="blue"  stroke-width=".03"/>
    <a href="http://www.w3.org">
      <ellipse cx="2.5" cy="1.5" rx="2" ry="1"
               fill="red" />
    </a>
  </a>
</svg>
```
In that case, whatever the HTML spec states about nesting prohibitions would be irrelevant — because it’s an SVG document, not an HTML document.

So that is in fact exactly the case here: the HTML spec doesn’t attempt to state requirement for `svg` subtrees. Any `svg` subtree needs to be considered as if it were a standalone SVG document.

**Comment by pkra** [comment]
Sorry for missing your response. 

> It probably makes sense for SVG elements to have the same prohibitions. But the place to state those would be in the SVG spec, not in the HTML spec. The HTML spec doesn’t attempt to define requirements for elements inside SVG documents.

I had included links to the SVG2 spec where it says that nested a's are invalid (in SVG) and to HTML to show that that's its point of reference for SVG. What am I missing?

**Comment by pkra** [comment]
Thanks, @sideshowbarker!
