### ISSUE TITLE
Drop rule "Attribute aria-hidden is unnecessary for elements that have attribute hidden."

### ISSUE THREAD

**Issue by masi** [validator/validator#1084]
The hidden attribute has a simple purpose: to hide an element until it is shown by a CSS rule or scripting. If it is made visible by CSS the aria-hidden attribute becomes a meaning.

So the rule only spams the reports and is a nuisance with auditors that let you discuss about any warning. Needless to say that it is also not very funny to have to explain the "issue" to customers that are worried to see warnings.

If you think the rule to be of interest please make it a "notice" not a "warning" for stated reasons.

**Comment by sideshowbarker** [comment]
The checker reports that warning because of the following requirement in the ARIA in HTML spec:

https://w3c.github.io/html-aria/#rules-wd
> It is NOT RECOMMENDED for web developers to set the ARIA role and aria-* attributes to values that match the implicit ARIA semantics defined in the table. Doing so is unnecessary and can potentially lead to unintended consequences.

And looking at the https://w3c.github.io/html-aria/#att-hidden row of the relevant table, it says that for an element with a `hidden` attribute, the implicit semantics are `aria-hidden=true`.

And therefore, per the spec requirement cited above, it’s not recommended for web developers to explicitly set `aria-hidden` for an element that already has `hidden` attribute, and the `aria-hidden` attribute is unnecessary in that case.

And that’s why the checker reports the warning: To warn web developers that using `aria-hidden` for an element that already has a `hidden` attribute isn’t recommended and is unnecessary.

@stevefaulkner, @scottaohara

**Comment by masi** [comment]
For the mentioned reason it is not unnecessary. IMHO the rule is wrong.

**Comment by stevefaulkner** [comment]
@masi the appropriate place to file a bug on this is https://github.com/w3c/html-aria/issues/ The w3c validator implements the rules it does not define them.

**Comment by masi** [comment]
@sideshowbarker thank you
