### ISSUE TITLE
Missing a validity confirmation

### ISSUE THREAD

**Issue by thomaszbz** [validator/validator#109]
I'm missing a confirmation message if a document validates against https://validator.w3.org/nu/

It only says

    Document checking completed.

which it also does when validation errors exist.

There should be a green something if everything is right. Just like the old http://validator.w3.org did it:

    This document was successfully checked as HTML5!

Plus, a green and red favicon would be nice.

**Comment by sideshowbarker** [comment]
This is intentional.

The way you can tell if the checker found any errors in the document is if the checker reports any errors. The way you tell that if the checker didn’t find any errors is if it doesn’t report any.

Unlike the legacy validator, this HTML checker is intended just as a tool for you to use to do static analysis of your HTML. It is essentially just a linter—except that the lint rules it uses are requirements that are actually defined in the HTML spec (instead of just being arbitrary rules).

It’s not a goal of this checker to tell you that a document is absolutely valid HTML5. It can’t do that, actually—because there are some requirements in the HTML spec that it isn’t testing yet, and some that it’s not capable of testing. So the best we can actually do is to make it just report any actual errors it finds. And it if doesn’t report any errors, then the document is in pretty good shape. But that doesn’t necessarily mean it’s perfectly valid, so we’re not going to lie and claim that we know it is.

I fully recognize that this is a departure from the behavior of the legacy validator. But it’s a very intentional departure. There are a lot of features of the legacy validator that are actually misfeatures that we have no plans to reproduce in this checker.

**Comment by peepo** [comment]
" no errors found "

is easily understood and meets the 'apparent' intention.

**Comment by peepo** [comment]
if you can't stomach green, perhaps orange wfy?

frankly this comes across as some elitist argument, if you are in the in crowd your in, else your out.

maybe listen to users a little more?

**Comment by peepo** [comment]
it also seems to assume both that the current guidelines are error free, and the checker also.
either of which are at least unlikely, so any errors reported, already have to be taken as merely possibilities,
rather than 'true'.

**Comment by thomaszbz** [comment]
To the point:

    Document checking completed.

just tells me that the "checking is completed". But there is no statement shown about the result of the "check": From a user's perspective, "Document checking completed" could still allow that errors were found.

Even if you intentionally did it that way, I think the intention is misleading users. I assume they don't get your intention. How should they?

As long as the validator is not stable, "No errors found" seems to be a reasonable replacement for "This document was successfully checked as HTML5!".

If there's so much uncertainity about HTML5 specs, there's no way you can go but rewrite the specs.
