### ISSUE TITLE
slot with role or aria-* attributes produces no errors

### ISSUE THREAD

**Issue by scottaohara** [validator/validator#1095]
URL being validated or code to reproduce error:
https://w3c.github.io/html-aria/tests/slot.html

No errors produced for adding `role` and `aria-*` attributes (specifically `aria-label` in tests) to `slot` element

Per [ARIA in HTML](https://w3c.github.io/html-aria/#el-slot) - no `role` or `aria-*` attributes are allowed.

**Comment by sideshowbarker** [comment]
`slot` can’t really be tested this way — and regardless, doesn’t need any restrictions.

I remember discussing this with @stevefaulkner somewhere previously, but the gist of it is that it doesn’t make much sense to put restrictions on what attributes `slot` can have — because `slot` doesn’t get parsed into the DOM. And the checker operates on the parsed document, not on the source.

If you use devtools to look at the parsed HTML of https://w3c.github.io/html-aria/tests/slot.html, you’ll see all the `slot` elements are in a document fragment that’s separate from the DOM of the document. They’re not part of the document, and they don’t get exposed to AT, right?

**Comment by scottaohara** [comment]
If this was already discussed then my apologies.  I was looking at it through the lens of just trying to get everything covered.  But if there's no reason to do this, then I'll just close this issue.  Thanks

**Comment by sideshowbarker** [comment]
> If this was already discussed then my apologies.

Yeah, I’ve been trying to see where Steve and I discussed it previously, but haven’t managed to find it yet

Anyway, I very much appreciate all the ARIA issues, and will make time this week to get them all fixed — and in general with the goal of fixing everything needed to bring the checker into full conformance with the current ARIA in HTML spec, for the next major checker release. So I may have some more questions as I work through that.
