### ISSUE TITLE
updates needed for use of aria-required in HTML

### ISSUE THREAD

**Issue by scottaohara** [validator/validator#1118]
[test cases](https://w3c.github.io/html-aria/tests/required-test.html)

test 1 expects no warnings for use of `aria-required` on elements where the `required` attribute is allowed. presently `date`, `datetime-local`, `month`, `time` and `week` `input`s do not pass the validator.

test 2 expects a warning when `aria-required=true` and `required` are used on the same element. presently only `textarea` and `select` throw a warning for the duplicate use of this attribute.

test 3 expects an error when `aria-required=false` and `required` are used on the same element. presently this is not implemented

**Comment by sideshowbarker** [comment]
> [test cases](https://w3c.github.io/html-aria/tests/required-test.html)
> 
> test 1 expects no warnings for use of `aria-required` on elements where the `required` attribute is allowed. presently `date`, `datetime-local`, `month`, `time` and `week` `input`s do not pass the validator.

Fixed by https://github.com/validator/validator/commit/78b8018c

> test 2 expects a warning when `aria-required=true` and `required` are used on the same element. presently only `textarea` and `select` throw a warning for the duplicate use of this attribute.

Fixed by https://github.com/validator/validator/commit/726e759

> test 3 expects an error when `aria-required=false` and `required` are used on the same element. presently this is not implemented

Fixed by https://github.com/validator/validator/commit/726e759

So I believe all problems reported in this issue are now fixed in the sources — and pushed to https://validator.w3.org/nu/ — and so I’m going ahead and closing this. But if I’ve missed anything, please let me know.

**Comment by scottaohara** [comment]
thank you!
