### ISSUE TITLE
Aria Labels in other Languages is marked as possible misuse

### ISSUE THREAD

**Issue by brondibur** [validator/validator#1162]
The whole point of aria labels is to ensure accessibility, and it will never be inclusive if such warnings deter developers from using them for different languages.

**Comment by scottaohara** [comment]
can you provide an example of what you mean by this?

**Comment by brondibur** [comment]
For example there is role='img' search button with aria-label='Search Button' on an english webpage, everything is absolutely fine.

But if for the hindi version one writes aria-label='खोजने की बटन', then the validator gives out a warnings "The value of attribute aria-label on element li from namespace http://www.w3.org/1999/xhtml is not in Unicode Normalization Form C" and/or "Possible misuse of aria-label".

**Comment by scottaohara** [comment]
why are you using an aria-label on an `<li>`?  doesn't the visible text already say that?

your first example of using an aria-label on a role=img makes sense that it would pass, because aria-label is allowed on a role=img.

an aria-label on an `<li>` will have varying levels of support, so warning people not to use an aria-label in that way also makes sense. 

if the visible text and the aria-label don't match, then that's even more of a concern, particularly if they're in different languages.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/1162#issuecomment-861027536
