### ISSUE TITLE
Dockerhub deleted?

### ISSUE THREAD

**Issue by bndw** [validator/validator#1189]
Hi,

https://hub.docker.com/r/validator/validator is returning a 404. Is this intentional?

EDIT: I see the registry was changed from dockerhub to github packages in https://github.com/validator/validator/commit/1b0e2b6578eeb920bf35bc3e9d8cc50655cc09cb. Hopefully it doesn't break too many folks.

**Comment by bndw** [comment]
I see the registry was changed from dockerhub to github packages in https://github.com/validator/validator/commit/1b0e2b6578eeb920bf35bc3e9d8cc50655cc09cb. Is this a long term move? This is a breaking change that I wasn't expecting, hopefully it doesn't break too many folks.

**Comment by sideshowbarker** [comment]
> [hub.docker.com/r/validator/validator](https://hub.docker.com/r/validator/validator) is returning a 404. Is this intentional?

It is intentional. Docker Hub changed its service such that it became impossible to keep providing images there in the way we had been.

> I see the registry was changed from dockerhub to github packages in [1b0e2b6](https://github.com/validator/validator/commit/1b0e2b6578eeb920bf35bc3e9d8cc50655cc09cb).

Right. https://ghcr.io/validator/validator is the place to get the images from now.

> Hopefully it doesn't break too many folks.

Unfortunately it’s going to break things — temporarily — for anybody who was using the Docker Hub images. But I could not figure out any way to push an announcement out so that people would know ahead of time — instead the way they’re going to find out is the same way that you did: Their builds will break because the Docker Hub images are no longer there, and then they’ll come back here looking for info, and hopefully end up finding the images at their new location.

**Comment by bndw** [comment]
Sounds good. I'll close the issue and if others are impacted they should be able to find it.
