### ISSUE TITLE
Attribute [@slide] not allowed on element div

### ISSUE THREAD

**Issue by WilliamGirgis** [validator/validator#1193]
Code to reproduce error: <div [@slide]="prepareRoute(outlet)" >
<router-outlet  #outlet="outlet"></router-outlet>
</div>

Error: Attribute [@slide] not allowed on element div at this point.

**Comment by WilliamGirgis** [comment]
As illustrated in the Angular animation tutorial (https://angular.io/guide/animations), a div may have a "trigger" name attribute.
I dont think Angular team would show up bad pratices.

**Comment by sideshowbarker** [comment]
The error message from the checker is correct. The `div` element isn’t allowed to have an attribute named `[@slide]`.

> As illustrated in the Angular animation tutorial ([angular.io/guide/animations](https://angular.io/guide/animations)), a div may have a "trigger" name attribute.
> I dont think the Angular team would write up bad pratices.

I think that’s something you probably want to take up with whoever wrote the Angular animation tutorial.

There’s otherwise nothing that can be changed in checker in response to this issue, so I’m going ahead and closing it.
