### ISSUE TITLE
Error on space-separated tokens in autocomplete attribute

### ISSUE THREAD

**Issue by morganwdavis** [validator/validator#1270]
URL being validated or code to reproduce error:

```
<input required class="adx_zip large" title="Enter a valid ZIP Code" aria-label="ZIP Code" name="ship_adx" maxlength="5" placeholder="ZIP Code" type="tel" pattern="^\d{5}$" autocomplete="shipping postal-code">
```

```
Error: Bad value shipping postal-code for attribute autocomplete on element input: The autofill field name postal-code is not allowed in this context.
```

Example of this exact attribute and values shown here:
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete

4.10.18.7 Autofill
...
Optionally, a token that is an ASCII case-insensitive match for one of the following strings:

"shipping", meaning the field is part of the shipping address or contact information
...
A token that is an ASCII case-insensitive match for one of the following autofill field names, excluding those that are inappropriate for the control:
...
"postal-code"

2.3.7 Space-separated tokens
A set of space-separated tokens is a string containing zero or more words (known as tokens) separated by one or more ASCII whitespace, where words consist of any string of one or more characters, none of which are ASCII whitespace.

**Comment by NiedziolkaMichal** [comment]
Provided example doesn't allow `postal-code` value, because `type` of `input` element is `tel`. According to [specification](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#inappropriate-for-the-control), `postal-code` value is allowed only in `textarea`, `select` and input of types `hidden`, `text` and `search`. [Mentioned example](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete) doesn't produce any error.

**Comment by sideshowbarker** [comment]
@NiedziolkaMichal Should we go ahead and close this one?

**Comment by NiedziolkaMichal** [comment]
@sideshowbarker I think so
