### ISSUE TITLE
Clarify the warning that is emitted when section lacks a heading

### ISSUE THREAD

**Issue by acabal** [validator/validator#1303]
**Is your feature request related to a problem? Please describe.**

v.Nu emits this warning when a section lacks a header: 

> (Section|Article) lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

This is good since headers are useful for a11y. However v.Nu also recognizes an alternative solution, which is  labeling a section with the `aria-label` attribute. If a section has `aria-label` but no header, this warning is (correctly) not emitted.

The problem is that the solution suggested by the warning is incomplete. The warning suggests to add an `h2`-`h6` element, but it says nothing about adding an `aria-label` attribute to achieve the same result.

Since it's not uncommon for sections to not have headings (like the dedications or frontispieces of ebooks), it would be useful to have the warning list all the possible ways it could be fixed.

**Describe the solution you'd like**

Update the warning message to also suggest adding `aria-label` instead of a heading, and any other affordances that might silence the warning.

**Comment by scottaohara** [comment]
i'm wary of adding this suggestion, as giving a section an aria-label is not the same thing as providing it a heading.

a heading simply ensures that the section be represented in the heading outline of the document and also allows screener users to navigate to that heading.

providing the section an accessible name (aria-label) does not add a heading to the outline.  Rather, it transforms the section from a generic element into a landmark region.  They _might_ be ok in some cases, but landmarks should be used sparingly and carefully.  If a section was not important enough to provide it a heading, it's arguable that it's important enough to add to the listing of landmarks.  Additionally, due to common misuse of landmarks (as this suggestion could promote) the web aim screen reader survey still notes that navigating by landmarks is not nearly as prevalent as navigating by heading elements.

**Comment by acabal** [comment]
OK, that makes sense. As an aside, do you know of a way to add a section to the document outline, but without using a heading? We encounter this problem often in ebooks because sections like dedications, frontispieces, untitled poems, etc., often don't have headings even though they're still discrete sections of a larger work. For example you may expect the dedication to be in the ToC of an ebook so that you can navigate back to it, even though it doesn't have a heading.

**Comment by pkra** [comment]
> As an aside, do you know of a way to add a section to the document outline, but without using a heading?

There's no document outline (unfortunately). To add something to the heading outline, you need a heading. For landmark navigation, you need a landmark.

> We encounter this problem often in ebooks because sections like dedications, frontispieces, untitled poems, etc., often don't have headings even though they're still discrete sections of a larger work. 

I'm curious as to how is this an issue for actual users. In my experience the linear reading order of an ebook is sufficient for all users. 

Sometimes sections don't have a heading which is why there's only a validation warning not a an error. Adding extra stuff won't necessarily improve the experience for AT users.

(As an aside, in an ebook context, it seems likely a dedication, frontispiece etc end up in a separate HTML file; in that case the title tag is a good and necessary place to put information.)

> For example you may expect the dedication to be in the ToC of an ebook so that you can navigate back to it, even though it doesn't have a heading.

If that's a problem for users, then add links to the ToC.
