### ISSUE TITLE
No heading outline shown when requested

### ISSUE THREAD

**Issue by nekromoff** [validator/validator#1320]
URL being validated or code to reproduce error:
https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Feyerim.sk%2Fblog%2F
```
Document checking completed.

Used the HTML parser. Externally specified character encoding was UTF-8.

Total execution time 4346 milliseconds.
```

**Comment by sideshowbarker** [comment]
The reason for this is that there’s an error in the source which prevents the checking for being able to actually check the document. I think it’s probably at line 86, where the document has `<noscript><img …`. That `img` element isn’t allowed in `noscript`, and I think it causes the HTML parser to insert an implicit `body` element. And then when it finds another `body` element later in the document, that’s a case which basically causes it to bail.

So that `img` element needs to be removed from the `noscript`.
