### ISSUE TITLE
Span tag Aria-Label Warning is Disagree!

### ISSUE THREAD

**Issue by Arungk-123** [validator/validator#1357]
Hi,

We have worked on some samples.

Work summary: DO NOT display spelled-out alt text content in a visible long description block. Instead display the text as expected by sighted users in the long description block, hide it from assistive technologies using aria-hidden=”true”, and provide the spelled-out content in a visually hidden block of text following the visible block of text

This is used for AT reading purposes why it's showing a warning in the "W3C Markup Validation Service".

**Comment by scottaohara** [comment]
More context of your situation needed.  What you’re describing raises some concerns

providing the markup snippet you are getting the warning about would also be helpful. Though if you’re getting the warning I assume it’s because you are using an aria-label on elements where it is not well supported. And if that’s the case, the validator is warning you that your solution wouldn’t be sufficient across all screen reader and browser pairings

**Comment by sideshowbarker** [comment]
Closing due to necessary details being missing.

@Arungk-123 If you’d like this re-opened, please provide the details in https://github.com/validator/validator/issues/new?assignees=&labels=bug&template=incorrect-validation.md&title=
