### ISSUE TITLE
http://validator.w3.org/check?uri=referer linking to wrong site

### ISSUE THREAD

**Issue by rbdevore** [validator/validator#1377]
using:
```html
	<a href="http://validator.w3.org/check?uri=referer">↩
	<img src="http://www.w3.org/Icons/valid-html40" alt="Valid HTML 4.0 Transitional"
	height="45" width="132"></a>
```
at the end of my web page http://www.rbdevore.com/programming/advcpp/advcpp_index.shtml
it checks page  http://www.rbdevore.com

**Comment by rbdevore** [comment]
today it went to https://motabitsltd.co.uk/

**Comment by nschonni** [comment]
It does seem to have some sort of shared variable that is spitting out other sites.
PS: The current NU validator (this repo) doesn't validate HTML 4 and uses a different URL. I kept this open since the old link you used redirects to the new one with the random site

**Comment by anna-55** [comment]
Same with me today.
`<a href="https://validator.w3.org/check?uri=referer"><img style="margin-top:-25px;" src="/images-global/HTML5_Logo_32.png" alt="Valid XHTML5"></a> `
It turned out to different sites like [https://validator.w3.org/check?uri=http%3A%2F%2Fwww.koho.or.jp](url)
Checking on [https://validator.w3.org/nu/?doc=https%3A%2F%2Fannaland.de%2F](url) annaland.de is ok. Using the referer check code on the site it turns out bad and NoScript warns cross-site scripting. I deleted the uri referer check on the site until a solution is coming up.

**Comment by drsox** [comment]
Same problem here. I'm going to throw out a guess that Cloudflare is responding to visitors with a cached page from someone else's result rather than serving a fresh result page to each visitor.
(Also, might be completely wrong :) )

**Comment by sideshowbarker** [comment]
Closing this as it see seems to be problem with the legacy validator.

Please always use https://validator.w3.org/nu/ instead.

Otherwise, please instead open an issue at https://github.com/w3c/markup-validator/issues
