### ISSUE TITLE
Not showing the no of errors and warnings

### ISSUE THREAD

**Issue by bindashsandeep** [validator/validator#139]
The old w3c validate show the no of errors and warnings. This tool doesn't shows that. Please add a section for that.

**Comment by mbnyc** [comment]
Yes. Agreed. The previous W3C validator provided the total number of errors discovered, which was very helpful. It was also more clear and user-friendly. Maybe the back-end now is better. But can we have the front-end design and formatting back? Thanks.

**Comment by bindashsandeep** [comment]
Yes I try to used the API. I tried to fetch the data from url which was JSON. But I failed to retrieve the total no of errors and warnings. I converted the JSON to Array and the Array was so confusing. May be I am beginner to php so I can't understand the Array. Can you help me to get this done? Thanks!!

**Comment by hellsing71** [comment]
+1

Does the 'Document checking completed.' message w/o any comment mean that my doc has no errors?

A simple 'It's okay' would be great.

**Comment by ramasaig** [comment]
Yes, I agree with the last comment/request. I've no idea if my document has any errors or not because all I can see is 'Document checking completed'. The 'old' checker listed any errors in great detail, which was helpful. If there were no errors there was lots of green background, so one was in no doubt.
