### ISSUE TITLE
Attribute minlength not allowed on element textarea

### ISSUE THREAD

**Issue by Rodriguevb** [validator/validator#164]
Thank for the website,

but it signals that "minlenght" isn't an attribute of textarea. It is, it works for me.

Thank you !

**Comment by cvrebert** [comment]
And it's in the spec: https://html.spec.whatwg.org/multipage/forms.html#attr-textarea-minlength

**Comment by sideshowbarker** [comment]
Yeah and I believe Firefox is the only UA that supports it at this point. If there is data to indicate otherwise please post it here. In cases where we don’t have UA support for a particular attribute in the spec, typically what we have the checker do is, emit a warning saying "This attribute isn’t supported in most UAs yet. You should not depend on it working for most users.” or something.

So it’s a choice between emitting the error we’re currently showing, or instead emitting a warning. In practice the effect is basically the same. So can go ahead and do the work to switch to this to being a warning, but that work doesn’t really buy us much.
