### ISSUE TITLE
Section headings ignored when preceded by other elements?

### ISSUE THREAD

**Issue by davidhund** [validator/validator#167]
I get a “Section lacks heading” [(source)](https://html5.validator.nu/?doc=http%3A%2F%2Fs.codepen.io%2Fdavidhund%2Fdebug%2FxGrLYy%3F&showsource=yes#l51c9) warning on [a simple example page](http://codepen.io/davidhund/pen/xGrLYy/?editors=100) where there is an `aside` as a first child of a `section`, preceding the section's heading.

As in `[section > [aside > h2] + h1]`

Why is the `h1` not picked up as the section heading when it's preceded by other sectioning content children? This seems a fairly straight-forward layout pattern.

PS: ignore me mentioning the mythical “outline” in the codepen :)

**Comment by sideshowbarker** [comment]
> Why is the `h1` not picked up as the section heading when it's preceded by other sectioning content children? This seems a fairly straight-forward layout pattern.

Because that’s what the HTML says should happen. The checker is behaving as expected per-spec here.

> PS: ignore me mentioning the mythical “outline” in the codepen :)

The outline algorithm is no myth. It’s something the follows necessarily from having the language define `article` and `section` and `aside`, etc., elements that can be nested and have `h1

**Comment by sideshowbarker** [comment]
> Why is the `h1` not picked up as the section heading when it's preceded by other sectioning content children? This seems a fairly straight-forward layout pattern.

As far as I can see, because that’s what the HTML says should happen here. I believe the checker is just behaving as expected per-spec here.

> PS: ignore me mentioning the mythical “outline” in the codepen :)

The outline algorithm is no myth. It’s something the follows necessarily from having the language define `article` and `section` and `aside`, etc., elements that can be nested and have `h1` headings or other arbitrary `h2`-`h6` heading levels.

Anyway, here for the document in that codepen is its outline:

![outline for document with section that lacks a heading](https://cloud.githubusercontent.com/assets/194984/10307098/d8c3deac-6c66-11e5-8e01-038c79218fa1.png)

Note the **section element with no heading** part there.

The gist of it is, the HTML checker conforms to the requirements in the HTML spec with regard to whether a particular section is considered to have a heading or not. And in this case, per the spec, that section does not in fact have a heading.

It’s possible that there’s a bug in the checker here, but if there is a bug, it would be a bug in the checker not conforming to the requirements in the spec. But as far as I can tell at this point, the checker is actually conforming to the requirements here.

**Comment by davidhund** [comment]
@sideshowbarker Thanks Michael,

Can you point me to the part in the spec that describes that the Section heading should not be preceded by other sectioning elements? 

All I can find is:

> “The first element of heading content in an element of sectioning content represents the heading for that section.” — [W3.org](http://www.w3.org/TR/html/sections.html#headings-and-sections)

…which seems not 100% correct since in my example the `h1` *is* the first element of heading content in my `section`, not?

However I am probably missing a lot from the technical [#outlines part](http://www.w3.org/TR/html/sections.html#outlines)…

As for the ‘Mythical Outline’ — I simply meant to make clear that I am aware there is not yet any implementation and that I should therefore not depend on the outline only for doc structure ;-)

**Comment by unor** [comment]
I think https://github.com/validator/validator/issues/103 is about the same topic.

**Comment by davidhund** [comment]
Thank you @unor — It seems the spec does deal with this scenario and indicates that the warnings are warranted.

Your comment on https://github.com/hoyois/html5outliner/issues/7#issuecomment-55496311 was helpful. It pointed me to http://www.w3.org/TR/2014/CR-html5-20140731/sections.html#sample-outlines where the spec mentions two examples dealing with exactly my issue:

> “Headings never rise above other sections[…]”
> “Thus, when an article element starts with a nav block[…]”

I am not sure what to think of this because I do feel it's un-intuitive and there are quite a few scenario's in which I believe you'd want e.g. a `nav` or `aside` preceding section headings.

However: it is not a bug with the validator, so I'll close this issue.

**Comment by sideshowbarker** [comment]
> I am not sure what to think of this because I do feel it's un-intuitive

FWIW, I agree, but I also assert that the unintuitiveness is a consequence of us having introduced sectioning elements in HTML5, which in turn can necessarily can nest to arbitrary levels and that can have arbitrary `h1`-`h6` headings that don’t match the hierarchical level of the actual section depth.

As much maligned as the outline algorithm is, it is only a means to explain what results from using those sectioning elements, and to provide a way to access a representation of the sectioning structure programmatically.

In hindsight, I personally wish that we had never introduced `section` and `article` and the rest. It seemed like a good idea at the time, and something that would at least not be harmful. But I think those elements have introduced some serious costs without any serious benefits, and are net liability to the language at this point. We would be much better off now if we had just stuck with simple old `h1`-`h6` for headings (and the implied and relatively very intuitive section hierarchy those create). Oh well…
