### ISSUE TITLE
The validator seems not to validate itself

### ISSUE THREAD

**Issue by Sebo-PL** [validator/validator#170]
It seems tke validator web interface does not produce a valid HTML output: https://validator.w3.org/nu/?doc=https%3A%2F%2Fvalidator.w3.org%2F

I would expect this site to be an example of the valid one.

**Comment by sideshowbarker** [comment]
> It seems tke validator web interface does not produce a valid HTML output: https://validator.w3.org/nu/?doc=https%3A%2F%2Fvalidator.w3.org%2F
> 
> I would expect this site to be an example of the valid one.

The URL you cite is not for the Web interface for the checker that runs from the source code in this this; instead you need to try this: https://validator.w3.org/nu/?doc=https%3A%2F%2Fvalidator.w3.org%2Fnu

Also, this checker (the Nu Html Checker) is not a tool for people to use for making assertions about whether a particular document is “valid” or not. Instead, it’s a tool for developers to find unintended mistakes—mistakes they might have otherwise missed.
