### ISSUE TITLE
odd error for inut type=checkbox

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#181]
when checking https://validator.w3.org/nu/?doc=http%3A%2F%2Fs.codepen.io%2Fstevef%2Fdebug%2FGpLXMd

Error: Bad value checkbox for attribute type on element input.

also does not indicate role=heading is an error which it is
http://w3c.github.io/html-aria/#input-checkbox

**Comment by sideshowbarker** [comment]
Actually what this message is saying is ”An `input` element with `role=heading` can’t have `type=checkbox`—which I agree is sorta an unintuitive way of looking at it, but this is a generic error message coming from the schema-checking code, and for this case we don’t have control over which attribute that schema-checking part of the code flags as the “wrong” one. It’s really just a case of “`role=heading` and `type=checkbox` can’t be used together on the same element”, but the schema-checking part of the code doesn’t give any control to have it state the error message that way.

So, I’m reluctantly closing this because I have not way to fix this readily without yanking all the current ARIA checking for `input` elements and rewriting it completely in a different part of the code. (Which I may end up doing eventually but not ready to take in on at the moment.)
