### ISSUE TITLE
parser does not detect </p> after <ul>

### ISSUE THREAD

**Issue by NetAktiv** [validator/validator#184]
It seems that the parser does not find the &lt;/p&gt; tag if the paragraph contains an unnumbered list as in the example below

&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;meta charset="utf-8" /&gt;
    &lt;title&gt;UL Test&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;p&gt;Text in P is OK&lt;/p&gt;
    &lt;ul&gt;&lt;li&gt;UL and LI inside BODY is OK&lt;/li&gt;&lt;/ul&gt;
    &lt;p&gt;&lt;ul&gt;&lt;li&gt;UL and LI inside P misses /P ERROR&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by NetAktiv** [comment]
$lt;!DOCTYPE html$gt;
$lt;html$gt;
$lt;head$gt;
    $lt;meta charset="utf-8" /$gt;
    $lt;title$gt;UL Test$lt;/title$gt;
$lt;/head$gt;
$lt;body$gt;
    $lt;p$gt;Text im P$lt;/p$gt;
    $lt;ul$gt;$lt;li$gt;UL und LI im BODY$lt;/li$gt;$lt;/ul$gt;
    $lt;p$gt;$lt;ul$gt;$lt;li$gt;UL und LI im P$lt;/li$gt;$lt;/ul$gt;$lt;/p$gt;
$lt;/body$gt;
$lt;/html$gt;

**Comment by NetAktiv** [comment]
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;meta charset="utf-8" /&gt;
    &lt;title&gt;UL Test&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;p&gt;Text im P&lt;/p&gt;
    &lt;ul&gt;&lt;li&gt;UL und LI im BODY&lt;/li&gt;&lt;/ul&gt;
    &lt;p&gt;&lt;ul&gt;&lt;li&gt;UL und LI im P&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by sideshowbarker** [comment]
The `<ul>` element is not allowed as child of a `<p>` element, because:
* [the `<p>` element is only allowed to contain phrasing content](https://html.spec.whatwg.org/multipage/semantics.html#the-p-element) and
* [the `<ul>` element is not phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2)
So trying to put a `<ul>` inside a `<p>` element is prohibited by the HTML spec.

As far as what browsers are required to actually do with it, if a `p` element is open and a parser encounters a `<ul>` start tag, the HTML parsing algorithm requires parsers to close the `p` element (essentially to act as if there’s a `</p>` end tag) before opening the `ul` element.

For the text of the actual requirement, see the part of the [The "in body" insertion mode](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody) section of the HTML spec that that reads **A start tag whose tag name is one of: "address", "article", "aside", "blockquote", "center", "details", "dialog", "dir", "div", "dl", "fieldset", "figcaption", "figure", "footer", "header", "hgroup", "main", "menu", "nav", "ol", "p", "section", "summary", "ul"**, which says, *If the stack of open elements has a p element in button scope, then close a p element.*

So the cause of the behavior that you’re seeing is that the parser has already closed the `p` element before the `ul` element, so when it encounters that `</p>` end tag after the `ul` element, it reports it as an error because there is no longer any open `p` element in need of an end tag.

**Comment by NetAktiv** [comment]
I can unterstand the behaviour of Browsers, but not the absolutely missleading error message of the parser. Nobody will read all the HTML documentation to find the cause. The parser should report something like ul not allowed inside p or p implicitely closed by ul.

**Comment by harrykao** [comment]
Thanks for the great explanation. I think I've been confused by this in the past as well. I think warning at the point of implicit close would be a very nice improvement.
