### ISSUE TITLE
Support Web Components Standard

### ISSUE THREAD

**Issue by realistschuckle** [validator/validator#211]
You know, things like `<link rel="import" href="...">` and `is` attributes for custom elements.

**Comment by zcorpan** [comment]
Custom elements is shipped in Chrome and Opera 
https://www.chromestatus.com/features/4696261944934400

**Comment by sideshowbarker** [comment]
The checker now has custom-elements support, and has had `<template>` support for a while now.

Those are the only two Web Components features currently supportable in the checker.

As far as the `rel=import` HTML Imports feature, the checker will not be getting support for that, because no browsers other than Chrome plan to implement it as currently specified. For more info:

* https://platform-status.mozilla.org/#html-imports
   https://hacks.mozilla.org/2014/12/mozilla-and-web-components/

   > Mozilla will not ship an implementation of HTML Imports. We expect that once JavaScript modules — a feature derived from JavaScript libraries written by the developer community — is shipped, the way we look at this problem will have changed.

* https://webkit.org/status/#feature-html-imports
   > Multiple browser vendors have raised concerns about how the HTML imports currently works. For example, its dependency model is not fully compatible with ES6 Modules. We are exploring other ways to package web components by integrating into ES6 Modules with other browser vendors.

Given all that, I think that at this point there are no other Web Components features to add to the checker support for, so I am going ahead and closing this issue. But feel free to add comments here and if I’ve missed something, we can re-open this.
