### ISSUE TITLE
The Content-Security-Policy directive `manifest-src` is not recognised

### ISSUE THREAD

**Issue by borisschapira** [validator/validator#215]
The manifest-src directive, as described in https://w3c.github.io/webappsec-csp/ seems to provoke a validation error.

![screenshot_2016-01-09-12-23-05](https://cloud.githubusercontent.com/assets/284742/12221023/ca61037a-b78a-11e5-9036-3edb3eeea5c9.png)

[As Mike signaled on Bugzilla](https://www.w3.org/Bugs/Public/show_bug.cgi?id=29366#c1), the general issue here is that the validator don’t yet support anything in CSP Level 3 that isn’t in CSP2: https://w3c.github.io/webappsec-csp/#changes-from-level-2

**Comment by cvrebert** [comment]
This appears to be due to an upstream bug in https://github.com/shapesecurity/salvation
Looks like they haven't implemented `manifest-src` yet.

**Comment by sideshowbarker** [comment]
@borisschapira Thanks for taking time to report this here.

> This appears to be due to an upstream bug in https://github.com/shapesecurity/salvation
> Looks like they haven't implemented manifest-src yet.

Yeah, since for CSP checking the HTML checker depends on [Salvation](https://github.com/shapesecurity/salvation)—and I’m not sure yet about the position/plans of @shekyan and @michaelficarra (the Salvation developers) with regard to supporting `manifest-src` or other new features in CSP3 at this point—I want to keep this issue open here, pending what happens upstream.

**Comment by sideshowbarker** [comment]
I’ve fixed this and pushed it to https://validator.w3.org/nu/ (sorry it took so long)

**Comment by borisschapira** [comment]
@sideshowbarker Sorry ? Don't you dare be sorry about fixing open source software. I am the one who is sorry for not being able to do it myself :) 

Thanks a lot !
