### ISSUE TITLE
Should SVG / MathML schemas use w:iri-ref instead of xsd:anyURI?

### ISSUE THREAD

**Issue by dd8** [validator/validator#216]
The HTML5 RNC schemas use the w:iri-ref data type for URLs (based on WHATWG URL Standard). 

The MathML and SVG schemas use xsd:anyURI (which is based on RFC 2396)
http://www.w3.org/TR/xmlschema-2/#anyURI

The WHATWG URL standard allows a wider range of valid URLs than RFC 2396, so a URL that's a valid img/@src in HTML may not be a valid image/@xlink:href in SVG-in-HTML

**Comment by sideshowbarker** [comment]
The validator implements a URL checker that conforms to the current URL Standard, which essentially obsoletes RFC 2396, and which other specs for the platform (such as the HTML spec) normatively reference. So I suggest filing a bug against the SVG spec to get it updated so that it aligns with other current specs for the platform and references the current URL Standard rather than RFC 2396.

As far as the validator behavior goes in the mean time, I don’t intend to (re)implement an RFC 2396 IRI checker in parallel to the URL checker.

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this per https://github.com/validator/validator/issues/216#issuecomment-216295263

But feel free to re-open it if you believe it needs more discussion here.
