### ISSUE TITLE
'meta' with @name and @property in 'body'

### ISSUE THREAD

**Issue by unor** [validator/validator#224]
*HTML+RDFa 1.1* [extends HTML5](https://www.w3.org/TR/rdfa-in-html/#extensions-to-the-html5-syntax) so that 

* `meta` can be used in the `body` if it has a `property` attribute:

 > If the `@property` RDFa attribute is present on the `link` or `meta` elements, they MUST be viewed as conforming if used in the `body` of the document. More specifically, when `link` or `meta` elements contain the RDFa `@property` attribute and are used in the `body` of an HTML5 document, they MUST be considered flow content.

* `meta` is not required to have a `name` attribute if it has a `property` attribute:

 > If the RDFa `@property` attribute is present on the `meta` element, neither the `@name`, `@http-equiv`, nor `@charset` attributes are required and the `@content` attribute MUST be specified.

So using `name` *and* `property` in the same `meta` element seems to be fine:

    <meta name="description" property="schema:description" content="foo" />

With https://validator.w3.org/nu/, this validates if used in the `head`, but gives an error if used in the `body`:

> Error: Attribute `name` not allowed on element `meta` at this point.

Given the quotes from above, **is this really an error or should it be allowed to have a `meta` element with `name` *and* `property` in the `body`?**

(FWIW, a `link` element with `rel` *and* `property` validates in `body`.)

**Comment by sideshowbarker** [comment]
The HTML spec itself is clear that if `meta` element has `name` attribute, it’s only allowed where “metadata content” is expected, which is in the `head` and not in the `body`. I recognize that the HTML+RDFa spec adds a requirement that it the `meta` element be allowed in the `body` if it has a `property` attribute, but the HTML+RDFa spec is ambiguous about whether a `meta` element with a `property` attribute but that also has a `name` attribute must be allowed in the `body`, overriding the specific explicit requirement in the HTML spec prohibiting a `meta` element with a `name` attribute from appearing the `body`.

I argue that if the HTML+RDFa spec editors did intend to override that more specific requirement in the HTML spec with regard to `meta` elements with `name` attributes, then they should have made the HTML+RDFa state it explicitly, and if that’s the intent, then the HTML+RDFa spec should be revised.

I otherwise don’t plan to make any change to the checker behavior around this. This question has come up before in W3C bugzilla or here, and already been resolved.

Incidentally, I don’t understand what if any the actual use cases might be for specifying both the `name` and `property` attributes on a `meta` element, but if there are any clear use cases for it, the place to address those would be in the HTML+RDFa spec, and the people to consider them would be the editors of the HTML+RDFa spec.

So I’m going to go ahead and close/resolve this issue here. But feel free to re-open it if you have new information to add—or short of that of course feel free to comment further here regardless.
