### ISSUE TITLE
Validator exhibits different behavior for 'upload file' and 'direct input'

### ISSUE THREAD

**Issue by smv94** [validator/validator#235]
When I directly copied and pasted the contents of my file, the validator didn't raise any errors or warnings. The output was

Info: The Content-Type was text/html. Using the HTML parser.
Info: Using the schema for HTML with SVG 1.1, MathML 3.0, RDFa 1.1, and ITS 2.0 support.
Document checking completed. No errors or warnings to show.

But when I uploaded the same file, it showed me

Info: The Content-Type was text/html. Using the HTML parser.
Error: The character encoding was not declared. Proceeding using windows-1252.
Info: Using the schema for HTML with SVG 1.1, MathML 3.0, RDFa 1.1, and ITS 2.0 support.

**Comment by sideshowbarker** [comment]
Short answer is that you should always put a `<meta charset=utf-8>` element into every document.

If you put `<meta charset=utf-8>` into your document, the difference in behavior with the checker that you have described here will go away.

Longer answer: The behavior you describe is expected behavior. The reason for the difference you see is that when you copy/paste into the direct-input form, the checker automatically sets the Content-Type to UTF-8. (And it gives no option to set it any other encoding.)

But when you upload a file, the checker does not automatically assume UTF-8. Instead it looks for a `<meta charset=utf-8>` element in the document, and if it doesn’t find one, it behaves as if the Content-Type is windows-1252—because for legacy reasons that’s what the HTML requires all HTML parsers to do if they don’t otherwise have any encoding information (either from a Content-Type header or from a `<meta charset=…>` element.

**Comment by smv94** [comment]
Thanks for the explanation! Actually I'm still new enough to HTML that I forget things like <meta charset>, and I was relying on the Nu Checker to catch mistakes like this.

Also, maybe I'm missing something obvious, but I still don't understand why there should be any difference in behavior for different methods of input. As long as 'Validate full document' is selected in the text input option, shouldn't the checker make sure that the character encoding is declared in the HTML document as the checker does for an uploaded file?

**Comment by sideshowbarker** [comment]
> As long as 'Validate full document' is selected in the text input option, shouldn't the checker make sure that the character encoding is declared in the HTML document just as it does for an uploaded file?

In the case of an uploaded file without a `<meta charset>` element, the checker emits an error message because no character encoding has been set anywhere.

In the case of using the text-input, the checker itself sets the character encoding, and so no `<meta charset>` element is needed.

That makes sense because the use cases for the two options is a bit different: The text-input option is intended for testing shorter snippets more than for testing real documents, while the file-upload option is more for testing real, full documents.

**Comment by smv94** [comment]
Then I believe the 'Validate full document' option in the text input section is misleading.

**Comment by sideshowbarker** [comment]
> Then I believe the 'Validate full document' option in the text input section is misleading.

Please always use https://validator.w3.org/nu/ and never use https://validator.w3.org/

The https://validator.w3.org/nu/ checker run code from this repo and has no **Validate full document** option for text input. That option is only provided in the https://validator.w3.org/ UI, which is a legacy entry point that runs code from https://github.com/w3c/markup-validator.

Several options in the https://validator.w3.org/ UI are simply ignored when requests are passed on to https://validator.w3.org/nu/. And https://validator.w3.org/nu/ has options which that UI doesn’t provide.

So the right UI to start from these days is https://validator.w3.org/nu/
