### ISSUE TITLE
Wrong pass <time>

### ISSUE THREAD

**Issue by momdo** [validator/validator#238]
Related report: by @tzik in w3c/html#62

The <a href="https://www.w3.org/TR/html5/text-level-semantics.html#the-time-element">HTML5 spec</a> says:
>A time element that does not have a datetime content attribute must not have any element descendants.

Thus:
```html
<time>2016-02-01</time><!-- Valid -->
<time><span>2016-02-01</span></time> <!-- Should be invalid -->
```

**Comment by sideshowbarker** [comment]
>The HTML5 spec says

The URL you cite there is actually not to the HTML spec but instead to a copy of it that had unaudited differences.

When citing the HTML spec in comments for this repo, please cite URLs to the actual HTML spec, and not URLs to copies or forks of it in other places.

**Comment by foolip** [comment]
Thanks for reporting @momdo! I neglected to check validator behavior when preparing https://github.com/whatwg/html/pull/637...

I'm wondering, is this restriction meaningful? The value is defined in terms of `textContent`, so child elements will not be a problem for implementations. Should HTML just allow it, perhaps?

---
A fond memory: In my very first round of bug reports on HTMLMediaElement, I wrote to the WHATWG but linked to the W3C copy of the spec. @zcorpan relayed to me that this had slightly amused @Hixie, and this was my first glimpse into the WHATWG-W3C dynamic.

Maybe we should write a short explainer of the current state of HTML stewardship that we can point to? Simply given search engine rankings, we should expect many/most new contributors to reference the W3C copy, and it has come up a few times in the last week or so.

@domenic @annevk

**Comment by annevk** [comment]
We could add some text to https://wiki.whatwg.org/wiki/Fork_tracking perhaps. https://annevankesteren.nl/2016/01/film-at-11 also provides a summary of why a particular fork is bad. The easiest is probably pointing out that both Google and Mozilla have a documented policy of preferring the WHATWG version of the standard over the forked version. Perhaps we should have a blog post making those nuances clear?

**Comment by domenic** [comment]
There's also https://html.spec.whatwg.org/#is-this-html5? and https://html.spec.whatwg.org/#history-2

**Comment by sideshowbarker** [comment]
@momdo Thanks much for reporting this. I’ve fixed it in the sources to align with the change @foolip made in https://github.com/whatwg/html/commit/d82d29ddfccaa2d1806dc9ed48fd3bbbc0181912 (for https://github.com/whatwg/html/pull/637), and pushed the fix to https://validator.w3.org/nu/

**Comment by sideshowbarker** [comment]
> I'm wondering, is this restriction meaningful? The value is defined in terms of textContent, so child elements will not be a problem for implementations.

I guess I’d turn your question around and ask what the rationale would be for eliminating the restriction.

If the use case is that somebody wants to style the contents of a `time` element, they can just put a `datetime` attribute on the element to give the machine-readable value, and then do whatever they want with the `time` content (as far as putting markup in it to get particular styling of parts of it).

Anyway, I think the rationale for the restriction is to make the parsing behavior of `datetime`-less `time` element content consistent with the parsing behavior for the parsing of the `datetime` attribute value—by requiring exactly the same microsyntax/datatype in both cases. So any processing app that does something with `time` can use exactly the same parsing code for parsing `datetime`-less  `time` element content as it does for parsing the `datetime` attribute value.

I think it’s worth remembering that browsers aren’t the target processors for the `time` element. Browsers don’t actually parse either the `datetime` attribute value or the `time` element content (because browsers don’t actually do anything with any of it; there’s no spec requirement for them to do that—no special UA behavior for processing it or doing anything with it).

So the use cases are instead about processing contexts other than native processing by UAs themselves (and including use cases that it’s imaginable may include contexts outside of JavaScript and/or that don’t work from a DOM).

So anyway given that the current restriction provides benefits to developers (that is, the benefits that come from the microsyntax and parsing behavior being exactly the same in both cases), then IMHO we should not relax the restriction unless/until we have bugs being reported about it, and use cases where relaxing it would clearly provide more benefits than what the current restriction is providing.

**Comment by stevefaulkner** [comment]
On 8 February 2016 at 03:08, Michael[tm] Smith <notifications@github.com>
wrote:

> Browsers don’t actually parse either the datetime attribute value or the
> time element content
>

Note: the time element role and the datetime attribute are exposed as
object attributes in browser Ia2 accessibility API implementations [1].

https://www.w3.org/TR/html-aam-1.0/#el-time

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by foolip** [comment]
@sideshowbarker, do you mean tools that assume validity and therefore can just assume a single text child instead of doing the equivalent of `textContent`? That would be kind of strange, if they don't control the input it wouldn't match how the spec defines the [datetime value](https://html.spec.whatwg.org/#datetime-value). Unless processing requirements match, does this restriction have any value?

**Comment by sideshowbarker** [comment]
> do you mean tools that assume validity and therefore can just assume a single text child instead of doing the equivalent of textContent?

No, I think tools shouldn’t need to assume anything. And so, considering it from that perspective, I think the fix is to make the processing requirements match the restriction—which means we should change the spec so it doesn’t specify that the value is obtained by getting the textContent of the element, but instead specifies that parsing must fail if the element has any child element nodes.

> That would be kind of strange, if they don't control the input it wouldn't match how the spec defines the datetime value. Unless processing requirements match, does this restriction have any value?

Yeah agreed the processing requirements should match the restriction, so IMHO the right fix would be to make the spec require that parsing of the element content fails if it contains any child element nodes.

**Comment by sideshowbarker** [comment]
@stevefaulkner you wrote:
> the time element role and the datetime attribute are exposed as
> object attributes in browser Ia2 accessibility API implementations

What about the content of `time` element itself? Is it exposed in the same way? I mean other than just as normal element content, but instead as an object attribute in the (special?) way that the `role` and `datetime` values are. And to be clear, are you saying the value of the `datetime` attribute in fact gets exposed as something specially identifiable as a date+time? I mean, as opposed to being exposed in whatever way any of the element’s other attributes might be exposed. Or do you mean the other attributes don’t get exposed at all, but that the `role` and `datetime` attributes do?

**Comment by foolip** [comment]
Following up on the spec discussion in https://github.com/whatwg/html/issues/644

**Comment by stevefaulkner** [comment]
On 8 February 2016 at 06:42, Michael[tm] Smith <notifications@github.com>
wrote:

> What about the content of time element itself? Is it exposed in the same
> way? I mean other than just as normal element content,
>
it is exposed in the usual way


> but instead as an object attribute in the (special?) way that the role
> and datetime values are. And to be clear, are you saying the value of the
> datetime attribute in fact gets exposed as something specially
> identifiable as a date+time? I mean, as opposed to being exposed in
> whatever way any of the element’s other attributes might be exposed.
>
yes,

see related chrome bug
https://code.google.com/p/chromium/issues/detail?id=480861
firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1095927



> Or do you mean the other attributes don’t get exposed at all, but that the
> role and datetime attributes do?
>

not all attributes (or elements) get exposed, the datetimehas been
implemented specifically as an object attribute as has the element role.
Prior to this the time elment did not have an 'accessible' as is the case
for many other text level elements, which are not exposed with any special
significance in the acc layer

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>
