### ISSUE TITLE
ie=edge,chrome=1

### ISSUE THREAD

**Issue by bbirdiman** [validator/validator#241]
please fix the validator so this doesn't return an error. thank you.

>   meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"

Error: A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.

**Comment by cvrebert** [comment]
Note that Google discontinued Chrome Frame two years ago.

**Comment by bbirdiman** [comment]
ok, cool, i'm just copying code that i find in lots and lots and lots of websites.
why do you suppose all of those people still keep including this statement?
i'm thinking that it probably must be because they think their users still need it.
moreover, what is it about this statement that causes the .html to be _invalid?_
i mean, it could be flagging a warning, right? but no, it's flagging an _error_...
i don't pretend to understand these things, but i would like to continue to be
able to place some value on having my files validate.  but if it's meaningless...

**Comment by sideshowbarker** [comment]
I think HTML5Boilerplate and similar things used to have to `IE=edge,chrome=1` value. So the reason you seen documents that still have it is that the authors of those documents just haven’t updated them.

Anyway, the checker is simply [following the rules in the HTML spec](https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-x-ua-compatible), which says:

> For meta elements with an http-equiv attribute in the X-UA-Compatible state, the content attribute must have a value that is an ASCII case-insensitive match for the string "IE=edge".

**Comment by sideshowbarker** [comment]
> my question is simply this:
> will it affect any users adversely if i simply delete the "chrome=1"?

It won’t affect any users adversely. It only ever affected users of Chrome Frame—which there were only relatively few of anyway. And as an earlier comment here pointed out, Google discontinued Chrome Frame two years ago.

But anyway, you rightly shouldn’t just trust anything I or anybody says about that. You should research it and find out for yourself. And you should do the same for any similar markup you put in your documents.

> then i will be forced to conclude that i must cease to care whether my files "validate"

That’s the wrong way to look at things. First off, there’s a reason this tool is called the Nu Html Checker and not the Nu Html Validator. Because the tool is a checker to help you, personally, find unintended mistakes in your own documents. You shouldn’t care whether your files "validate" nor whether anybody else knows whether or not they "validate".

And if the checker emits a message about something that you don’t consider a mistake but instead is something you’re doing intentionally, then you can just ignore the message (or even use the Message Filtering option in https://validator.w3.org/nu/ to persistently ignore it for every document you check).

**Comment by bbirdiman** [comment]
>   It won’t affect any users adversely.

thank you for that information.  and because you
have responded with such kindness and in full,
i will return the favor, even though this was the
only real important question i had regarding this.


>   You should research it and find out for yourself. 

asking an expert is a good way to do research.    :+)


>   You shouldn’t care whether your files "validate" 
>   nor whether anybody else knows whether or not they "validate".

i do understand what you are saying, in general terms.

but i have no need for the scorn which geek nerds use
to try to discredit me, with non-validation as an excuse.
when someone is saying "your code doesn't validate"
as a dirty trick to induce people to ignore your product,
it's better strategically to just deny them that justification.

and more importantly, in the world of electronic-books,
some e-book retailers require that your files validate,
or they refuse to carry them. yes, it's as simple as that.
so even if i personally decline to care about validation,
other entities out in the world require it as a benchmark.

again, thank you for your kind and informative response.

-bowerbird

**Comment by brett1337** [comment]
Shouldn't this still be a bug though? The error says it does not contain "IE=edge" but it does contain "IE=edge". Am I missing something?
