### ISSUE TITLE
Proper mailto: rejected

### ISSUE THREAD

**Issue by RHaworth** [validator/validator#248]
I coded this link:
`&lt;a href='mailto:Roger%20W%20Haworth%20&#60;W@RHaworth.net&#62;?subject=W3%20Validator'>`
but validator rejects it saying:

> Bad value mailto:Roger%20W%20Haworth%20<W@RHaworth.net>?subject=W3%20Validator for attribute href on element a: Illegal character in scheme data: < is not allowed.

`<a href='mailto:Roger%20W%20Haworth%20&#60;W@RHaworth.net&#62;?subject=W3%20Validator'>Try it now!</a>`

This a "proper" email address in the format `"Plain Name &lt;Name@domain&#62;"`. Clicking on the link takes me to Outlook Express perfectly happily. I have escaped the `<>` around the email address as `&#60;` and `&#62;` (if I use `&lt;` and `&gt;` the error still reports). So why is Validator rejecting it?

**Comment by sideshowbarker** [comment]
`mailto:Roger%20W%20Haworth%20%3CW@RHaworth.net%3E?subject=W3%20Validator`

**Comment by sideshowbarker** [comment]
> I have escaped the `<>` around the email address as `&#60;` and `&#62;` (if I use `&lt;` and `&gt;` the error still reports).

To escape (encode) particular characters in URLs, you need to [percent-encode](https://en.wikipedia.org/wiki/Percent-encoding) (aka “URL encode”) them.

So instead of using `&#60;` and `&#62;`, you need to `%3C` and `%3E`.

The following tables show the percent-encoded representations for some common characters:

- https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters  
- https://en.wikipedia.org/wiki/Percent-encoding#Character_data

<table cellpadding="6px" border="1" style="border:1px solid #C0C0C0; border-collapse:collapse; background-color:white;">
<caption>Reserved characters after percent-encoding</caption>
<tbody><tr>
<td><code><a href="/wiki/Exclamation_mark" title="Exclamation mark">!</a></code></td>
<td><code><a href="/wiki/Number_sign" title="Number sign">#</a></code></td>
<td><code><a href="/wiki/Dollar_sign" title="Dollar sign">$</a></code></td>
<td><code><a href="/wiki/Ampersand" title="Ampersand">&amp;</a></code></td>
<td><code><a href="/wiki/Apostrophe_(mark)" title="Apostrophe (mark)" class="mw-redirect">'</a></code></td>
<td><code><a href="/wiki/Parenthesis" title="Parenthesis" class="mw-redirect">(</a></code></td>
<td><code><a href="/wiki/Parenthesis" title="Parenthesis" class="mw-redirect">)</a></code></td>
<td><code><a href="/wiki/Asterisk" title="Asterisk">*</a></code></td>
<td><code><a href="/wiki/Plus_sign" title="Plus sign" class="mw-redirect">+</a></code></td>
<td><code><a href="/wiki/Comma_(punctuation)" title="Comma (punctuation)" class="mw-redirect">,</a></code></td>
<td><code><a href="/wiki/Slash_(punctuation)" title="Slash (punctuation)">/</a></code></td>
<td><code><a href="/wiki/Colon_(punctuation)" title="Colon (punctuation)">:</a></code></td>
<td><code><a href="/wiki/Semicolon" title="Semicolon">;</a></code></td>
<td><code><a href="/wiki/Equal_sign" title="Equal sign" class="mw-redirect">=</a></code></td>
<td><code><a href="/wiki/Question_mark" title="Question mark">?</a></code></td>
<td><code><a href="/wiki/@" title="@" class="mw-redirect">@</a></code></td>
<td><code><a href="/wiki/Square_bracket" title="Square bracket" class="mw-redirect">[</a></code></td>
<td><code><a href="/wiki/Square_bracket" title="Square bracket" class="mw-redirect">]</a></code></td>
</tr>
<tr>
<td><code>%21</code></td>
<td><code>%23</code></td>
<td><code>%24</code></td>
<td><code>%26</code></td>
<td><code>%27</code></td>
<td><code>%28</code></td>
<td><code>%29</code></td>
<td><code>%2A</code></td>
<td><code>%2B</code></td>
<td><code>%2C</code></td>
<td><code>%2F</code></td>
<td><code>%3A</code></td>
<td><code>%3B</code></td>
<td><code>%3D</code></td>
<td><code>%3F</code></td>
<td><code>%40</code></td>
<td><code>%5B</code></td>
<td><code>%5D</code></td>
</tr>
</tbody></table>

<table cellpadding="6px" border="1" style="border:1px solid #C0C0C0; border-collapse:collapse; background-color:white;">
<caption>Common characters after percent-encoding (ASCII or UTF-8 based)</caption>
<tbody><tr>
<td><a href="/wiki/Newline" title="Newline">newline</a></td>
<td><a href="/wiki/Space_(punctuation)" title="Space (punctuation)">space</a></td>
<td><code><a href="/wiki/Double_quote" title="Double quote" class="mw-redirect">"</a></code></td>
<td><code><a href="/wiki/Percent_sign" title="Percent sign">%</a></code></td>
<td><code><a href="/wiki/Hyphen" title="Hyphen">-</a></code></td>
<td><code><a href="/wiki/Full_stop" title="Full stop">.</a></code></td>
<td><code><a href="/wiki/Angle_bracket" title="Angle bracket" class="mw-redirect">&lt;</a></code></td>
<td><code><a href="/wiki/Angle_bracket" title="Angle bracket" class="mw-redirect">&gt;</a></code></td>
<td><code><a href="/wiki/Back_slash" title="Back slash" class="mw-redirect">\</a></code></td>
<td><code><a href="/wiki/Caret" title="Caret">^</a></code></td>
<td><code><a href="/wiki/Underscore" title="Underscore">_</a></code></td>
<td><code><a href="/wiki/Grave_accent" title="Grave accent">`</a></code></td>
<td><code><a href="/wiki/Curly_bracket" title="Curly bracket" class="mw-redirect">{</a></code></td>
<td><code><a href="/wiki/Vertical_bar" title="Vertical bar">|</a></code></td>
<td><code><a href="/wiki/Curly_bracket" title="Curly bracket" class="mw-redirect">}</a></code></td>
<td><code><a href="/wiki/Tilde" title="Tilde">~</a></code></td>
</tr>
<tr>
<td><code>%0A</code> <i>or</i> <code>%0D</code> <i>or</i> <code>%0D%0A</code></td>
<td><code>%20</code></td>
<td><code>%22</code></td>
<td><code>%25</code></td>
<td><code>%2D</code></td>
<td><code>%2E</code></td>
<td><code>%3C</code></td>
<td><code>%3E</code></td>
<td><code>%5C</code></td>
<td><code>%5E</code></td>
<td><code>%5F</code></td>
<td><code>%60</code></td>
<td><code>%7B</code></td>
<td><code>%7C</code></td>
<td><code>%7D</code></td>
<td><code>%7E</code></td>
</tr>
</tbody></table>
