### ISSUE TITLE
Inconsistent validation for the longdesc attribute on the img element

### ISSUE THREAD

**Issue by Kobee1203** [validator/validator#262]
I noticed a validation issue for the `longdesc` attribute on the `img` element on the 3 sites you mention in README.md: checker.html5.org, html5.validator.nu and validator.w3 .org/nu

Here is the HTML content to validate:
```
<! DOCTYPE html>
<Html>
  <Head>
    <Meta charset="UTF-8">
    <Title>A Pen by Captain Anonymous</ title>
  </ Head>
  <Body>
    <Img src="http://placehold.it/350x150" alt="Little Cat" longdesc="http://placehold.it/350x150/text" />
  </ Body>
</ Html>
```

The first 2 sites (checker.html5.org, html5.validator.nu) return the following error:

> The longdesc attribute on the img element is obsolete. Use a regular element has to link to the description.

When I use your library `vn.jar`, I get the same error.

But the site validator.w3.org/nu does not return an error.

The W3C specification does not seem to indicate that the longdesc attribute is deprecated: 
https://www.w3.org/TR/html-longdesc/

Do you know why the 3 sites are not consistent on the validation of the `longdesc` attribute on the `img` element?

**Comment by stevefaulkner** [comment]
@Kobee1203 the reason is that (checker.html5.org, html5.validator.nu) do not check conformance requirements for the [W3C HTML specification](http://w3c.github.io/html/), they check the conformance requirements for the whatwg html spec.

If you want to check against w3c html you need to use:
https://validator.w3.org/nu/
or
https://validator.w3.org/

>When I use your library vn.jar, I get the same error.

I believe there is a flag you need to set to check w3c html, but @sideshowbarker should be able to answer this definitively.
HTH

**Comment by sideshowbarker** [comment]
Everything in Steve’s comment is correct.


> > When I use your library vnu.jar, I get the same error.
>
> I believe there is a flag you need to set to check w3c html, but @sideshowbarker should be able to answer this definitively.

The `vnu.jar` distribution is built without the option for following the W3C spec, and there is no run-time flag that can be set to enable the option. The reason is that the support for following the W3C spec needs to be enabled at build time, because it affects how the checker code is actually built.

So the gist of it is that if you want a `vnu.jar` file that follows the W3C spec, you need to build it on your own from the sources.

**Comment by Kobee1203** [comment]
Ok. Thanks for your responses.

I have a little suggestion.

I tested with the following maven dependency:
<dependency>
	<groupId>nu.validator</groupId>
	<artifactId>validator</artifactId>
	<version>15.6.29</version>
</dependency>

This jar seems to be built without the option for the W3C spec, because I get the same result, but the jar description is the following:

An HTML-checking library (used by https://html5.validator.nu and the HTML5 facet of the W3C Validator)

Should you not indicate that the library checks the conformance requirements for the whatwg html spec and not W3C?

**Comment by Kobee1203** [comment]
To complete my previous comment, the description that I quoted is in the following file: https://github.com/validator/validator/blob/master/build/build.xml, and this is visible to the following URL: http://mvnrepository.com/artifact/nu.validator/validator/15.6.29

**Comment by sideshowbarker** [comment]
> This jar seems to be built without the option for the W3C spec, because I get the same result, but the jar description is the following:
> 
> An HTML-checking library (used by https://html5.validator.nu and the HTML5 facet of the W3C Validator)

Good point. I’ve changed the description to not mention the W3C Validator.

> this is visible to the following URL: http://mvnrepository.com/artifact/nu.validator/validator/15.6.29

I can’t go back and change that but will be doing a new release in the near future, so the revised description will show up in the corresponding place after I deploy it to maven central.
