### ISSUE TITLE
Validation fails on characters : È and É

### ISSUE THREAD

**Issue by SensicalCat** [validator/validator#297]
Validation fails on characters : È and É

observe this query : 
https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fshotonwhat.com%2Fgods-of-egypt-2016#cl1758c201

notice items 10 - 17

**Comment by sideshowbarker** [comment]
You need to either convert the source of that document to UTF-8 using iconv or something, or serve it with an ISO-8859-1 character encoding.

That’s because the problem you are seeing is due to that doc being served with a UTF-8 character encoding, but it’s not actually encoded in UTF-8—instead it seems to be encoded in ISO-8859-1.

So the HTML parser tries to parse it as UTF-8 but then runs into character sequences that aren’t allowed in UTF-8 because they are instead character sequences for  ISO-8859-1.

You can verify that here:

https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fshotonwhat.com%2Fgods-of-egypt-2016&charset=ISO-8859-1&laxtype=yes

If you give the checker the `charset=ISO-8859-1` and `laxtype=yes`, that tells it to override the character encoding the document is being served with and instead use ISO-8859-1. If you look at the checker results at the URL above, you’ll see the messages about those È and É characters are no longer reported if you check it as ISO-8859-1.

**Comment by SensicalCat** [comment]
Thank you for the info. Interesting to note that the actual file is utf-8 and the header encoding for the compiled page is also utf-8. So it would seem my issue is with the htmlentities parameter being used is not properly converting to uft-8. Further investigation on my side is needed. Appreciate the time you took to review this. Thanx!

**Comment by sideshowbarker** [comment]
cheers!
