### ISSUE TITLE
Internal Error with this testcase

### ISSUE THREAD

**Issue by mstange** [validator/validator#301]
If I run the URL https://bug1276161.bmoattachments.org/attachment.cgi?id=8758032 through https://checker.html5.org/, I get the result "Internal Error: Oops. That was not supposed to happen. A bug manifested itself in the application internals. Unable to continue. Sorry. The admin was notified."

**Comment by sideshowbarker** [comment]
Thanks for catching this. The cause was some code in the checker’s content-type parser which did not expect to find a header like `Content-Type:  text/html; name="canvas-dashed-line.html"; charset=` with a `charset=` param but no value. But the fix is now pushed to https://checker.html5.org/:

https://checker.html5.org/?doc=https%3A%2F%2Fbug1276161.bmoattachments.org%2Fattachment.cgi%3Fid%3D8758032

…that now reports:

> Error: Document served with malformed Content-Type header:  text/html; name="canvas-dashed-line.html"; charset=. The empty string is not a valid encoding name.

By the way, bmoattachments.org seems be doing something broken with content-types. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1276820 to report it. If you look at https://bugzilla.mozilla.org/attachment.cgi?id=8758032&action=edit you’ll see the content-type is just `text/html` there, so it seems like something funky is happening to make https://bug1276161.bmoattachments.org/attachment.cgi?id=8758032 serve it with that borked `Content-Type:  text/html; name="canvas-dashed-line.html"; charset=`  header.

**Comment by mstange** [comment]
Thanks, that was fast!
