### ISSUE TITLE
Bogus "Start tag head seen but an element of the same type was already open."

### ISSUE THREAD

**Issue by walles** [validator/validator#302]
Paste the below document into https://validator.w3.org/#validate_by_input.

I get:
```
Error: Start tag head seen but an element of the same type was already open.
From line 4, column 1; to line 4, column 6
</script>↩<head>↩  <me
```

Since there's no head tag already open on line 4 I'd prefer if the validator didn't say that.

Test case:
```html
<!DOCTYPE html>
<html>
<script src="weatherclock.js"></script>
<head>
  <meta charset="utf-8">
  <title>Weather Clock</title>
  <link rel="stylesheet" type="text/css" href="weatherclock.css" />
</head>
<body onload="main();">

<p class="header">
  <a href="https://github.com/walles/weatherclock">Source code on GitHub</a>
  <br/>
  <a href="test.html">Unit Tests</a>
  <br/>
</p>

<svg
  id="weatherclock"
  width="95%" height="95%"
  xmlns="http://www.w3.org/2000/svg" version="1.1"
  viewbox="-50 -50 100 100">
  <circle cx="0" cy="0" r="45" stroke="black" stroke-width="5" fill="white" />

  <line id="hour-hand" class="hour-hand" x1="0" y1="0" x2="0" y2="-24" />
  <line id="minute-hand" class="minute-hand" x1="0" y1="0" x2="0" y2="-28" />
</svg>

<pre id="log"></pre>

<p class="footer">Weather forecast from <a href="yr.no">yr.no</a>, delivered by
  the <a href="http://met.no/English/">Norwegian
  Meteorological Institute</a> and the <a href="http://www.nrk.no/">NRK</a>.</p>

</body>
</html>
```

**Comment by cvrebert** [comment]
I believe the misplaced `<script>` tag implicitly opens `<head>` in this case.

**Comment by sideshowbarker** [comment]
> I believe the misplaced `<script>` tag implicitly opens `<head>` in this case.

Yes

> Since there's no head tag already open on line 4 I'd prefer if the validator didn't say that.

In fact there is a head element already open on line 4, because as @cvrebert noted, per the HTML parsing algorithm in the HTML spec and per the HTML parsing behavior in every major browser, when a parser encounters that `script` start tag at line 4, it opens in the DOM a `head` element and then adds that `script` element to the DOM as a child of that `head` element.

Then when the parser runs into that `<head>` start tag in the next line, it doesn’t create yet another `head` element in the DOM (since it just opened one), so it just drops that (redundant) `head` start tag on the floor and emits the error message you see, and moves on.

**Comment by sideshowbarker** [comment]
Closing but please feel free to re-open if you think think this needs further consideration.
