### ISSUE TITLE
firstLine not being included in JSON output

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#305]
Hello, it looks like `firstLine` is not being included in the JSON output, although it appears when using the HTML form:

https://validator.nu/?doc=http%3A%2F%2Fjaimeiniesta.com&out=json

**Comment by sideshowbarker** [comment]
Is this a regression? Has it ever appeared in the JSON output? I'm wondering if the docs on the JSON output state that it's included. If so, then this is clearly a bug.

**Comment by sideshowbarker** [comment]
So yeah the [JSON docs do mention `firstLine`](https://github.com/validator/validator/wiki/Output:-JSON#the-firstline-firstcolumn-lastline-and-lastcolumn-numbers)

**Comment by sideshowbarker** [comment]
[Examining the code](https://github.com/validator/validator/blob/master/src/nu/validator/messages/JsonMessageEmitter.java#L74) indicates that this is intentional, and it’s also [documented in the JSON-format docs](https://github.com/validator/validator/wiki/Output:-JSON#the-firstline-firstcolumn-lastline-and-lastcolumn-numbers):

> The `"firstLine"` *number* indicates the first line onto which the source range associated with the message falls. **If the attribute is missing, it is assumed to have the same value as `"lastLine"`**.

**Comment by jaimeiniesta** [comment]
Thank you for the clarification, it makes sense :+1:
