### ISSUE TITLE
Non-urlencoded URLS, is it an error/warning or no?

### ISSUE THREAD

**Issue by ssteinerx** [validator/validator#31]
Referencing: https://bugzilla.validator.nu/show_bug.cgi?id=841

This is killing me as the FaceBook API returns unencoded URLs and I'm not sure if I have to urlencode every one of them to be valid...

Thanks,

Steve

**Comment by sideshowbarker** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1153920

**Comment by sideshowbarker** [comment]
I think I’m going to give up on trying to get this fixed upstream in the parser any time soon, and will instead just add some code to catch the exception the parser throws for this, and just drop it on the floor rather than reporting it. Then downside is that will cause some errors to be unreported for some ampersand cases that the HTML spec does actually define as errors, but I think the tradeoff is probably going to be worth it in this case.

**Comment by sideshowbarker** [comment]
Fixed in v16.1.1 and after https://github.com/validator/validator/releases/latest and pushed to https://validator.w3.org/nu/
