### ISSUE TITLE
Invalid encoding prevents message.url from being set

### ISSUE THREAD

**Issue by jzaefferer** [validator/validator#313]
Trying to validate this file results in messages about bad encoding, but without the `url` property being set: [index.txt](https://github.com/validator/validator/files/336851/index.txt)

Originally reported at https://github.com/jzaefferer/grunt-html/issues/97

**Comment by sideshowbarker** [comment]
The cause of this is that those `Malformed byte sequence` messages (exceptions) are generated/thrown by the HTML parser (and then caught and emitted by the core message-handling code in the checker). And unlike the messages that are generated in the checker code itself, those messages from the HTML parser don’t have a URL/filename associated with them, because at the point where those messages are generated, the HTML parser code does not have the URL—for some reason I don’t clearly understand at this point (or have forgotten).

So I will need to investigate this a bit further to first figure out if it’s even fixable in the current architecture.

The code was originally designed with an assumption that it would only be checking one file at a time, and in that case the code can globally set the `messages.url` property (that is, on the wrapper around all the individual `message` items), so that even if an individual `message` lacks a `url`, the URL can be determined by looking at `messages.url` on the wrapper.

But the way the standalone command-line checker works is that when it’s used,  `messages.url` is never set on the wrapper. The reason is that in the case of the Web-based checker service, which only checks one document at a time, when the message handler is instantiated it can be given the URL for a document and it then uses that to set the `messages.url` property of the wrapper. But for the case of the command-line checker, when we instantiate the message handler it is not for a single document but instead for any arbitrary number of documents, so we can’t globally set the  `messages.url` property.

Anyway, all that said, things would still work as expected (without need for any consuming code to check the `messages.url` property, if the URL were actually getting exposed to the HTML parser for these cases. So I’ll try to see if I can make that happen.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I believe this will fix the specific problem reported at https://github.com/jzaefferer/grunt-html/issues/97 as well as the general problem of some messages lacking a `message.url`.

Lemme know if you want me to do another release for y’all to update to. I can get it done pretty quickly, and it will include [a fix for not reporting errors for comments ending in `<!-->`](https://github.com/validator/validator/issues/310), which was a regression introduced by the comment-checking changes in the 16.6.18 and 16.6.20 releases that I reckon some of your users are likely to run into and report soon—because `<!-->` is apparently very commonly used in IE conditional comments, which are found still in tons of sites (e.g., many or most Alexa top 100 sites).
