### ISSUE TITLE
Random warning (This document appears to be written in Latin but the html start tag has lang="en".)

### ISSUE THREAD

**Issue by BeFiveINFO** [validator/validator#321]
I recently started seeing warning like the followings when I validate html files on server with https://validator.w3.org/:

> Warning: This document appears to be written in Latin but the html start tag has lang="en". Consider using lang="la" (or variant) instead.
> From line 1, column 16; to line 2, column 16
> TYPE html>↩<html lang="en">↩<head

But it does not alway report the error. It often says the page is fine without any warnings.

Is this a known issue? I googled the sentence of error message but I found no matches. Thank you for your attention in advance.

**Comment by sideshowbarker** [comment]
I very recently added a language-detection feature and the intermittent nature of the warnings is due to the fact that it bases the language detection on a random sample of text from the document. So it’s not deterministic. However it is usually accurate as a far as the determination it makes from what it samples. But the feature still needs some refinement and troubleshooting yet.

So if you have documents for which the validator it is misidentifying the language (even if it is intermittent), it would help me a lot of you could could provide the URLs for me to test with. You could either e-mail them to me privately at [mike@w3.org](mailto:mike@w3.org), or just post some as comments here.

**Comment by BeFiveINFO** [comment]
thank you for a reply!

I just found out that it was greek text I was using in the html file. Here is an example html markups that can replicate the warning.

It gets a warning with 2 paragraphes of greek text
https://gist.github.com/BeFiveINFO/3f716fcd7565f438ae29d60da0c4334f

... while there is no problem with a paragraph of greek text 
https://gist.github.com/BeFiveINFO/25eaac7460bd6d8b260414efc602ccc7

**Comment by sideshowbarker** [comment]
> It gets a warning with 2 paragraphes of greek text

I think you mean Latin

> https://gist.github.com/BeFiveINFO/3f716fcd7565f438ae29d60da0c4334f

OK yeah getting a warning for that is expected, because it’s Latin text and there is no `<html lang>`.

> ... while there is no problem with a paragraph of greek text 
> https://gist.github.com/BeFiveINFO/25eaac7460bd6d8b260414efc602ccc7

The reason for that is, the checker does not attempt to detect the language unless it has 512 characters of text to evaluate. And that one paragraph has only about 450 characters.

**Comment by BeFiveINFO** [comment]
yes. The Lorem ipsum dummy text is often used to fill sample layouts. Will we then have to start using dummy text in the same language as specified by the lang attribute if we want to avoid the warning?

Alternative to lorem ipsum found on google :
http://graphicdesign.stackexchange.com/questions/18325/alternative-to-lorem-ipsum-dummy-text-for-websites

**Comment by sideshowbarker** [comment]
> Will we then have to start using dummy text in the same language as specified by the lang attribute if we want to avoid the warning?

Yes. Either that or ignore the warning until such time as the document is actually populated with real text.

> Alternative to lorem ipsum found on google :
> http://graphicdesign.stackexchange.com/questions/18325/alternative-to-lorem-ipsum-dummy-text-for-websites

Yes. The lang value can somewhat affect the layout of a document—at least as far as things like hyphenation—so it seems like a good idea to have the correct lang value set even when you’re the stage of only evaluating the layout.

**Comment by BeFiveINFO** [comment]
Thank you very much for clarification as well as valuable information about the issue, which is really helpful. :)

**Comment by sideshowbarker** [comment]
closing per https://github.com/validator/validator/issues/321#issuecomment-234252594
