### ISSUE TITLE
lang ca detected

### ISSUE THREAD

**Issue by DaniSpringer** [validator/validator#328]
but it's just html. it is lorem ipsum text though.

**Comment by cvrebert** [comment]
Does the problem occur with https://checker.html5.org ?

**Comment by sideshowbarker** [comment]
Yeah for the case of documents with just lorem ipsum text, the warning about lang can of course be safely ignored (since such documents are not actually intended to be read for meaning).

I intentionally do not support language detection for Latin in the checker (because adding Latin support has the effect of reducing the confidence with which the language detector can identify other languages), so in some cases the language detector will guess that it’s Catalan, and in other cases, some other Romance language.

**Comment by DaniSpringer** [comment]
I can't seem to find the original file, but I tried another html file containing lorem ipsum, and both w3 and checker returned no errorsor warnings.

**Comment by sideshowbarker** [comment]
> I can't seem to find the original file, but I tried another html file containing lorem ipsum, and both w3 and checker returned no errorsor warnings

You might get different results if you reload. That’s because one of the (mis)features of the language-detection library we use it that it does not do its language analysis against the entire text you feed it, but instead on some random sample of the text. So it can produce different results at different times from the same input document.

So anyway I’m working on creating a specific language profile to recognize lorem ipsum text, which make help solve the problem. I’ll post an update here after I push the change for that.

**Comment by sideshowbarker** [comment]
By the way in looking through the W3C Internalization guides, I found [something relevant](https://www.w3.org/International/questions/qa-no-language#nonlinguistic):

> Use the subtag `zxx` when the text is known to be not in any language.

> This would apply for text such as type samples, part numbers, illustrations of binary data, etc. The definition of zxx in the IANA Language Subtag Registry is 'no linguistic content'.

So if you have a document that is just lorem ipsum text, it probably should have `<html lang=zxx>`.

I’ll update the HTML checker soon to not emit any “This document appears to be written in…” warnings for documents that have `<html lang=zxx>`.

**Comment by sideshowbarker** [comment]
OK I implemented _Lorem-ipsum_ detection and pushed it to https://checker.html5.org/ and https://validator.w3.org/nu/

**Comment by sideshowbarker** [comment]
Closing this for now, since the <i>Lorem ipsum</i> detection seems to be working as expected. Feel free to reopen if needed.
