### ISSUE TITLE
No SNI support (fails with handshake_failure)

### ISSUE THREAD

**Issue by tkrotoff** [validator/validator#33]
Error message from validator.nu: `IO Error: Received fatal alert: handshake_failure`

Might be due to [Server Name Indication (SNI)](https://en.wikipedia.org/wiki/Server_Name_Indication#No_support).

Examples:
- Error with my website (https://osteo15.com) that uses SNI: https://html5.validator.nu/?doc=https%3A%2F%2Fosteo15.com
- No problem with my website and W3C validator: http://validator.w3.org/check?uri=https%3A%2F%2Fosteo15.com
- No problem with https://validator.nu/: https://html5.validator.nu/?doc=https%3A%2F%2Fvalidator.nu

**Comment by sideshowbarker** [comment]
Yes, it's a known issue that the backend code doesn't support SNI. See https://github.com/validator/validator/issues/22#issuecomment-69160365

The fix is for us to add SNI support. @hsivonen is already looking into that.

The workaround for now is to use http://validator.w3.org because that does a fetch itself of the document directly, using a separate https backend, and then uses our web-services interface to send the document to our (HTML5-checking) backend. (In other words, it bypasses our own https-fetching code.)

**Comment by tkrotoff** [comment]
Ok, thx for the quick reply

**Comment by sideshowbarker** [comment]
I've just now pushed this change to the W3C validator. So the following should now work—
http://validator.w3.org/nu/?doc=https%3A%2F%2Fosteo15.com%2F

**Comment by tkrotoff** [comment]
:+1: works on http://validator.w3.org/ (not on https://html5.validator.nu/ and https://validator.nu/)

**Comment by sideshowbarker** [comment]
> works on http://validator.w3.org/ (not on https://html5.validator.nu/ and https://validator.nu/)

Yeah https://html5.validator.nu/ and https://validator.nu/ are @hsivonen’s servers and get updated separately from the W3C service.
