### ISSUE TITLE
Where's the Fatal Error here?

### ISSUE THREAD

**Issue by ravilura** [validator/validator#335]
Hello,

can you please check the line and tell why the validator reports the fatal error for it:

`<body class="home page page-id-8 page-template-default wpb-js-composer js-comp-ver-4.11.2.1 vc_responsive" >`

https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fpergola.kz%2F

Thanks a lot in advance!

**Comment by sideshowbarker** [comment]
The cause is the [`<div>` start tag in the `head` of that document a line 142](https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fpergola.kz%2F#l142c15).

You can’t have a `div` inside a `noscript` element in the `head`. If you do, that `<div>` start tag causes HTML parsers to assume the `body` of the document has started, so the HTML parser essentially creates a `<body>` start tag in the DOM before that `div`. But then after that, it runs into the `<body>` start tag, and you get that error because the document already has a `<body>`.

That is a fatal error in the checker because the checker does streaming parser and it cannot backtrack at that point. So it just stops.

Anyway the fix is to remove that `div` from your `noscript` element.

**Comment by ravilura** [comment]
Hi Michael,
thanks for your quick response.

The first fatal error was fixed successfully with your help.

But after rechecking it was found another fatal error in: 
`<a class="icon_box_button" style="color:;" href="http://pergola.kz/pergola-system/" target="_self" >`
From line 432, column 8; to line 432, column 107

Can you please check it again:
https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fpergola.kz%2F#l142c15

**Comment by sideshowbarker** [comment]
That document ha an `<a>` start tag at line 430 and then inside it at line 432, another `<a>` start tag. An `a` element can’t be nested inside another `a` element.

**Comment by ravilura** [comment]
You are right. it a mess of a code here to be fixed!

Thanks again for your assist!
