### ISSUE TITLE
February 16 Release WAR Broken

### ISSUE THREAD

**Issue by Pacoup** [validator/validator#35]
Whenever I deploy this release's WAR (https://github.com/validator/validator/releases/tag/20150216) on my Tomcat 7 server on Debian 7, I get a 404 when accessing localhost/vnu.

Any idea? Previous release is working fine.

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I've not actually tested the WAR but will try to today. In the mean time, maybe @jacobq might have some insight on what the cause is.

**Comment by sideshowbarker** [comment]
OK I've been able to reproduce this with Tomcat 7 running on a Debian system. But I can't yet tell what what the cause is. I tested with the previous vnu.war release from https://github.com/validator/validator/releases/download/20150207/vnu-20150207.war.zip and everything works as expected. But if I replace that with the vnu.war from https://github.com/validator/validator/releases/download/20150216/vnu-20150216.war.zip I get 404 just as you described.

**Comment by jacobq** [comment]
I'll take a peek when I get home in about an hour. Thanks for reporting &
investigating.

-Jay

**Comment by sideshowbarker** [comment]
Thanks @jacobq. Peeking into the Tomcat localhost.log file just now, I see a bunch of `Unsupported major.minor version 52.0` so I'm pretty sure the cause is just that I recently updated my build environment to Java8, but my Debian environment is still using a Java7 VM. I thought I had addressed by having my local build environment set up to call javac with `1.6` for the `-target` and `-source` options but it seems maybe for the WAR build there's something else I need to set to make it backward-compatible.

**Comment by sideshowbarker** [comment]
OK, I believe I've got it fixed. I rebuilt and re-generated the WAR file and re-uploaded it to https://github.com/validator/validator/releases/download/20150216/vnu-20150216.war.zip

I tested it in my Debian Java7+Tomcat7 environment and it's now working as expected for me. So please give it a try and let me know if it fixes the problem for you.

The cause was just pilot error on my part: I hadn't actually built the the sources with `-target=1.6` and `-source=1.6` passed to javac. Instead I had just called it without passing `-target` or `-source` to javac at all, so since I'm building under Java8, that created code that'll only run in Java8 VM.

I'll try to add some test automation to catch this so it doesn't happen.

Thanks much for catching this.

**Comment by sideshowbarker** [comment]
All right, to make sure this doesn't regress later, I've changed the defaults in the build script such that we now compile Java6+ compatible classes in vnu.war/vnu.jar builds by default: https://github.com/validator/validator/commit/81365b22f532d282fdc5833d8a3525f3ec2c39ae

And I've also added a related step to our Travis CI checks:  https://github.com/validator/validator/commit/45044aa45ea93db78263ba55fcc557362f42e03c

**Comment by Pacoup** [comment]
Yup, this is working now. Thanks so much for the support.
