### ISSUE TITLE
Incorrect language

### ISSUE THREAD

**Issue by radioegor146** [validator/validator#357]
Hi. The website http://new.rockpaperscissors.site88.net is in Russian language, but w3validator say that language of this page is Estonian. Thank you.

**Comment by sideshowbarker** [comment]
That site is not displaying at the moment due to a server-side PHP error. I’ll check again later to see if it’s up again but if in the mean time you get that PHP problem corrected, if you post a comment here I’ll try it again in the checker right away to see if I can get the incorrect-language problem fixed.

**Comment by radioegor146** [comment]
Hi. Sorry for not working website. Now it is working.

**Comment by sideshowbarker** [comment]
OK, thanks—due to some recent fixes I made, it looks like the checker is no longer misidentifying the language of the page, so I’m going ahead and closing this now. But if you find that it is again misidentifying the language of any documents, please raise a new issue here.
