### ISSUE TITLE
<meta itemprop="description" name="description" content="my description"> reports an error

### ISSUE THREAD

**Issue by don-esteban** [validator/validator#370]
Hello all,

the following code reports an error

    <!DOCTYPE html>
    <html itemscope itemtype="http://schema.org/WebPage">
    <head>
        <meta itemprop="description" name="description" content="my description">
        <title>Test</title>
    </head>
    <body>
    </body>
    </html>

The error message states: _Attribute `name` not allowed on element `meta` at this point._

The following variants are all passing the test:

    <meta itemprop="description" content="my description">

    <meta name="description" content="my description">

Do I miss something?

**Comment by sideshowbarker** [comment]
The [section on `meta` in the spec says](https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names):

> Exactly one of the `name`, `http-equiv`, `charset`, and `itemprop` attributes must be specified.

Because the `meta` element in the document in the issue description already has an `itemprop` attribute, when the checker then sees the `name` attribute, it emits the _Attribute `name` not allowed on element `meta` at this point_ error message—because the spec says that a `meta` element can have only one or the other, and the `name` attribute occurs after the `itemprop` attribute.

If the document instead had `<meta name="description" itemprop="description" content="my description">` (that is, with the `itemprop` attribute after the `name` attribute), then the checker would instead emit the message  _Attribute `itemprop` not allowed on element `meta` at this point_.

**Comment by don-esteban** [comment]
Thanks! I do understand.
