### ISSUE TITLE
'Validate by Direct Input' didn't detect my unclosed tags.

### ISSUE THREAD

**Issue by sklarjeb** [validator/validator#372]
It didn't detect some of my unclosed tags and said that no errors were found instead.
the input in question: https://gist.github.com/sklarjeb/ef0c252ee9c5bb3d65153cba19f243c9

**Comment by sideshowbarker** [comment]
The start tag and end tag for the `body` element are both optional, and the end tag for the `tr` element is optional. And there are other elements whose start tags and end tags are optional. See https://html.spec.whatwg.org/multipage/syntax.html#optional-tags for the details.

**Comment by cvrebert** [comment]
Omitted close tags are often not errors per se (see e.g. `<p>` tags), since HTML's parser defines how to unambiguously handle tag soup (usually by inferring close tags when nesting would be nonsensical).

It is unfortunate that the validator does not offer an option to detect such situations though, since they frequently indicate authoring mistakes. In the interim, tools like HTMLHint and htmllint can be used to detect missing close tags.

**Comment by sklarjeb** [comment]
Oh sorry. I didn't know that they were optional. Thanks for the infro!

**Comment by sideshowbarker** [comment]
closing per https://github.com/validator/validator/issues/372#issuecomment-248787403
