### ISSUE TITLE
Wrong link for Media Queries in error message

### ISSUE THREAD

**Issue by bert-github** [validator/validator#396]
When the Nu Html Checker detects an error in a MEDIA attribute, it helpfully presents a link to the Media Queries specification...

... except that it doesn’t link to the real specification, but to an editors’ draft, which changes often and is likely to give incorrect information.

The link

    https://drafts.csswg.org/mediaqueries/

should be

    https://www.w3.org/TR/css3-mediaqueries/

**Comment by sideshowbarker** [comment]
The checker doesn’t emit messages with links to `https://drafts.csswg.org/mediaqueries/`.

Instead it emits messages with links to  either`http://drafts.csswg.org/mediaqueries/#media-types` or to `http://drafts.csswg.org/mediaqueries/#mf-deprecated` specifically.

> it doesn’t link to the real specification, but to an editors’ draft,

It’s the intent of the checker to align with what’s actually implemented in browsers, regardless of whether the spec most closely matching what’s implemented in browsers happens to be in TR space.

It’s an unfortunate fact that many specs in TR space are not up to date with current implementations, and no consistent effort is made to ensure that specs in TR space are kept up to date.

So in general I can’t trust that if I point users of the checker to a document in TR space, the users will be getting accurate, up-to-date information. So I don’t have the checker messages link to TR docs.

> which changes often and is likely to give incorrect information

It doesn’t matter if other parts of the spec might change often. What matters is if any information at `drafts.csswg.org/mediaqueries/#media-types` or `drafts.csswg.org/mediaqueries/#mf-deprecated` has changed in any way that doesn’t match the current checker behavior.

So if specific information has changed in either of those sections in such a way that it doesn’t align with the current checker behavior, then please file a bug describing what the difference are so that I can decide if we need to update the checker

**Comment by sideshowbarker** [comment]
For just one recent example of why I don’t trust pointing people (especially implementors) at TR, see the thread at https://twitter.com/bz_moz/status/794675380296843264. (Basically, Boris Zbarsky seems to have ended up having his time wasted by working from a TR draft that the CSS WG already knew had been obsoleted months before by changes to the ED—and nobody bothered to try to get the TR draft updated to match current reality.)

**Comment by sideshowbarker** [comment]
Closing for now, as there’s been no further discussion on this here in 3 weeks. Feel free to re-open.
