### ISSUE TITLE
X-UA-Compatible HTTP header 

### ISSUE THREAD

**Issue by p2tu** [validator/validator#397]
Nu Html Checker displays error:
X-UA-Compatible HTTP header must have the value IE=edge, was IE=Edge,chrome=1. http://noored.ee/

I have that in header:
<meta http-equiv="X-UA-Compatible" content="IE=edge">

Why error tho?

**Comment by sideshowbarker** [comment]
> Nu Html Checker displays error:
> X-UA-Compatible HTTP header must have the value IE=edge, was IE=Edge,chrome=1.  http://noored.ee/
>
> I have that in header:
> `<meta http-equiv="X-UA-Compatible" content="IE=edge">`

Yeah but that’s an element in the document, not an HTTP header.

The error message is not about that element, it’s about the HTTP header.

> Why error tho?

The error is because http://noored.ee/ is being served with this HTTP header:

> X-UA-Compatible: IE=Edge,chrome=1

The full headers can be viewed in browser devtools or using `curl` or something:

```
$ curl -I http://noored.ee/
HTTP/1.1 200 OK
Date: Mon, 07 Nov 2016 03:24:52 GMT
Server: Apache / ZoneOS
Link: <http://noored.ee/wp-json/>; rel="https://api.w.org/"
Set-Cookie: wpml_referer_url=http%3A%2F%2Fnoored.ee%2F; expires=Tue, 08-Nov-2016 03:24:52 GMT; path=/
Set-Cookie: _icl_current_language=et; expires=Tue, 08-Nov-2016 03:24:52 GMT; path=/
Set-Cookie: wfvt_1348928751=581ff4044dbe2; expires=Mon, 07-Nov-2016 03:54:52 GMT; path=/; httponly
Set-Cookie: _icl_current_language=et; expires=Tue, 08-Nov-2016 03:24:52 GMT; path=/
Cache-Control: max-age=600
Expires: Mon, 07 Nov 2016 03:34:52 GMT
Vary: User-Agent
X-UA-Compatible: IE=Edge,chrome=1
Content-Type: text/html; charset=UTF-8
```

So to fix that error the Web server would need to be configured to instead send the header as just `X-UA-Compatible: IE=Edge`.

**Comment by p2tu** [comment]
Thanks! Makes sense now :)
Gonna look into it. Topic resolved ;)

**Comment by sideshowbarker** [comment]
Super—thanks for taking time to report this
