### ISSUE TITLE
"valid date or time string" is not defined in HTML

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#404]
https://wiki.whatwg.org/wiki/MicrosyntaxDescriptions#date-or-time

There exists [parse a date or time string](https://html.spec.whatwg.org/multipage/infrastructure.html#parse-a-date-or-time-string) but no "valid date or time string". I suppose it was replaced by [valid date string with optional time](https://html.spec.whatwg.org/multipage/infrastructure.html#valid-date-string-with-optional-time), used by ins/del elements.

Should update the checker and the wiki.

**Comment by sideshowbarker** [comment]
The current checker code uses `common.data.datetime | common.data.date` to check the datatypes of the ins/del elements (rather than using a single datatype), and the effect of that for an error is, e.g.:

> Error: Bad value foo for attribute datetime on element ins: The literal did not satisfy the datetime with timezone format. The literal did not satisfy the date format.
> …
> Syntax of datetime with timezone:
> > A global date and time string; that is, a date, followed by a “T” or a single space, followed by a time, followed by time-zone information, where: the date must be in the form YYYY-MM-DD • the time must begin in the form hh:mm, followed by :ss, optionally followed by “.” and one, two, or three or digits • the time-zone information must be either “Z” or in the form +hh:mm or the form -hh:mm • > Examples: 1996-01-01T12:05:25-02:00, 1996-01-01T12:05:25Z

> Syntax of date:
> > A date in the form YYYY-MM-DD. Example: 2002-09-29.

That is, it emits two separate “The literal did not satisfy the foo format” statements, and the emits two separate “Syntax of…” datatype elaborations.

I think that’s fine but please reopen this if you think instead it should only emit one “The literal did not satisfy the foo format” statement, and only one “Syntax of…” datatype elaboration (because I guess if it’s important enough I could consolidate the checks into being exposed as a single datatype).
