### ISSUE TITLE
allow checking of error pages

### ISSUE THREAD

**Issue by koalatux** [validator/validator#413]
Error pages may have HTML content, and one may want to check that for validity, too. The validator now just says "IO Error: HTTP resource not retrievable. The HTTP status from the remote server was: 404."

The classic validator supported that, and the checkbox "Validate error pages" under "More Options" is now a bit useless.

**Comment by sideshowbarker** [comment]
Thanks very much for taking time to raise this issue. I implemented the option in it 536359a and pushed it to https://checker.html5.org/ and https://validator.w3.org/nu/

It adds a new `checkerrorpages` query parameter to the checker HTTP API, along with a **check error pages** option in the checker Web UI (under **Options**).

If set, the behavior is as with the similar option the legacy validator: It causes the checker to retrieve a document and check it even if the server response is a 404 or other non-200 status; e.g.:

https://validator.w3.org/nu/?checkerrorpages=yes&doc=https://github.com/does-not-exist

Otherwise, the checker behaves as it always has: It doesn’t retrieve the document but instead emits a message indicating the document was not retrieved, along with the HTTP status code.
