### ISSUE TITLE
allow h1-h6 in legend elements

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#418]
please implement this change in the checker
refer to https://github.com/w3c/html/issues/724

**Comment by alanfluff** [comment]
Please excuse my ignorance, but would I be right in thinking this change is still not live here https://validator.w3.org/nu/#textarea as I still see

> Error: Element h3 not allowed as child of element legend

Or is there an ETA when it will be, or an alternate version of the validator?

Thanks in advance for this most useful resource.

**Comment by sideshowbarker** [comment]
> Please excuse my ignorance, but would I be right in thinking this change is still not live here https://validator.w3.org/nu/#textarea 

It’s live again there now.

(The change was reverted some time ago due to the fact it previously wasn’t in what’s now agreed by everybody to be the canonical HTML spec, but instead was only in the W3C fork of that spec. But with https://github.com/whatwg/html/pull/5090/ (https://github.com/whatwg/html/commit/db558772627ea2df4e74c470733de9946e5b4e8d) it was added to the current HTML spec, so with https://github.com/validator/validator/commit/89a1221f1faab09ffb7590b8a73c40cf0662cad4 it’s now been added back to the HTML checker.)

**Comment by alangistfluff** [comment]
Great, thanks.
