### ISSUE TITLE
Async attribute on link tag flagged as error

### ISSUE THREAD

**Issue by TimvdLippe** [validator/validator#437]
A link which is async (such as `<link rel="import" href="foo.html" async>`) will be flagged as an error. However, async is allowed on these imports.

**Comment by sideshowbarker** [comment]
The checker intentionally doesn’t support any features from the HTML Imports specification.

The reason is, that spec isn’t implemented in any browsers other than Chrome, and at this point will never be implemented in any other browser—because reps from browser projects have made it clear they’re not going to support it but instead will implement something the integrates with ES6 Modules.

(However, I think no browsers other than Edge have added support for ES6 Modules yet, so it’s going to be at least a year before there’s a cross-browser way to do HTML imports).

So anyway, bottom line is that the checker is going to continue to flag `link[async]` as an error unless/until it’s ever re-defined in a spec other than the old HTML Imports spec.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/437#issuecomment-269906067
