### ISSUE TITLE
Warn if both allow-top-navigation and allow-top-navigation-by-user-activation are specified

### ISSUE THREAD

**Issue by foolip** [validator/validator#470]
For changes in https://github.com/whatwg/html/pull/2292

**Comment by sideshowbarker** [comment]
Spec citation:
https://html.spec.whatwg.org/#the-iframe-element:attr-iframe-sandbox-allow-top-navigation-4

> The `allow-top-navigation` and `allow-top-navigation-by-user-activation` keywords must not both be specified, as doing so is redundant; only `allow-top-navigation` will have an effect in such non-conformant markup.

**Comment by sideshowbarker** [comment]
Note that because the language at  https://html.spec.whatwg.org/#the-iframe-element:attr-iframe-sandbox-allow-top-navigation-4 uses a “must”, I made the checker emit an error for this case, not a warning. If the intent was for the checker to only warn about this, then the spec language needs a “should” in place of that “must”.
