### ISSUE TITLE
Wrong Chinese variant detection for jdh8.org

### ISSUE THREAD

**Issue by jdh8** [validator/validator#473]
https://jdh8.org

This page is in Traditional Chinese and marked `lang=zh-Hant` but detected as Simplified Chinese.

This is my blog, written in Traditional Chinese, except that one article is in Simplified Chinese. That particular article is correctly labeled `lang=zh-Hans`. Despite of vast majority of Traditional-only characters, the detector insists that this page is in Simplified Chinese due to few Simplified-only characters.

**Comment by sideshowbarker** [comment]
Thanks much for taking time to report this. It’s a great real-world problem case, and made me realize that if a document has elements in the body with `lang` attributes that don’t match the `html[lang]` value, the language detector should just ignore the content of those elements—the rationale being that because the language detector’s purpose is to identify a document’s primary language, then any content a document has in another language should just be ignored as far as that purpose.

I’ve pushed a fix to https://validator.w3.org/nu/ and https://checker.html5.org/

Please check your documents again and if you notice any problems, let me know.
