### ISSUE TITLE
Getting lang=

### ISSUE THREAD

**Issue by benjamindally** [validator/validator#482]
The validator keeps saying I need to specify a language. However, most my pages don't have a language specified and validate fine. Just two say they need a language. Weird, right?

**Comment by sideshowbarker** [comment]
Yeah it’s confusing but the reason is, the checker only says you need to specify a language when it’s able to guess with some degree of certainty what the actual language of the document is.

If the text content of a document is less than some configured limit (I think I currently have it set to 1000 characters), then the checker doesn’t attempt to guess the language at all. The reason is that in practice it doesn’t do a super-great job at guessing the language of text shorter than that.

Another case where the checker has a hard time guessing the language is if the page contains content in multiple languages. In the case it ends up seeing that there’s are certain probability of it being in one particular language, and a certain probability of it being in another, and another, and so on. And if it is no particular language is detected with at least a 90% probability, then it gives up.

Hope that all gives you some insight into why you’re seeing the (admittedly confusing and apparently inconsistent) behavior that you’re seeing.

**Comment by benjamindally** [comment]
Thank you for the feedback! I'll look into it and see if I can figure it out.

Cheers,
Ben

**Comment by sideshowbarker** [comment]
Closing for now but feel free to comment further or re-open if you have suggestion for resolving further
