### ISSUE TITLE
Label for Progress element issue

### ISSUE THREAD

**Issue by AlanSmithey** [validator/validator#490]
Hello!

> ERROR - The `for` attribute of the `label` element must refer to a non-hidden form control.

This error occurs in this section of code:

`<label for='progress-bar'>Label</label>`
`<progress value='0.5' max='1' id='progress-bar'>50%</progress>`

But according to the **HTML** specification, `progress` element categorized as **labelable**, therefore it can  be associated with a `label` element.

What is the problem with this code and why is it considered not valid?
This is a bug, or a feature?)

Thank you!

**Comment by nschonni** [comment]
Although it is listed under form elements https://www.w3.org/TR/html5/forms.html#the-progress-element it does seem odd to label element that is directly interactive in a form.

**Comment by sideshowbarker** [comment]
Thanks for catching this and taking time to report it. It was a checker bug checker, because the [current spec](https://html.spec.whatwg.org/multipage/forms.html#category-label) defines `progress` as labelable (and `meter` too, which the checker had also been incorrectly not considering as labelable).

Fix pushed to https://checker.html5.org/ and https://validator.w3.org/nu/
