### ISSUE TITLE
Specifying a User-Agent?

### ISSUE THREAD

**Issue by jaimeiniesta** [validator/validator#51]
Is it possible to specify a different User-Agent string per request? I've seen this can be set [on the build](https://github.com/validator/validator/blob/master/build/build.py#L1091), but can it be changed on runtime, like on the W3C legacy validator accepts a `user-agent` param?

This can help when validating web pages that respond with different contents depending on the User-Agent string, I've seen cases where the web developers were confused about getting issues related to content that they did not see when browsing the page, and thought there was some kind of cache.

For example, this is a [validation of a page](http://validator.w3.org/check?uri=http%3A%2F%2Fvalidationhell.com%2Fpages%2Fagent&charset=%28detect+automatically%29&doctype=Inline&ss=1&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices) and this is the [same validation with a browser-like User-Agent](http://validator.w3.org/check?uri=http%3A%2F%2Fvalidationhell.com%2Fpages%2Fagent&charset=%28detect+automatically%29&doctype=Inline&ss=1&group=0&user-agent=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_8_5)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/29.0.1547.76%20Safari/537.36).

**Comment by sideshowbarker** [comment]
This is a good idea.

There's nothing yet exposed by the vnu code that’d enable it but as far as I can see it’d be feasible to add it as a new input param https://wiki.whatwg.org/wiki/Validator.nu_Common_Input_Parameters

If we add support in the code I think I'd still be reluctant myself to expose anything for it in the http://validator.w3.org/nu/ UI—just because it adds complexity to the UI for a feature that the vast majority of users don't need. Of course any user could still add it manually to the query part of the request URL, though they'd have to escape it correctly.

Still it'd be there regardless for any consumers of the checker’s HTTP/REST/Web-services API.

**Comment by jaimeiniesta** [comment]
Cool, I also think that it would be better to not clutter the UI with a new input as most users are not going to use it, but it would be great to be able to pass it as a query parameter.

**Comment by sideshowbarker** [comment]
OK. BTW the docs at http://validator.w3.org/docs/users.html#option-user-agent imply there's an option fo this provided in the Web UI but I notice that http://validator.w3.org/ doesn't actually seem to expose such an option in its UI. Is that true? Or am I missing something? I realize it's supported in the backend—just wondering what mechanism if any there is for it, other than just adding it to the URL manually.

**Comment by jaimeiniesta** [comment]
I don't remember seeing an input for it on the UI. All that there is now is a hidden input used to remember its setting, for the Revalidate form.

**Comment by jaimeiniesta** [comment]
Thanks, I've added the option to specify a User-Agent string to [nunchaku 0.2.0](https://github.com/sitevalidator/nunchaku#specifying-a-custom-user-agent-string).
