### ISSUE TITLE
Handling of <a href="..."> inside <text> / <tspan> in inline-SVGs

### ISSUE THREAD

**Issue by s-m-e** [validator/validator#511]
Assume an HTML-document of the following shape:

```
<!DOCTYPE html>
<html><head><title>title</title></head><body>
<svg xmlns="http://www.w3.org/2000/svg">
<text><tspan><a href="http://www.google.com">some link</a></tspan></text>
</svg>
</body></html>
```

VNU 17.3.0 reports

```
"test.htm":4.14-4.45: error: Attribute “href” not allowed on element “a” at this point.
"test.htm":4.14-4.45: error: Element “a” is missing required attribute “href”.
```

This behavior is irritating. The "href"-attribute is allowed in the [SVG2-specification](https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs) and supersedes the deprecated "xlink:href" attribute. The XML-namespace "http://www.w3.org/2000/svg" should allow SVG2 syntax. Not sure whether this is a bug or a mistake on my side.

**Comment by AmeliaBR** [comment]
Was just about to report this myself.  There are really two issues here:

- The un-namespaced `href` should now be allowed on any SVG element that accepts `xlink:href`.

- If the Validator is going to report that a required attribute with a namespace is missing, the error message needs to actually specify the namespace!

PS, to @s-m-e: your code is valid in SVG 2, but using `xlink:href` would have better browser support.

**Comment by frivoal** [comment]
cc @sideshowbarker 

This bug is getting in the way of publishing specifications at W3C using [echidna](https://github.com/w3c/echidna), since [bikeshed](https://tabatkins.github.io/bikeshed/) generates svg diagrams that uses `<a href="..."` instead of `<a xlink:href="..."` in the specifications. 

https://validator.w3.org/nu rejects that, so echidna [rejects my spec](https://labs.w3.org/echidna/api/status?id=0773791d-2127-423f-95a9-f98d3f1c0e77), and I cannot publish, which makes me a sad panda.

As @AmeliaBR said, it would be better if bikeshed generated `<a xlink:href="..."`, but fixing that may be [non trivial](https://github.com/html5lib/html5lib-python/issues/59).

So it would be really nice if this was fixed.
