### ISSUE TITLE
errorenous 401 error for .htpasswd protected page

### ISSUE THREAD

**Issue by leserman** [validator/validator#538]
I get a 401 error when I try to validate a page with .htpasswd protection. It does work properly if I select the "check error pages" Option. Such access was working properly as of a few weeks ago.

Thank you for maintaining this validator.

**Comment by sideshowbarker** [comment]
Validating pages that are require authentication has never worked when you use the https://validator.w3.org/nu/ frontend to make the request. That’s intentional, because enabling it would require you exposing your password to me to do whatever I want with.

I think it does work if you use the https://validator.w3.org/ frontend (because it was added as a feature there many years ago and I guess it’s removing it now would generate too many complaints from people who’ve grown accustomed to having).

But I think if you use it there it will only work if you have a non-HTML5 doctype on your document; that is, if you use an HTML4 or XHTML1 doctype.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/538#issuecomment-322033005 but feel free to comment here if you have further questions or information to add
