### ISSUE TITLE
Outline not shown for URL

### ISSUE THREAD

**Issue by nekromoff** [validator/validator#539]
URL of a page with multiple (different level) headings
[https://www.mosysolutions.com/every-car-might-be-stolen/](https://www.mosysolutions.com/every-car-might-be-stolen/)

W3C Validator  not showing an outline, when checked:

https://validator.w3.org/nu/?showoutline=yes&acceptlanguage=&doc=https%3A%2F%2Fwww.mosysolutions.com%2Fevery-car-might-be-stolen%2F

**Comment by sideshowbarker** [comment]
The problem here is that there’s a _“Start tag body seen but an element of the same type was already open.”_ problem in the document that causes a _“Cannot recover after last error. Any further errors will be ignored”_ fatal error before checking of the document can complete. So the checker never reaches the step of generating the outline.

The solution is to fix the error that’s causing that _“Start tag body seen but an element of the same type was already open.”_ to occur. The root cause of that seems to be that the document has an `iframe` element in the `head`, which isn’t allowed. Move that `iframe` to within the `body`.
