### ISSUE TITLE
Microdata inside option/select elements

### ISSUE THREAD

**Issue by Malvoz** [validator/validator#542]
It is currently not valid to wrap the **option** element with **div/span** elements to convey microdata.
Also using the **link/meta** element to provide additional information inside option element is not valid.

As an example:

&lt;html  itemscope itemtype="https://schema.org/WebSite"&gt;
...
**&lt;select itemprop="potentialAction" itemscope itemtype="https://schema.org/ChooseAction"&gt;
&nbsp;&nbsp;&nbsp;&lt;option itemprop="actionOption" itemscope itemtype="https://schema.org/WebPage"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;link href="https://example.com/en-gb" hreflang="en-GB" itemprop="url"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div itemprop="inLanguage" content="en-GB"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;United Kingdom
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&lt;/option&gt;
&lt;/select&gt;**
...
&lt;/html&gt;

Will result in:
1. Error: Stray start tag link.
2. Error: Stray start tag div.
3. Error: Stray end tag div.

**Comment by unor** [comment]
As the validator seems to be correct here (because `option` can’t contain any element, and `select` can only contain `option`/`optgroup`/`script`/`template`), are you proposing to change the HTML spec to allow it? If yes, this project here wouldn’t be the right place. 

Instead, you might want to head to https://github.com/whatwg/html and/or http://github.com/w3c/html/ (or, I guess, to http://github.com/w3c/microdata/ if it should only be allowed for use with Microdata).

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/542#issuecomment-318962378 but feel free to comment here if any further clarification is needed
