### ISSUE TITLE
Change validation Warning: The button role is unnecessary for element button.

### ISSUE THREAD

**Issue by squalrus** [validator/validator#549]
Regarding the warning: "The button role is unnecessary for element button." the Submit role is the default state per "The missing value default is the Submit Button state." from https://www.w3.org/wiki/HTML/Elements/button#HTML_Attributes 

Update the warning to check for `role="submit"` with updated messaging: "The submit role is unnecessary for element button."

**Comment by LeeKowalkowski** [comment]
There is no `role="submit"` (see https://www.w3.org/TR/wai-aria/roles).  

I think you meant because `<button role="button">` is a warning, `<button type="submit">` should also.

It is not harmful to set an attribute to its default value, however, in [Aria in HTML](http://w3c.github.io/html-aria/#rules-wd), HTML authors are told they should not do it:

> Web developers should not set the ARIA role and aria-* attributes to values that match the implicit ARIA semantics defined in [the table](http://w3c.github.io/html-aria/#docconformance).

**Comment by squalrus** [comment]
You are totally right. I had myself confused while reading the validation, reading "role" but thinking "type". Thanks!
