### ISSUE TITLE
Validator not checking custom data attributes?

### ISSUE THREAD

**Issue by martindholmes** [validator/validator#558]
The HTML spec says "A custom data attribute is an attribute in no namespace whose name starts with the string "data-", has at least one character after the hyphen, is XML-compatible, and contains no ASCII upper alphas."

https://html.spec.whatwg.org/multipage/dom.html#attr-data-*

The validator does not seem to check conformance here; it does not raise an error for an attribute named (for instance) `data-myOwnAttribute`.

**Comment by sideshowbarker** [comment]
Just below the sentence you cite from the spec, there’s a note:

> All attribute names on HTML elements in HTML documents get ASCII-lowercased automatically, so the restriction on ASCII uppercase letters doesn't affect such documents.

So the parser used by the checker (validator) lowercases attributes before the checker code itself is ever reached, and so the checker code just sees that attribute name as `data-myownattribute`.

And like and such requirements in the spec, that requirement applies to the post-parsed (DOM) state of an HTML document. In fact, as far as the spec goes that’s what “HTML document” means—it means the product of having run some kind of source through an HTML parser. It does not mean whatever per-parsed serialized source which a parser created an HTML document from.

So, that “contains no ASCII upper alphas” spec requirement isn’t machine testable. Not every document-conformance requirement the spec states is necessarily intended to be machine-testable. This case is one that’s not.

The only way that could become machine testable would be if the section of the spec that states requirement for HTML parsing were to add a requirement the parsers report an error for any `data-*` attributes that contain ASCII upper alphas.

**Comment by martindholmes** [comment]
That makes perfect sense. We hit a problem where Chrome's inspector was showing a camel-cased version of the attribute name in its document tree, but when we queried for it in JavaScript at the console, it would lower-case the query and fail to find it. If I understand correctly, that's a bug in the Chrome parser, since the attribute name should have been lower-cased at parse time, and the JS query should have found it by matching lower-case to lower-case.

**Comment by sideshowbarker** [comment]
> We hit a problem where Chrome's inspector was showing a camel-cased version of the attribute name in its document tree

The only way I can imagine that being possible would be if the DOM were constructed by an XML parser instead of HTML parser.

By the way, that reminds me: I need to qualify my previous comments to note that everything I wrote applies only to HTML documents parsed as text/html. In documents parsed as XML all attributes are case sensitive so can end up with `data-myOwnAttribute` attribute post-parsing.

However, the checker code actually already reports an error if it finds ASCII upper alphas in a `data-*`-attribute name:

https://github.com/validator/validator/blob/master/src/nu/validator/xml/dataattributes/DataAttributeDroppingContentHandlerWrapper.java#L216

But in order for a document to cause the checker to report that error, the document needs to be delivered with an `application/xhtml+xml` media type, or some other XML media type.

> If I understand correctly, that's a bug in the Chrome parser, since the attribute name should have been lower-cased at parse time, and the JS query should have found it by matching lower-case to lower-case.

I think it’s almost certainly not a bug in the Chrome parser but instead what you were seeing in the Chrome inspector was DOM constructed from an XML parser instead of an HTML (text/html) parser.

**Comment by martindholmes** [comment]
You're absolutely right: these are XHTML5 documents. We always use XHTML because it's more easily processable (XQuery, XSLT etc.). I was running vnu.jar against a local copy of the file, though, which means that it would not have had the XML media type, and so would presumably have defaulted to HTML and not reported the error.

**Comment by sideshowbarker** [comment]
> I was running vnu.jar against a local copy of the file, though, which means that it would not have had the XML media type, and so would presumably have defaulted to HTML and not reported the error.

If you give the vnu.jar checker a file with a `.xhtml` extension, it will parse the file with the XML parser instead of the HTML parser.
