### ISSUE TITLE
Publish Docker Image with Standalone Web Server on Docker Hub

### ISSUE THREAD

**Issue by phauer** [validator/validator#573]
Hi,
I really love to execute vnu as a standalone web server in order to validate my sites locally. So I don't have to upload them. 
Have you consider to create a Docker image and publish it on Docker Hub? This would make the usage much easier. 

The Dockerfile would be straightforward:

```Dockerfile
FROM java:8u111-jre-alpine
ADD vnu_17.11.1.jar /vnu.jar
CMD ["java", "-cp", "/vnu.jar", "nu.validator.servlet.Main", "8888"]
```

Moreover, it would fit perfectly into dockerized setups that uses docker-compose:

```yml
version: '2'
services:
  nu_validator:
    image: vnu:17.11.1
    ports:
      - "8888:8888"
    network_mode: "host" #so "localhost" refers to the host machine.
```

Cheers, Philipp

**Comment by jaimeiniesta** [comment]
Hello @phauer, I maintain this one:

https://github.com/sitevalidator/nu-cat

**Comment by sideshowbarker** [comment]
> Have you consider to create a Docker image and publish it on Docker Hub?

I have no plans to do that myself, but there’s nothing preventing somebody else from publishing an image at Docker Hub. If @jaimeiniesta’s image is not there already, it seems like anybody could take it publish it there themselves.

**Comment by phauer** [comment]
Thanks for your answers. 
@sideshowbarker, you are right. Creating the docker image is no big deal.
@jaimeiniesta, I really appreciate your docker image! Thanks! However, I have the following considerations:
If the creation and publishing of the Docker Image would be done within this project, it could be integrated into the travis release build. So there would be always the latest version on DockerHub and we don't have to rely on other kind folks that are manually maintaining and updating their image.

However, I'm not familiar with travis and the release workflow on GitHub, but after uploading the latest artifact on GitHub the Dockerfile could look like this:

```Dockerfile
FROM java:8u111-jre-alpine
RUN apk --no-cache add curl
RUN curl -o 'vnu.zip' 'https://github.com/validator/validator/releases/download/17.11.1/vnu.jar_17.11.1.zip' --location
RUN mkdir /vnu
RUN unzip vnu.zip -d /vnu
RUN rm vnu.zip
CMD ["java", "-cp", "/vnu/dist/vnu.jar", "nu.validator.servlet.Main", "8888"]
```

Just replace the `17.11.1` with the current version.

**Comment by sideshowbarker** [comment]
For the record here and to close the loop on this issue: A Dockerfile for the checker has been published at https://hub.docker.com/r/validator/validator/ and gets updated each time anything is pushed to the master branch here. To create that Dockerfile, I just borrowed from the example in https://github.com/validator/validator/issues/573#issuecomment-344926128 and also from the nu-cat Dockerfile at https://hub.docker.com/r/sitevalidator/nu-cat/~/dockerfile/

But I’m happy to make any further changes to that https://hub.docker.com/r/validator/validator/ Dockerfile. So if there are specific suggestions, please comment here to let me know — or else raise new issues or just create a PR with any suggested changes.

**Comment by phauer** [comment]
Hi @sideshowbarker,
the docker image looks pretty good! I just tested it. Thank you very much!

**Comment by phauer** [comment]
Hi @sideshowbarker,
the docker image looks pretty good! I just tested it. Thank you very much!
Just some random thoughts:

The README should at least mention the Docker image and contain a quick getting started section. Like

`docker run -p "8888:8888" validator/validator:latest`
or
```yaml
version: '2'
services:
  nu_validator:
    image: validator/validator
    ports:
      - "8888:8888"
    network_mode: "host" #so "localhost" refers to the host machine.
```

Especially the network_mode is relevant if you want to run the validator against a website running on localhost. 

On Docker Hub, I see a "latest" image. Do you plan to add a new tag for each release? This way, users can pin a fixed version. Sometimes you don't to automatically get the latest version (reproducibility).

But that are just minor points. Again, thank you!

**Comment by jaimeiniesta** [comment]
Thanks for publishing an official Dockerfile @sideshowbarker !

I've tried it and works fine, so I think I'll deprecate mine now, but first I'd like to understand the differences:

* In your version, you don't use Tomcat. Which is great, the less pieces the better, but do we lose anything? Like, maybe Tomcat does some monitoring and restarts the checker if it crashes? I don't know anything about Tomcat, just wondering if there's any benefit on having it or not.
* The faster SecureRandom is therefore unneeded because we don't need to make Tomcat boot up faster now.
* In my image I tweaked timeouts to 10 seconds on catalina properties, how would we do that using your image?

As @phauer said, it would help to simplify the README with instructions specific to setting up docker, and also have release tags. By the way, the version in master is 18.2.7 but the latest release is 17.11.1, is there going to be a release soon?

Thanks!

**Comment by sideshowbarker** [comment]
> The README should at least mention the Docker image and contain a quick getting started section.

OK, thanks, I added some details. See the first paragraph of https://validator.github.io/validator/ and https://github.com/validator/validator/#the-nu-html-checker-vnu--  and https://hub.docker.com/r/validator/validator/. The text there mentions/links to a new **Pulling from Docker Hub** which is toward the end of the README:

https://github.com/validator/validator#pulling-from-docker-hub

The content of that **Pulling from Docker Hub** section mentions both how to pull the latest version or a tagged version, and it includes an example Compose file based on the one in https://github.com/validator/validator/issues/573#issuecomment-364644614.

> On Docker Hub, I see a "latest" image. Do you plan to add a new tag for each release?

Yes, based on your feedback, I’ve now added [an additional Dockerfile](https://github.com/validator/validator/blob/master/build/Dockerfile.tagged) to the github repo, for internal use in pushing a tag to Docker Hub for each official release.

Thanks much for the help and suggestions so far

**Comment by sideshowbarker** [comment]
> I think I'll deprecate mine now

I think yours is still useful for people who might prefer to use Tomcat rather than the embedded Jetty.

> * In your version, you don't use Tomcat. Which is great, the less pieces the better, but do we lose anything? Like, maybe Tomcat does some monitoring and restarts the checker if it crashes? I don't know anything about Tomcat, just wondering if there's any benefit on having it or not.

I also don’t know much about Tomcat (nor Jetty for that matter), so I’m not sure what might be lost by using the embedded Jetty version rather than Tomcat. But having the Tomcat-base Dockerfile remain available seems useful for people who do prefer it for whatever reason.

> In my image I tweaked timeouts to 10 seconds on catalina properties, how would we do that using your image?

As far as I understand it, I guess maybe we could provide a way for users to do that at runtime with my image by taking environment variables set with the `--env` argument to `docker run` and based on the values of those, passing some system properties to the `java` call  that starts the checker.

The relevant system properties are documented at:

* https://github.com/validator/validator/#nuvalidatorservletconnection-timeout
  `-Dnu.validator.servlet.connection-timeout=5000`
* https://github.com/validator/validator/#nuvalidatorservletsocket-timeout
  `-Dnu.validator.servlet.socket-timeout=5000`

Of course another way would be to just hardcode those system properties (with 10000 instead, for 10 seconds) into the Dockerfile itself.

> As @phauer said, it would help to simplify the README

As far as I can see, as long as I’m using the Docker Hub “automated build” option, I can’t publish a different README at Docker Hub than the one that’s in the github repo — because the Docker Hub build just picks up the latest version of the README in the githbub repo.

Of course an alternative would be to just put the Dockerfile into a separate github repo with its own README — or at least a separate branch. But I have been hoping to avoid needing to do that.

> with instructions specific to setting up docker, and also have release tags

The change I made in 0d49a43 is my best attempt at incorporating the Docker Hub/Dockerfile info into the existing README in a way that will get the attention of readers and lead them to the right details (in the new **Pulling from Docker Hub**  section). 

I hope that’s enough but if you think there are ways I could improve it further, I welcome suggestions.

> By the way, the version in master is 18.2.7 but the latest release is 17.11.1, is there going to be a release soon?

I’ve been holding off doing a new release until we get the (now-embedded) CSS-checking backend improved a bit further — specifically, until the CSS backend has support for checking CSS variables (instead of the parser choking on them, as it does now) and support for checking the `@supports` at-rule (which the parser also chokes on currently).

But it’s looking like it might take a bit longer to get CSS-variables checking and `@supports` checking added to the CSS backend, so I guess I might do a release sometime soon without them.

**Comment by phauer** [comment]
That looks really nice! Good job!

**Comment by jaimeiniesta** [comment]
Thanks a lot!

> As far as I understand it, I guess maybe we could provide a way for users to do that at runtime with my image by taking environment variables set with the --env argument to docker run and based on the values of those, passing some system properties to the java call that starts the checker.

That would be the cleanest solution I think, instead of hardcoding the values in the Dockerfile, let's take them from the `--env` argument to `docker run`.

**Comment by sideshowbarker** [comment]
> instead of hardcoding the values in the Dockerfile, let's take them from the `--env` argument to `docker run`

OK, I just now pushed 63f64e6, which adds support for changing the timeouts using environment variables named `CONNECTION_TIMEOUT_SECONDS` and `SOCKET_TIMEOUT_SECONDS`.

**Comment by sideshowbarker** [comment]
Seems like we have everything resolved for this issue at this time, so I’m now gonna go ahead and close it. Thanks again much and if any other problems come up going forward, please file new separate issues.
