### ISSUE TITLE
iFrame validation error

### ISSUE THREAD

**Issue by richardrv** [validator/validator#592]
This code is returning a validation error:
         <iframe src="TriviaSchedule.html" width="460" height="792">
            <p>Your browser cannot display the schedule.</p>
         </iframe>    

My reading of w3schools suggests the paragraph between the iFrame tags is valid:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe

Here's the error:
Error: Text not allowed in element iframe in this context.
From line 29, column 13; to line 29, column 14
          <p>Your 
Content model for element iframe:
    Text that conforms to the requirements given in the prose. 

Am I missing something (obvious)?

**Comment by cvrebert** [comment]
https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element

> 4.8.5 The `iframe` element
> [...]
> Content model: Nothing.

https://html.spec.whatwg.org/multipage/dom.html#concept-content-nothing

> When an element's content model is **nothing**, the element must contain no Text nodes (other than inter-element whitespace) and no element nodes.

In other words, w3schools is wrong yet again; film at 11.

**Comment by richardrv** [comment]
Thanks Chris.

 

Richard Harvey
Home: 416-699-4245

**Comment by sideshowbarker** [comment]
Closing per reason noted in https://github.com/validator/validator/issues/592#issuecomment-355858686

@richardrv w3schools is full of wrong information, and the site maintainers do very little to keep the information up to date with the current spec, nor do they fix known problems in a timely fashion when the problems are reported to them.

You’re pretty much always better off consulting MDN https://developer.mozilla.org/en-US/ and ignoring w3schools altogether — because in contrast, MDN is very actively kept up to date, and any problems there generally get fixed very quickly.

**Comment by dmtucker** [comment]
Related: https://github.com/validator/validator/issues/403
