### ISSUE TITLE
Mistake in validation on month strings in <time>

### ISSUE THREAD

**Issue by edent** [validator/validator#600]
The validator *only* accepts years >= 1000.

Consider the 1st of January in the year 1.
`<time>0001-01-01</time>`
Gives the error
> Warning: The text content of element time was not in the required format: Year may be mistyped.

The spec says
> A string is a valid month string representing a year *year* and month *month* if it consists of the following components in the given order:
> Four or more ASCII digits, representing year, where year > 0
> https://www.w3.org/TR/2017/REC-html52-20171214/infrastructure.html#valid-month-string

Example 19 on that page says that the string `0033-03-03` is valid - but the validator fails it.

The validator should recognise that years < 1000 are also valid.

We're also discussing whether it should recognise the year `0000`. See https://github.com/w3c/html/issues/1141

**Comment by sideshowbarker** [comment]
> The validator *only* accepts years >= 1000.

That’s not correct. It allows any year greater than 0 without emitting any error.

If it only accepted years >= 1000, it would emit an error for years less than 1000.

> Consider the 1st of January in the year 1.
> `<time>0001-01-01</time>`
> Gives the error
> > Warning: The text content of element time was not in the required format: Year may be mistyped.

That’s not an error. It’s a warning. It also warns for years greater than 3000. And that warning’s not there by mistake — I added it intentionally in e55cfdc to help authors/developers catch the cases where they might have mistyped a date.

> Example 19 on that page says that the string `0033-03-03` is valid - but the validator fails it.

The validator doesn’t fail it. If it were to fail it, the message wouldn’t be a warning — it’d be an error.

> The validator should recognise that years < 1000 are also valid.

That validator already does recognize those as valid. That’s why it doesn’t flag them as errors.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. After looking at it a bit more carefully, I realize the problem here is that the language of the warning message is wrong. The backend code was just re-using the exact same text as what gets emitted for the error case, but slapping a *Warning:* prefix on it instead.

So in 387754c I changed the language for the warning case such that it’ll instead report this:

> Warning: Double-check the text content of element `time`: Year may be mistyped.

**Comment by edent** [comment]
Ah! Sorry for my confusion between errors and warnings. I agree, the new wording is better.

**Comment by sideshowbarker** [comment]
I’m gonna go ahead and close this now since I pushed the change for it to the W3C checker:

https://validator.w3.org/nu/?doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%2C%3C%21doctype+html%3E%3Ctitle%3Etest%3C%2Ftitle%3E%3Ctime%3E0001-01-01%3C%2Ftime%3E

Thanks again for raising the issue. I think there are probably still other cases where some of the warning messages are incorrect in the way this one was — so please do report others if/when you run into any.
