### ISSUE TITLE
Consider migrating away from commons-httpclient

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#61]
[The project has been end-of-life-ed.](http://hc.apache.org/httpclient-3.x/) Its successor is the [Apache HttpComponents](http://hc.apache.org) project's `HttpClient`, although I have no idea whether or not that's the most preferable library in today's Java ecosystem.

**Comment by sideshowbarker** [comment]
So yeah we need to migrate to something new anyway—to get SNI support, because commons-httpclient doesn’t set SNI.

> Its successor is the Apache HttpComponents project's HttpClient, although I have no idea whether or not that's the most preferable library in today's Java ecosystem

Given that we have to migrate to something new regardless, and change or code to write to some new API regardless, it might make sense to try some non-Apache-project thing, if there’s something that stands out as being better. But a quick look around doesn’t seem to indicate that there is any, so I reckon we should just go ahead and migrate to HttpComponents. But I’ll do a little more investigation before doing that. And anyway we definitely want @hsivonen to weigh in on this.

**Comment by sideshowbarker** [comment]
I found a couple of commons-httpclient⇒HttpComponents HttpClient migration guides:

http://blog.teamextension.com/migrating-from-httpclient-3-1-to-4-0-34
http://debuguide.blogspot.jp/2013/01/quick-guide-for-migration-of-commons.html

It looks like it would take at least a couple hours to migrate the validator sources and test them, so I’d be glad if somebody wanted to contribute a patch for this. Otherwise it’s not likely I’ll get around to until this weekend at the earliest.

**Comment by sideshowbarker** [comment]
I pushed out a nightly with the change included—https://sideshowbarker.net/nightlies/vnu.jar
