### ISSUE TITLE
'npm update' installs newer ('dev'-tagged) version rather than keeping 'latest'-tagged version 

### ISSUE THREAD

**Issue by nickserv** [validator/validator#610]
Based on the npm versions available, it would appear that 17.12.28 should be the latest version tag because it's the most recent 17.x release. However, the latest release is 17.11.1. I'm not sure if this was intentional or if someone accidentally used the wrong dist tags when publishing to npm. Oddly enough `npm install vnu-jar` will give me 17.11.1, while `npm update` after that will update it to 17.12.28.

```
$ npm view vnu-jar dist-tags
{ latest: '17.11.1', dev: '18.2.13' }
$ npm view vnu-jar versions
 
[ '16.6.29',
  '16.11.19',
  '16.12.25',
  '16.12.27',
  '17.0.0',
  '17.0.1',
  '17.1.0',
  '17.1.8',
  '17.1.31',
  '17.1.32',
  '17.1.33',
  '17.1.34',
  '17.2.0',
  '17.2.1',
  '17.2.13',
  '17.2.23',
  '17.3.0',
  '17.4.14',
  '17.4.17',
  '17.5.7',
  '17.5.20',
  '17.7.0',
  '17.7.4',
  '17.7.6',
  '17.7.8',
  '17.8.18',
  '17.8.20',
  '17.8.28',
  '17.9.0',
  '17.9.10',
  '17.9.13',
  '17.10.1',
  '17.10.4',
  '17.11.0',
  '17.11.1',
  '17.12.5',
  '17.12.7',
  '17.12.14',
  '17.12.15',
  '17.12.26',
  '17.12.28',
  '18.1.18',
  '18.1.30',
  '18.2.2',
  '18.2.4',
  '18.2.5',
  '18.2.13' ]

````

**Comment by sideshowbarker** [comment]
The `17.12.28` tag is a dev tag. It doesn’t correspond to an official release but instead just to a nightly build. The `latest` value only gets changed for every official release, and there’s not been any official release since the `17.11.1` release.

As far as the `npm update` behavior you describe, I personally wouldn’t expect it to update you to dev tag without asking; instead I’d expect that it only updates you to a non-`latest` tag if you explicitly specify that’s what you want. But it sounds like maybe it does something other than that — and if so, I guess that’s how `npm update` is intended to work.

So I’m not sure what to suggest other than, don’t run `npm update` if you don’t want to get updated to something other than `latest`. And if instead of `latest` you do actually want the most up-to-date package version, then just explicitly install `dev`.

**Comment by nickmccurdy** [comment]
I see, I wasn't sure if the recent 17.x releases were in dev. But I'm still not totally sured if this is an npm issue or something with this package's tagging that could be improved.

**Comment by nickmccurdy** [comment]
I'm not sure why 17.12.28 is wanted here:

```
~/Repos/nickmccurdy.github.io $ npm i vnu-jar
+ vnu-jar@17.11.1
added 1 package in 2.317s
~/Repos/nickmccurdy.github.io $ npm outdated
Package  Current    Wanted   Latest  Location
vnu-jar  17.11.1  17.12.28  17.11.1
```

**Comment by sideshowbarker** [comment]
> But I'm still not totally sure if this is an npm issue or something with this package's tagging that could be improved

Yeah me neither.

> I'm not sure why 17.12.28 is wanted here:

```
$ npm i vnu-jar
+ vnu-jar@17.11.1
added 1 package in 2.317s
$ npm outdated
Package  Current    Wanted   Latest  Location
vnu-jar  17.11.1  17.12.28  17.11.1
```
I’m not sure either. But if it’s possible for me to tag (force) it in a way which results in the value of the `Wanted` field always being the same as the `Current`/`Latest` field, then that seems like what I should do. At this point I don’t know how to make it do that; I’ll make some time to investigate.

But if `npm outdated` (and `npm update` by way of `npm outdated` I guess) automatically calculates that `Wanted` value with no way for packagers to override it, that seems like an unfortunate misfeature.

**Comment by Arttse** [comment]
@nickmccurdy see NPM docs https://docs.npmjs.com/cli/outdated
> **wanted** is the maximum version of the package that satisfies the semver range specified in **package.json**. If there's no available semver range (i.e. you're running npm outdated --global, or the package isn't included in package.json), then **wanted** shows the currently-installed version.

When using `npm install` by default it installs package (with semver range) from the `latest` tag. For example, in this case, it's `^17.11.1`. Symbol `^` means «*include everything greater than a particular version in the same major range*». For `vnu-jar` in this range, the maximum version is `17.12.28`. This version is displayed in the column **Wanted**, but it will not be installed because it is not in the `latest` tag, it's in the `dev` tag. If you want to install this version, you must use `npm install vnu-jar@17.12.28` or use `dev` tag (`npm install vnu-jar@dev`) for most recent `dev` version.

See also https://docs.npmjs.com/getting-started/semantic-versioning and you will understand why this is so. You may need read https://semver.org

Also, try playing with [npm semver calculator](https://semver.npmjs.com) for clarity. Pick the `vnu-jar` package and enter the range `^17.11.1`.

**Comment by sideshowbarker** [comment]
Given https://github.com/validator/validator/issues/610#issuecomment-366757528, please lemme know if there’s something more you think we could do to address this.

**Comment by sideshowbarker** [comment]
Closing this out per https://github.com/validator/validator/issues/610#issuecomment-366757528 but feel free to comment here further (and we can re-open this if needed)
