### ISSUE TITLE
Allow role=rowgroup to be contained in role=table

### ISSUE THREAD

**Issue by mraccess77** [validator/validator#612]
When I use a role of row under a role of table the checker indicates that role of row is only allowed as child of grid, treegrid, and rowgroup.  Also placing role of columnheadr on td under a TR element does not recognize a TR as a implied role of row.

**Comment by sideshowbarker** [comment]
> When I use a role of row under a role of table the checker indicates that role of row is only allowed as child of grid, treegrid, and rowgroup.

Thanks for catching and reporting that. I’ve fixed in the checker sources and pushed the fix to https://validator.w3.org/nu/

**Comment by sideshowbarker** [comment]
> Also placing role of columnheadr on td under a TR element does not recognize a TR as a implied role of row.

I don’t know what that means. But if there’s a particular markup case for which you believe the checker isn’t behaving correctly, then please file a new separate issue and include:

1. An HTML markup sample for the case you believe the checker doesn’t handle correctly.
2. A description of the expected behavior from the checker for that case.
3. A description of what the checker does or doesn’t do that’s different from the expected behavior.
4. A link to the document-conformance requirements in the ARIA in HTML spec that lead to the expected behavior you want from the checker for that case.
5. (If possible) A similar markup case for which the checker already exhibits the expected behavior (that is, for some other `role`+element combination).
