### ISSUE TITLE
500 Can't connect

### ISSUE THREAD

**Issue by drzraf** [validator/validator#615]
Checking [this site](https://www.l214.com/) I get the message "500 Can't connect to www.l 214.com:443".
First the message lacks a description (timeout, DNS resolution, SSL certificate validation, ...)?
But secondly, I can't understand why the validator wouldn't connect to this site.

**Comment by sideshowbarker** [comment]
I don’t get a “500 Can't connect”—

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.l214.com%2F

> First the message lacks a description (timeout, DNS resolution, SSL certificate validation, ...)?

I think the `500` in the error message you got is the HTTP response code the https://www.l214.com/ server sent back to the request it got from the checker at the time. That is, the request the checker sent to https://www.l214.com/ triggered some internal server error in the https://www.l214.com/ server, which then therefore responded to the checker with a 500 response. So the checker told you, “Can't connect” (because the checker got a 500 error response from that server, instead of 200 success).

**Comment by drzraf** [comment]
At the time it was tried, the website was responding to browsers from various places in and outside Europe.

**Comment by sideshowbarker** [comment]
So is https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.l214.com%2F working for you now?

**Comment by drzraf** [comment]
yes, now, it does.
Thank you

**Comment by drzraf** [comment]
(still, having some precision about the cause of failure would help if it were to happen again)

**Comment by sideshowbarker** [comment]
> (still, having some precision about the cause of failure would help if it was to happen again)

Agreed. I’ll investigate some possible refinements. Thanks for taking time to report this

**Comment by tiflopin** [comment]
The problem is still occurring. Not with ths Nu Html Checker but with the Markup Validation Service : 
https://validator.w3.org/check?uri=https://www.l214.com/

The www.l214.com seems to be ok : https://www.sslshopper.com/ssl-checker.html#hostname=www.l214.com

**Comment by sideshowbarker** [comment]
> The problem is still occurring. Not with ths Nu Html Checker but with the Markup Validation Service :
https://validator.w3.org/check?uri=https://www.l214.com/

Interesting. I don’t know why the Markup Validation Service would be doing that, but I don’t actually work on the backend (Perl) code for that, so it’s not something I’m likely to be able to fix.

To get attention from others, it should be reported at https://github.com/w3c/markup-validator/issues

**Comment by tiflopin** [comment]
I reported the problem on the good project.
Thanks! @sideshowbarker
