### ISSUE TITLE
[Suggestion] w3-include-html attribute recognition

### ISSUE THREAD

**Issue by scoutchorton** [validator/validator#625]
This is a _suggestion_, not an _issue_.

In my website, I use the w3 include HTML script, but I think it would be nice if there could be something that would tell users that they should use iFrames as they are more modern. I will be switching soon, but I thought it might be a nice little feature.

It occurred in my code at a line with: `<div w3-include-html="../nav.html"></div>`. There could be something that says `Attribute "w3-include-html" should be replaced by using an "<iframe>" instead of "div".`

It's a small feature, and not many people would have it, but it would be useful for people like me who could switch over to XHTML. Hope it helps!

**Comment by sideshowbarker** [comment]
Thanks for taking time to suggest this, but as far as I can see, the `w3-include-html` attribute is only used by some JavaScript code from the W3Schools site. It’s basically a bad idea to be using code from that site — or even any information at all from that site, because it’s very poorly maintained.

So I don’t think there’s any good change at all we can make to the HTML checker to deal with this (well, other than having the checker emit a message saying, “It’s a bad idea to use code from the W3Schools site”).

Therefore, I’m gonna go ahead and close this for now, but please feel free to comment here further if you have other information to add
