### ISSUE TITLE
Error: CSS: Parse Error.

### ISSUE THREAD

**Issue by 2globalnomads** [validator/validator#632]
I am getting strange parse errors when checking this page:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.webseodesigners.com%2F

Could it be that there is too much CSS code embedded in the page causing a congestion?

**Comment by 2globalnomads** [comment]
It could have been too long lines in CSS. I prettyprinted the CSS and the error disappeared, and I haven't been able to repeat it.

**Comment by sideshowbarker** [comment]
I was able to reproduce it, but the message is caused by a server-side error in the https://www.webseodesigners.com/ backend — a PHP error, I think. And that results in an HTML document being sent to the validator with the following in its source:

```
<style>
[an error occurred while processing this directive]
.loadinganimation{position:fixed;display:block;…
```

That is, the `style` element contains a literal `[an error occurred while processing this directive]`.

So that causes the validator to emit a message saying there’s a CSS parse error — because that string `[an error occurred while processing this directive]` isn’t a valid CSS expression.

**Comment by 2globalnomads** [comment]
OK, my bad. Thanks for figuring that out. That's why the error vanished, after I got the SSI fixed.
