### ISSUE TITLE
W3C validators not getting correct referrer, possibly because of a tilde (~) in url

### ISSUE THREAD

**Issue by jamesrschmidt** [validator/validator#635]
The W3C validators for html and css are no longer recognizing the correct referrer url from my website (they used to). Possibly, this is because there is a tilde (~) in the url. In particular, (http://users.ugent.be/~jaschmid/) shows the validation for (http://users.ugent.be/) with the recommended code `<a href="http://validator.w3.org/check?uri=referer">` (html) and `<a href="http://jigsaw.w3.org/css-validator/check/referer">` (css). I am able to get the correct validation with `<a href="http://validator.w3.org/check?uri=users.ugent.be/~jaschmid/">` and `<a href="http://jigsaw.w3.org/css-validator/validator?uri=users.ugent.be/~jaschmid/">`, however.

**Comment by sideshowbarker** [comment]
As far as W3C-hosted services go, this issue tracker is the place to report problems only with the https://validator.w3.org/nu/ checker. But the problem described in this issue seems to be with other W3C-hosted services unrelated to https://validator.w3.org/nu/ — specifically, it seems, the W3C Link Checker and the W3C CSS Validator. Report problems with those at:

* https://github.com/w3c/link-checker/issues
* https://github.com/w3c/css-validator/issues

**Comment by mirabilos** [comment]
This still happens, the XHTML validator always validates the `/` page on the domain instead of the actual `/foo.htm` page.
