### ISSUE TITLE
a element with no href allowed any role, but reports errors for all

### ISSUE THREAD

**Issue by stevefaulkner** [validator/validator#638]
ARIA in HTML [allows the `a no href` element](https://w3c.github.io/html-aria/#anohref) to have a `role` attribute with any value, but it throws errors for many

[test cases](http://stevefaulkner.github.io/HTML5accessibility/tests/ARIA-tests/ARIAinHTML/a-nohref-testcases.html)

**Comment by sideshowbarker** [comment]
Making different role values allowed for the `a` element based on whether or not it has an `href` attribute adds additional complexity to the checker sources beyond what I’m willing to support.

So I’m marking this one _wontfix_.

If anybody cares enough about this to take the time to write up a patch to support, I’d be willing to review but still won’t guarantee I’d actually land it — because at this point I can’t imagine any actual use cases that are compelling enough to merit the additional complexity.
