### ISSUE TITLE
Bad value  for attribute type on element source

### ISSUE THREAD

**Issue by lcseguin** [validator/validator#662]
The validator show me this : 
![capture du 2018-06-06 12-13-39](https://user-images.githubusercontent.com/1129935/41032379-78196b2c-6983-11e8-88a8-c4d2afbf1c1f.png)

My source code 
`<source src="./video.ogv" type="video/ogg; codecs='theora, vorbis'">`

Validated with the inversion of **'** and **"** 
`<source src='./video.ogv' type='video/ogg; codecs="theora, vorbis"'>`

**Comment by sideshowbarker** [comment]
In RFC 5322 terms, the `codecs` parameter value there is a `quoted-string`, and so it must be surrounded by double quotes, not single quotes

See https://tools.ietf.org/html/rfc5322#section-3.2.4
>  Strings of characters that include characters other than those allowed in atoms can be represented in a quoted string format, where the characters are surrounded by quote (DQUOTE, ASCII value 34) characters.

So the validator is behaving as expected here; per RFC 5322 the following is not valid:
```html
<source src="./video.ogv" type="video/ogg; codecs='theora, vorbis'">
```
…because of the single quotes in the `codecs='theora, vorbis'` part.

But per RFC 5322, the following is valid:
```html
<source src='./video.ogv' type='video/ogg; codecs="theora, vorbis"'>
```
…because it has double quotes in the `codecs="theora, vorbis"` part.

And the following is also valid:
```html
<source src="./video.ogv" type="video/ogg; codecs=&quot;theora, vorbis&quot;">
```
…because the HTML parser resolves those `&quot;` character references to `"` characters.

**Comment by lcseguin** [comment]
The RFC must be changed to accept ASCII 34 or ASCII 39 ;-)
