### ISSUE TITLE
allow HTTPS in xmlns

### ISSUE THREAD

**Issue by roycewilliams** [validator/validator#692]
Is the URI scheme (`http` vs `https`) a hard requirement for xmlns checking? 
```
Error: Bad value https://www.w3.org/1999/xhtml for the attribute xmlns (only http://www.w3.org/1999/xhtml permitted here).

<html xmlns="https://www.w3.org/1999/xhtml" xml:lang="en">
```
If not, then the process of tracking down legacy non-HTTPS links in large corpora of documents could be simplified by simply allowing HTTPS in the xmlns.

**Comment by sideshowbarker** [comment]
The HTML namespace is literally `http://www.w3.org/1999/xhtml`. It’s a string that starts with `http://`, not `https://`. It is normatively defined that way. See https://infra.spec.whatwg.org/#html-namespace

So it’s an error to use `https://www.w3.org/1999/xhtml` instead. That would be a different namespace.

Similarly, the namespace URIs for MathML and SVG and XML start with `http://`.

Namespace URIs are simply identifiers. There’s no requirement that they actually resolve to anything — that is, if you open up a namespace URI in browser and it’s a 404 not found, then that’s fine.

So the fact that a particular namespace URI starts with `http://` rather than `https://` doesn’t matter. It’s not broken or somehow less usable, and is not bad practice.

**Comment by roycewilliams** [comment]
Fair points. My only concern was that since some naive implementations of "is non-https: being used on these pages" might treat the xmlns http: as a false positive. But probably not worth the trade-off. Closing; thanks for the explanation.

**Comment by sideshowbarker** [comment]
Cheers — thanks for taking time to raise an issue about it, so we have a record of it here

**Comment by waldyrious** [comment]
Cross-referencing a similar discussion, for further context: https://github.com/w3c/svgwg/issues/738.
