### ISSUE TITLE
Incorrectly Finding Duplicate attributes

### ISSUE THREAD

**Issue by wpexplorer** [validator/validator#726]
It appears that the validator is searching for id= when locating duplicate ID's but this causes issues if a data attribute ends with "id". Example in the screenshot below:

![screen shot 2018-11-06 at 11 36 05 am](https://user-images.githubusercontent.com/1128841/48089091-81a36000-e1b8-11e8-9bb2-59b000336d47.png)

This does seem to be a new issue as it wasn't happening in previous versions of the validator.

Thanks!

**Comment by sideshowbarker** [comment]
> It appears that the validator is searching for id= when locating duplicate ID's

It’s not.

> but this causes issues if a data attribute ends with "id". Example in the screenshot below:<br>
> …

That screenshot doesn’t show the error message the checker emits when it finds duplicate IDs. Instead it shows the error message the checker emits when it finds an element that has two attributes with exactly the same name.

In this specific case it seems the document has an element with two `data-ls_id` attributes.

If you check the document and find that’s not true, then please post the URL for the document, so that I can test it. Or else please post some markup snippet that reproduces the error.

**Comment by wpexplorer** [comment]
@sideshowbarker Apparently I am need some better glasses. You are correct ;) Sorry for the troubles!

**Comment by sideshowbarker** [comment]
> @sideshowbarker Apparently I am need some better glasses. You are correct ;) Sorry for the troubles!

No trouble :) Thanks for taking time to report it and please don’t hesitate to report any future issues you run into
