### ISSUE TITLE
Element “h1,h2,h3 ...” not allowed as child of element “legend”

### ISSUE THREAD

**Issue by borislavpetrovhmcts** [validator/validator#732]
Element "legend" can contain h1, h2, h3 ... according to https://www.w3.org/TR/html52/sec-forms.html#the-legend-element

Why was this functionality excluded from the validator few weeks ago ?
https://github.com/validator/validator/compare/18.11.5...master#diff-f6510381ab30f5043197f2d12d8108ccL281

It was implemented in the 17.0.1 release from 08 January 2017 :
"Allow h1-h6 & hgroup in legend"

**Comment by sideshowbarker** [comment]
> Element "legend" can contain h1, h2, h3 ... according to https://www.w3.org/TR/html52/sec-forms.html#the-legend-element

That spec no longer has any normative standing. The only HTML spec that’s normative now is https://html.spec.whatwg.org/. So the relevant section to look at in that is https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element — which say that the only allowed content for the `legend` element is phrasing content. And the h1-h6 heading elements are not phrasing content.

> Why was this functionality excluded from the validator few weeks ago ?
> [18.11.5...masterdiff-f6510381ab30f5043197f2d12d8108ccL281](https://github.com/validator/validator/compare/18.11.5...masterdiff-f6510381ab30f5043197f2d12d8108ccL281)

It changed I few weeks ago when I updated the checker to bring it into full conformance with the normative spec at https://html.spec.whatwg.org/. The normative HTML spec has always disallowed h1-h6 elements in the `legend` element.

> It was implemented in the 17.0.1 release from 08 January 2017 :
> "Allow h1-h6 & hgroup in legend"

That change was made because at that time, the requirement was for the checker to conform to the rules in the https://www.w3.org/TR/html52/ spec. But that’s no longer the case — instead the requirement now is for the checker to fully conform to the https://html.spec.whatwg.org/ spec.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/validator/validator/issues/732#issuecomment-441836562 but feel free to add further comments here if any more clarification is needed.
