### ISSUE TITLE
"Attribute name not allowed on element div at this point."

### ISSUE THREAD

**Issue by Bert-de-Jong** [validator/validator#748]
Regarding this error message:
"Attribute name not allowed on element div at this point."

On Stack Overflow, someone [answers](https://stackoverflow.com/a/4962083) that:
"The error message seems pretty self explanatory. You cannot have a name attribute on a div tag. So your code could look like this: [...]"

The "at this point" portion of the error message made it not self-explanatory to me. Is this true, is name never allowed with div. If so, maybe scrap the "at this point" bit?

**Comment by sideshowbarker** [comment]
The *"at this point"* part is an artifact of the backend using a validation mechanism based on generic grammar-based checking — specifically, RelaxNG.

That mechanism doesn’t lend itself to producing deterministic “attribute foo is never allowed on element bar” statements. Instead it essentially determines “in the context in which element foo is used in this document, it’s not allowed to have attribute bar”.

In other words, it’s not ruling out that there might be some other part of the grammar that might permit element foo to have attribute bar — in some other context (for example, if element foo has some other parent element, or certain other attributes).

Given that limitation that comes from relying on using a RelaxNG validator, you might wonder why the checker doesn’t use some other backend validation mechanism. The reason is that it comes down to tradeoffs. The costs of writing a validation backend completely from scratch to replace what we’re doing with the RelaxNG backend would be very large — and outside of the known limitations like the one reported in this issue, the benefits of the current RelaxNG backend are quite substantial.

**Comment by Bert-de-Jong** [comment]
Thanks for the explanation.
