### ISSUE TITLE
Checking "google.com" redirects me to Google

### ISSUE THREAD

**Issue by ghost** [validator/validator#753]
When I enter https://www.google.com/ at https://validator.w3.org/nu/ , the page is suddenly completely redirected to google.com.

The following link opens Google for me:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.google.com%2F

Does not happen with Bing or any other URL I've tried so far. Happens with Firefox, Chrome and Edge, 100% of the time, even when I disable all extensions.

**Comment by sideshowbarker** [comment]
Yeah this behavior is intentional.

To check the HTML source of google.com, use the IP address instead:

https://validator.w3.org/nu/?doc=http://172.217.31.132

**Comment by ToBeFree** [comment]
Oh! :)

Thanks.

**Comment by a3nm** [comment]
I was also affected by this today -- I find it rather counter-intuitive. @sideshowbarker, would you mind explaining more why this behavior is intentional?

Also, if the IP address under consideration is serving different vhosts, how does one specify the vhost (to be sent as the `Host` header)?

Thanks!

**Comment by hmnd** [comment]
@sideshowbarker I'd also like to find out why this behavior is intentional, if you don't mind?

**Comment by a3nm** [comment]
Hi, this still does not work for me: when entering "https://www.google.com/" on https://validator.w3.org/nu I get redirected to https://validator.w3.org/nu//www.google.com/ which is currently a 404 error. The same happens when doing it on https://validator.w3.org/ directly.

I guess this is not the intended behavior, right?

Many thanks for your help!
