### ISSUE TITLE
<img> with src attribute containing '/img' as part of URL incorrectly flags </img> as stray

### ISSUE THREAD

**Issue by jscheller** [validator/validator#773]
I have this bit of HTML, copied verbatim from the validator output...

`<img id=HeaderImage src="/img/DadsWorksheetsLogo@2x.png" alt="DadsWorksheets.com - Thousands of printable math worksheets for teachers, home schooling or general study!"></img>`

...and it's identifying the closing </img> tag as a stray. I going to hazard a guess this is because the src attribute contains "/img" (none of the other img elements on this page, none of which include a similar /img url, are affected.)

You can see the entire source at the URL here...

[https://www.dadsworksheets.com/charts/square-root-chart.html](https://www.dadsworksheets.com/charts/square-root-chart.html)

**Comment by sideshowbarker** [comment]
Remove the `</img>` end tag. The `img` element can’t have an end tag:

https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element:concept-element-tag-omission

**Comment by jscheller** [comment]
Good grief... I've made it quite a few miles without hearing that before. Corrected. Thank you!

**Comment by sideshowbarker** [comment]
> I've made it quite a few miles without hearing that before. Corrected. Thank you!

Cheers — that kind of case is exactly what the checker is intended to help you find and fix. So it’s nice to know it’s helping.

The thing about that `</img>` end tag is that browsers just ignore it when parsing your HTML source, so it doesn’t have any negative effect on behavior. But it’s also not serving any real purpose (which is why the checker reports it as an error).
