### ISSUE TITLE
JSON output's "message" fields contain smart quotes

### ISSUE THREAD

**Issue by rujiel** [validator/validator#834]
In the JSON output "messages" array, a message can appear as below. Note the MS Word smart quotes (also called Oxford quotes) around "href" and "link". These types of characters are disliked by developers, please replace them with escaped standard quotes.

{
	"type": "error",
	"lastLine": 10,
	"lastColumn": 56,
	"firstColumn": 7,
	"message": "Bad value “*** Broken Link ***” for attribute “href” on element “link”: Illegal character in path segment: space is not allowed.",
	"extract": "s\">\n      <link rel=\"stylesheet\" href=\"*** Broken Link ***\"><scrip",
	"hiliteStart": 10,
	"hiliteLength": 50
}

**Comment by nschonni** [comment]
There is an option to control that https://github.com/validator/validator#--asciiquotes

**Comment by rujiel** [comment]
Ah okay, thanks for the info. Any way the default could be changed to "off" for those?

**Comment by cvrebert** [comment]
The curly quotes are useful in that they are distinct from regular quotes, and the source HTML which is often quoted in error messages often itself contains regular quotes.

**Comment by rujiel** [comment]
I'm using the default docker image accessible here, is it possible to pass that flag when running it like this?

docker run -it --rm -p 8888:8888 validator/validator:latest

You can close this ticket since nothing more apparently needs to be done, I just think using smart quotes as clever workaround to avoid having to escape strings is a bad idea: introducing a bane of developers to provide a minor convenience.

**Comment by sideshowbarker** [comment]
@XhmikosR

**Comment by sideshowbarker** [comment]
@XhmikosR if we change the default behavior for JSON-formatted output to have `\”`-escaped quotes where it now has `“` and `”` (U+201C and U+201D) curly quotes, do you think that’s gonna break a lot of downstream filters that people have set up using grunt-html and such?

**Comment by XhmikosR** [comment]
Probably, yeah. So, the current asciiquotes option doesn't change the quotes in all cases?

**Comment by sideshowbarker** [comment]
> So, the current asciiquotes option doesn't change the quotes in all cases?

Yeah. Specifically, it never affects the JSON output; currently the JSON output always has U+201C and U+201D no matter whether asciiquotes is specified or not.

So that’s a bug that I need to fix, regardless.

**Comment by sideshowbarker** [comment]
> I'm using the default docker image accessible here, is it possible to pass that flag when running it like this?
> 
> docker run -it --rm -p 8888:8888 validator/validator:latest

It’s now possible to set the asciiquotes options by doing this:

```
docker run -e JAVA_TOOL_OPTIONS=-Dnu.validator.client.asciiquotes=yes \
    -it --rm -p 8888:8888 validator/validator
```

That is, add `-e JAVA_TOOL_OPTIONS=-Dnu.validator.client.asciiquotes=yes` to the invocation.

> I just think using smart quotes as clever workaround to avoid having to escape strings is a bad idea: introducing a bane of developers to provide a minor convenience.

The smart quotes weren’t added as a worked for escaping strings. They were added because of limitations in how we could format message strings for multiple output formats — including in the console environment (GNU error format), where they get shown literally.

Anyway, that said, as far as the JSON-formatted output goes, in hindsight I’m not sure they should have even been used there to begin with. So I would be inclined to change the default to asciiquotes there — except that it seems likely it might break pattern-matching filters that users have already set up (for filtering/suppressing certain messages) and that rely on matching the smart-quotes characters.
