### ISSUE TITLE
security issue? - where comes the markup from

### ISSUE THREAD

**Issue by voku** [validator/validator#850]
Hi, I use codeception + https://github.com/Kolyunya/codeception-markup-validator (https://validator.w3.org/nu/ via post api) ... and I noticed that sometimes I got something like the following response? Maybe the "Markup:" part is a special response from your service? But for me it seems like the markup is from a different request, because it's not from my source-code?

```
Markup validator message:
Type: error
Summary: Non-space characters found without seeing a doctype first. Expected “<!DOCTYPE html>”.
Details: unavailable
First Line: unavailable
Last Line: 1
Markup: x !important;}                    td[class="max552"] {width: 420px !important;}                    a[class="max368"] {font-size: 22px !important; line-height: 27px !important;}                    a[class="max8"] {font-size: 30px !important; line-height: 35px !important;}                    a[class="max145"] {font-size: 32px !important; line-height: 37px !important;}                    }                    @media only screen and (max-width: 479px) {                    table[class=global] { width:320px !important;} *[class=mob-hide] { display: none !important; }                    img[class="max1326"] {height: 196px !important; width: 320px !important;}                    td[class="max552"] {width: 290px !important; height: 80px !important;}                    a[class="max551"] {font-size: 42px !important; line-height: 47px !important; width: 290px !important; height: 80px !important;}                    td[class="max485"] {height: 15px !important;}                    td[class="max505"] {height: 105px !importan

Markup validator message:
Type: error
Summary: Element “head” is missing a required instance of child element “title”.
Details: unavailable
First Line: unavailable
Last Line: 1
Markup: x !important;}                    td[class="max552"] {width: 420px !important;}                    a[class="max368"] {font-size: 22px !important; line-height: 27px !important;}                    a[class="max8"] {font-size: 30px !important; line-height: 35px !important;}                    a[class="max145"] {font-size: 32px !important; line-height: 37px !important;}                    }                    @media only screen and (max-width: 479px) {                    table[class=global] { width:320px !important;} *[class=mob-hide] { display: none !important; }                    img[class="max1326"] {height: 196px !important; width: 320px !important;}                    td[class="max552"] {width: 290px !important; height: 80px !important;}                    a[class="max551"] {font-size: 42px !important; line-height: 47px !important; width: 290px !important; height: 80px !important;}                    td[class="max485"] {height: 15px !important;}                    td[class="max505"] {height: 105px !importan
```

**Comment by voku** [comment]
I think the problem is this code ```(uri == systemId || (uri != null && uri.equals(systemId)))) {``` (src/nu/validator/messages/MessageEmitterAdapter.java) and we use something like "localhost.localdomain" behind a nginx-reverse-proxy in a lxd container. So if someone else use the same url, we will share the results.

**Comment by sideshowbarker** [comment]
> I think the problem is this code `(uri == systemId || (uri != null && uri.equals(systemId)))) {` (src/nu/validator/messages/MessageEmitterAdapter.java)

No

> and we use something like "localhost.localdomain" behind a nginx-reverse-proxy in a lxd container.So if someone else use the same url, we will share the results.

If you are saying your  "localhost.localdomain" behind a nginx-reverse-proxy in a lxd container causes results to be shared, then that’s not an upstream problem in the validator service itself. Instead, that’s a problem in your own deployment, as far as I can see. There isn’t anything I can change upstream to mitigate that.

The validator service does not share any state between requests. Period. It is stateless.

> Hi, I use codeception + https://github.com/Kolyunya/codeception-markup-validator

I have not idea what that is. For all I know, codeception could be sharing state information between requests and causing the problem that you’ve run into.

> (https://validator.w3.org/nu/ via post api) ... and I noticed that sometimes I got something like the following response?

If you’re getting an unexpected response, that’s because whatever client you’re using to send the request has in fact sent some request to the validator service that’s not what you expect.

In other words, the validator service itself is behaving as expected. It’s just that the request you think it has received is in fact not the actual request it has received.

You’ve reported something you claim is a potential security issue without providing any way data or evidence to document that claim — you’ve not provided any steps for reproducing the problem.

I suggest that you use Wireshark or something to inspect that actual requests that your client is sending to the service. If you can document a case where your client is sending a particular document to the validator service, but the validator sends a response that indicates it checked a different document than the one you sent, then we have something to investigate.

But right now, you so far haven’t provided anything concrete that I could even do any concrete investigation of at all.
