### ISSUE TITLE
"text-decoration: strikethrough" gives confusing error message

### ISSUE THREAD

**Issue by martindholmes** [validator/validator#885]
Using vnu 18.11.5, this bad CSS:

`text-decoration: strikethrough;`

generates this error message:

`error: CSS: “text-decoration”: “strikethrough” is not a “color” value.`

Obviously the error has nothing to do with "color".

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. The upstream code at https://github.com/w3c/css-validator code is where the fix would need to be made. I haven’t looked at it yet, but I reckon it’s probably a pretty easy fix.

Heads-up @ylafon in case he manages to look into it before I do

**Comment by ylafon** [comment]
You can raise issue on the css-validator repository, as @sideshowbarker pointed out, but it derives from the fact that every unknown keyword will be parsed tentatively as a color. The error message is right, as it is not a color value, but it is also wrong as it is not a `text-decoration` value either!

**Comment by sideshowbarker** [comment]
> … every unknown keyword will be parsed tentatively as a color. The error message is right, as it is not a color value, but it is also wrong as it is not a `text-decoration` value either!

OK yeah I see now — the following is actually valid:

```css
p { text-decoration: red }
```
…that is, it’s valid to just have color as the value single value of the property.
 
So now I can understand the assumption the current code is making.

But then of course the following is also valid:

```css
p { text-decoration: underline }
```
So anyway it seems like we could just as easily have the code not try to make an assumptions at all about the intended datatype of the value, so that in this case the message emitted would just be:

> *error: CSS: “text-decoration”: “strikethrough” is not a “text-decoration” value*

Regardless, this issue should (as you said) be raised instead in the https://github.com/w3c/css-validator issue tracker

**Comment by martindholmes** [comment]
Issue raised on the other repo (https://github.com/w3c/css-validator/issues/264). Thanks for the clarification and direction. Feel free to close this one if that's appropriate.

**Comment by sideshowbarker** [comment]
Thanks, closing this — let’s follow up at https://github.com/w3c/css-validator/issues/264
