### ISSUE TITLE
area element requires href attribute?

### ISSUE THREAD

**Issue by dagoldman** [validator/validator#887]
Input HTML: `<area alt="Anderson (448)" title="Anderson (448)" shape=poly coords="510,238, ... 510,238">`

Nu Html Checker says: Error: Element area is missing required attribute href. 

But https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-href documentation on same website says: The href attribute on a and area elements is not required; when those elements do not have href attributes they do not create hyperlinks.

And w3schools (I know, not most authoritative source) says: If the href attribute is not present, the `<area>` tag is not a hyperlink.

I do not want a hyperlink, so I left off href.  But I get hundreds of these apparently false-positive errors, so makes it rather difficult to verify the page.

Thanks for the great validator. Could you fix this bug, or tell me what I am doing wrong, or suggest a workaround, some way to modify my HTML, so I do not get the error messages?

If confirmed as a bug, any idea how long it might take to fix?

Until the bug gets fixed, should I use `<area href="#" ... >` or `<area href="javascript:void(0)" ...>` perhaps in combination with an onclick event, to turn off false error messages? 

Thanks,
Daniel

**Comment by dagoldman** [comment]
Input HTML that did not get included:

`<area alt="Anderson (1.3)" title="Anderson (1.3)" shape=poly coords="510,238, ... 238">`

**Comment by sideshowbarker** [comment]
> Input HTML: `<area alt="Anderson (448)" title="Anderson (448)" shape=poly coords="510,238, ... 510,238">`
> 
> Nu Html Checker says: Error: Element area is missing required attribute href.

You get the error because the `area` element has an `alt` attribute.

The relevant requirement in the spec is this:

https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element:attr-hyperlink-href-3
> If the `area` element has no `href` attribute, then the area represented by the element cannot be selected, and the `alt` attribute must be omitted.

(Admittedly, the error message doesn’t make that very clear; but that’s a general issue with how some of the error messages from the checker are generated.)



> Could you fix this bug, or tell me what I am doing wrong, or suggest a workaround, some way to modify my HTML, so I do not get the error messages?

You can omit the `alt` attribute. As the relevant part of the spec states, if the `area` element lacks an `href` attribute, then it’s not selectable — so that `alt` text is never going to be read out by an screen readers, and so it’s not really serving any purpose.

> Until the bug gets fixed, should I use `<area href="#" ... >` or `<area href="javascript:void(0)" ...>` perhaps in combination with an onclick event, to turn off false error messages?

It depends on what you’re trying to do. If you want that `area` element to be selectable, then you need to give is a `href` attribute. But if you don’t want it to be selectable, then it’s fine to omit the `href` attribute — but in if you do, then you also need to omit the `alt` attribute.

**Comment by dagoldman** [comment]
Thank you! Yes, I missed that detail, that when href is omitted from area tag, alt must also be omitted. Sure enough, when I omit alt attribute, no errors are reported. Indeed, I do NOT want the area element to be selectable, so I omit BOTH href and alt attributes. 

Yes, the error message is somewhat misleading. I would suggest one of the following: 
"Element area requires href attribute if alt attribute used"
"Element area must omit alt attribute if no href attribute"

But beggars cannot be choosers. The checker is a great help. Thanks again!
