### ISSUE TITLE
Why are Block level elements not allowed as child of Button

### ISSUE THREAD

**Issue by LaurenceRLewis** [validator/validator#888]
Why is it flagged as an error when a block level element is child of a BUTTON. The spec states: 
 Phrasing content, but there must be no interactive content descendant. 

Block elements are not interactive and I can’t find any mention they are not allowed in the spec. 

I’m probably missing something, so appreciate any feedback on why it is an issue.

**Comment by sideshowbarker** [comment]
Please post a markup snippet that triggers whatever error you're asking about

**Comment by LaurenceRLewis** [comment]
The snippet of the affected code being tested is:

`<button class="btn"><div class="icon"><i aria-hidden="true" class="fa fa-flag-o flag"></i></div><div class="message"><span>Back to topic overview</span><i aria-hidden="true" class="fa fa-sign-out"></i></div></button>`

However just simply using the following to test the validator reporting,  flags the error message: _Error: Element div not allowed as child of element button in this context. (Suppressing further errors from this subtree.)_

`<button><div>Back to topic overview</div></button>`

I'm interested to understand why this is an issue (error) and what user impact is (accessibly) if block elements are used as children of a button element.

Thanks

**Comment by sideshowbarker** [comment]
> `<button><div>Back to topic overview</div></button>`

OK, yeah, so the `div` element isn’t phrasing content, and the HTML spec only allows phrasing content within `button` elements.

https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element

> I'm interested to understand why this is an issue (error)

As far as the behavior of the HTML checker is concerned, the checker reports an error because using `div` within `button` violates the requirements in the HTML spec.

> and what user impact is (accessibly) if block elements are used as children of a button element

I guess the best way to get feedback about that would be to raise an issue against the HTML spec in the issue tracker at  https://github.com/whatwg/html/issues
