### ISSUE TITLE
false positive warning about document language lang="es"

### ISSUE THREAD

**Issue by cruzdelsur3** [validator/validator#897]
I get following warning on from NU HTML CHECKER (https://validator.w3.org/nu/#textarea):

Warning: This document appears to be written in Portuguese but the html start tag has lang="es". Consider using lang="pt" (or variant) instead.
From line 2, column 16; to line 2, column 31
type html><html lang='es'>↩<head

It is wrong because document is written in spanish

[es.zip](https://github.com/validator/validator/files/4049172/es.zip)

THANKS!

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. For that particular document, I’d recommend using `lang="zxx"` rather than `lang="es"`.

The reason I recommend that is, it looks like that document is a product catalog of some kind. It doesn’t really have prose content as such (by which I mean, complete sentences and paragraphs) but instead a bunch of items with code (código) numbers and category (rubro) labels that are just a few words rather than complete sentences.

So the content isn’t really “lingustic” in the typical sense — for example, it’s not really content that anybody would read out aloud — and lang="zxx"` is the appropriate language tag to use for non-linguistic content.

In general for a case like that document — a product catalog — the language detector in the HTML checker has a hard time guessing the language correctly. That limitation is just a consequence of the way it works; it really needs complete sentences in order to guess the language reliably.
