### ISSUE TITLE
Error due to certain kinds of whitespace between </li> and <li>

### ISSUE THREAD

**Issue by RickTuckerUSA** [validator/validator#900]
In a file I have &lt;li&gt; ... &lt;/li&gt; followed by &lt;li&gt; ... &lt;/li&gt; , repeated 100 times within a &lt;ul&gt; ... &lt;/ul&gt;.

Where I have a new line then new line then tab between a &lt;/li&gt; and the next &lt;li&gt;, the validator does not complain.

There are cases where I have a new line then new line then space then tab between a &lt;/li&gt; and the next &lt;li&gt;, and the validator gives the follow Error (in HTML). Note that there are no &amp;nbsp; items in the actual file.

<li class="error" id="vnuId0"><p><strong>Error</strong>: <span>Text not allowed in element <a href="https://html.spec.whatwg.org/multipage/#the-ul-element"><code>ul</code></a> in this context.</span></p><p class="location"><a href="#l1322c2">From line <span class="first-line">1322</span>, column <span class="first-col">1</span>; to line <span class="last-line">1322</span>, column <span class="last-col">2</span></a></p><p class="extract"><code>&gt;<span class="lf" title="Line break">↩</span>	&lt;/li&gt;<span class="lf" title="Line break">↩</span><span class="lf" title="Line break">↩</span><b>&nbsp;	</b>&lt;li&gt;<span class="lf" title="Line break">↩</span>	</code></p><dl><dt>Content model for element <a href="https://html.spec.whatwg.org/multipage/#the-ul-element"><code>ul</code></a>:</dt><dd>Zero or more <code><a href="https://html.spec.whatwg.org/multipage/#the-li-element">li</a></code> and <a href="https://html.spec.whatwg.org/multipage/#script-supporting-elements-2">script-supporting</a> elements.</dd></dl></li>

**Comment by sideshowbarker** [comment]
Please provide a URL for an HTML document that can be used to reproduce the error. It doesn’t have to be your actual document — it can instead just a be a minimal document. Or if not a URL for such a doucment, then please add a comment with the contents of such a minimal HTML document that can be used to reproduce the error.

**Comment by RickTuckerUSA** [comment]
Here's the URL (with no CSS): http://tiddlywinks.org/transfer/winking-world/winking-world.html

**Comment by nschonni** [comment]
could be a non-space character. You might need to look in a hex editor to see what the actual character is

**Comment by sideshowbarker** [comment]
>> http://tiddlywinks.org/transfer/winking-world/winking-world.html
>
> could be a non-space character. You might need to look in a hex editor to see what the actual character is

Yeah, that’s the actual cause of the errors in http://tiddlywinks.org/transfer/winking-world/winking-world.html. At the beginning of line 1338, for example, there’s a non-breaking space (U+00a0). And at the beginning of lines 1353, 1368, 1382 and 1383, etc. Some lines start with two non-breaking spaces — line 1462, for example.

Anyway, the HTML checker is behaving as expected and in conformance with the HTML spec in this case, because per the HTML spec (see more details below), text containing U+00a0 characters isn’t allowed as a direct child of the `ul` element. 

>> When is whitespace not whitespace?

To define what’s allowed, the HTML spec uses the specific term *ASCII whitespace*:

https://infra.spec.whatwg.org/#ascii-whitespace
> ASCII whitespace is U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, or U+0020 SPACE.

There are of course other non-printing/non-visible characters outside the ASCII range that are also typically referred to as “whitespace” (e.g., various other space characters). But those by definition aren’t ASCII whitespace, so that’s why the language in the HTML spec is careful to always consistently use the term _ASCII whitespace_ — to make it clear and unambiguous what specific kind of whitespace is meant.

So, as far as HTML markup requirements go (and HTML parsing), the U+00a0 (non-breaking space) character is not ASCII whitespace but instead is non-ASCII-whitespace text, which is prohibited within elements — such as the `ul` element — that don’t allow text nodes as children.

Anyway, I guess maybe the text editor you’ve used that `winking-world.html` document is somehow causing U+00a0 non-breaking spaces to get added the document in places where you think you’re just adding a normal ASCII U+0020 space character. The fix is either to configure your editor to make it not do that, or else run the document through some post-processing step which converts those U+00a0 characters in normal ASCII U+0020 space characters.
