### ISSUE TITLE
Please consider adding comment substitution to process server-side scripts

### ISSUE THREAD

**Issue by AMA3** [validator/validator#93]
It would be Most Awesome™ if you added an option to treat certain character sequences used for server-side scripting as though they were HTML comment start/end delimiters.  For example, options such as:
``--comment-begin=<%
--comment-end=%>``

I ask because I have a project that generates .html, .php and .aspx files from an XSL stylesheet and uses grunt-html to lint the results.  Currently, I have to list a lot of patterns to ignore certain errors caused by misinterpretation of the server-side code, and those patterns could potentially ignore real problems in the actual markup.  Allowing users to treat <% and %>, or <?php and ?> (for example) as equivalents for  would be an easy way to reduce this problem.

Thank you for your consideration!

**Comment by sideshowbarker** [comment]
Thanks for taking the time to raise this enhancement request and sorry for not replying to it before now. This is a request that comes up pretty regularly, but the short answer to it is, we’re not going to implement this any time in the foreseeable future.

> Currently, I have to list a lot of patterns to ignore certain errors caused by misinterpretation of the server-side code,

Actually that’s not “misinterpretation” (though I can understand it being seen that way). The checker is an HTML checker. It’s not a PHP checker nor an ASP checker. PHP files and ASP files are not HTML. And in a great many cases, trying to hack through their non-HTMLness by treating some kinds of delimiters as comments does not make them parsable as HTML anyway.

The checker backend is driven by an HTML parser that conforms to the HTML spec. The enhancement proposed here would require having the checker backend instead be driven by different parsing behavior for which there is no actual spec. Or rather I guess it’d require us to instead implement a PHP parser.

I recognize that people think simply having an HTML parser treat the PHP delimiters in the same way as HTML comment delimiters would be an easy way to get what’s needed. But it’s not. There are many cases where that simply would not work (even if we thought it was a good idea to do it).

Anyway I think the solution to this for command-line users of the checker is to first run their PHP source through a command-line php tool that parses the PHP and converts it into the same HTML that would be sent over the wire to Web browsers and that browser engines would then parse. In the end, that’s what you want to be checking anyway, because that’s where the problems the checker is meant to report on would be found.

So I’m going to go ahead and close this. Feel free to open it if you want (e.g., if you have additional information beyond what you already reported when you raised this.)
