### ISSUE TITLE
Custom elements validation

### ISSUE THREAD

**Issue by otachasak** [validator/validator#94]
Hello, I would like to ask, how to to use this project to validate html5 with custom elements. If I use it the following error occurs: Element my-element not allowed as child of element...

Thank you

**Comment by sideshowbarker** [comment]
See my answer at http://stackoverflow.com/questions/28508533/w3c-validation-for-ui-select/28711028#28711028

We don’t currently have a good solution for dealing with custom elements. They are strictly not valid HTML per the requirements HTML spec. That said, it would be nice to try to find a way to check documents that contain them. But we’re not going to be coming up with a way to do that any time in the near future, so I’m going to close out this issue rather than just leaving it hanging open forever.

If/when we ever do implement checker support for documents with custom elements, it will be a major new feature that we announce widely. But don’t expect to see that announcement any time soon.

**Comment by jfiala** [comment]
We are using Knockout custom components
(http://knockoutjs.com/documentation/component-overview.html) and currently pages using custom components fail html validation.
e.g.  <like-widget params="value: userRating"></like-widget>

However, to keep our pages valid, we are currently using the alternative syntax for Knockout custom components (<div data-bind="component: {...}">...), but this syntax is less readable.

According to 
http://stackoverflow.com/questions/9845011/are-custom-elements-valid-html5
it should be possible for the HTML validator to simply ignore elements using a dash in the element name (as these are probably custom elements).

This would be a very minor feature which should easy to add and would make the direct validation of HTML pages containing custom elements / custom components possible (together with a checkbox "allow usage of custom elements", maybe even whitelisting the allowed custom components separated with comma"). 
So current users of the HTML validator wouldn't have any change in the validation behaviour and users wanting to use custom elements would be allowed to do so and could ensure their markup is valid.

It would be even better, if it would be possible to declare the valid custom elements inside the page, but the specifications seem to be currently in early draft mode (http://w3c.github.io/webcomponents/spec/custom/#custom-tag-example).
