### ISSUE TITLE
SVG files not checked from command line

### ISSUE THREAD

**Issue by edemaine** [validator/validator#953]
`java -jar vnu.jar --verbose --svg test.svg` outputs `test.svg` but does not seem to actually test the file, only that the file exists.  I've tried it on empty files and files with small and large errors, and there's never any output.

On the other hand, `java -jar vnu.jar --verbose --svg - <test.svg` does properly test the file (but the error message lack the file name, naturally).

I believe [this line](https://github.com/validator/validator/blob/master/src/nu/validator/client/SimpleCommandLineValidator.java#L449) should be followed by something like `validator.checkXmlFile(file);` (and possibly schema-setting code as in `checkSvgInputSource`).

**Comment by sideshowbarker** [comment]
https://github.com/validator/validator/releases/tag/jar has a dev/snapshot with the fix for this.

> I believe [this line](https://github.com/validator/validator/blob/master/src/nu/validator/client/SimpleCommandLineValidator.java#L449) should be followed by something like `validator.checkXmlFile(file);`

Yes. I’m surprised nobody reported this before now. Thanks for catching it.

(I’d like to imagine that the reason nobody reported it before now is that nobody has been using the SVG-checking feature in the command-line checker. Unfortunately though I think the reality is, people have been using it but since it’s not been reporting any errors, it’s been misleading them into thinking none of the SVG files they’ve checked have had any errors…)

> (and possibly schema-setting code as in `checkSvgInputSource`)

Yup, needed to add that too (because in the command-line-checker context, we don’t do any namespace sniffing to identify what schema to use).

Thanks again!

**Comment by edemaine** [comment]
Just tested, and it works in my application!

> I’d like to imagine that the reason nobody reported it before now is that nobody has been using the SVG-checking feature in the command-line checker. Unfortunately though I think the reality is, people have been using it but since it’s not been reporting any errors, it’s been misleading them into thinking none of the SVG files they’ve checked have had any errors…)

Yes, that is a fear. Luckily in my case, I knew I should be getting some warnings/errors based on my experience with the web interface, and was adding automated testing to check that I was squashing the bugs in my SVG generator.
