### ISSUE TITLE
my code is absolutely correct 

### ISSUE THREAD

**Issue by shivani1906** [validator/validator#959]

**Comment by shivani1906** [comment]
i

**Comment by shivani1906** [comment]
i learnt this code from coursera and they gave the exact same example which was approved by w3c wiyhout any warnings whereas in my code the compiler is asking me to add some 'lang' attribute....

**Comment by sideshowbarker** [comment]
Please post the URL for a document that demonstrates the problem.

But note at https://html.spec.whatwg.org/multipage/semantics.html#the-html-element:attr-lang the HTML spec says:

> Authors are encouraged to specify a `lang` attribute on the root `html` element, giving the document's language. This aids speech synthesis tools to determine what pronunciations to use, translation tools to determine what rules to use, and so forth.

So if the problem you’re reporting is that the checker emits a warning because you document’s `html` element lacks a `lang` attribute, then you can fix that problem by adding a `lang` attribute to the `html` element — which will bring it in line with that recommendation in the HTML spec.

**Comment by sideshowbarker** [comment]
Closing due to lack of response
