### ISSUE TITLE
Highlighting of errors/warnings sometimes highlight the wrong part by 3 characters.

### ISSUE THREAD

**Issue by Jeff-Schafer** [validator/validator#991]
Site Tested: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftvlistings.zap2it.com%2F#l1c4393

Notice some are highlighted correctly.
Some start correctly, but go 3 characters too far on the right-hand side.
Some are shifted 3 characters: the first 3 characters that should be highlighted on the Left are not & 3 additional characters that should NOT be highlighted are on the Right.

Occurs on both Firefox "77.0.1 (64-Bit)" & EDGE "Version 83.0.478.56 (Official build) (64-bit)" browsers.
OS: Windows 10 ("Version 10.0.18363 Build 18363")

![Bad Highlighting on some errors for W3C's Validator (06-30-2020)](https://user-images.githubusercontent.com/23586920/86192076-8b03dd80-bafd-11ea-80bd-9aa7a7a7cac2.png)

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. It’s not immediately obvious to what the cause might be, but certainly it’s a bug. I’ll try to make some time to investigate it myself, but in the meantime, I’ve added some labels to help attract more attention.

**Comment by sideshowbarker** [comment]
I now realize this is related to the `&` ampersands in the attribute values — what the HTML spec refers to as “ambiguous” ampersands, because they don’t indicate a named character reference. The spec used to define those as an error, and disallowed them and required you to use `&amp;` instead. But the spec subsequently changed to allow them, and I made the code change at https://github.com/validator/htmlparser/commit/c6778f8 to attempt to align with the current spec — but that apparently has had the unintended side effect of causing this problem with misalignment of the source-code highlighting.

So this is the same problem as https://github.com/validator/validator/issues/1003 — and as I mentioned there, it’s likely going to be a couple more weeks before I can get back to investigating it further. So in the mean time, please don’t think I’m ignoring this.

**Comment by sideshowbarker** [comment]
I’ve made a fix for this and pushed the fix to https://validator.w3.org/nu/. If it doesn’t solve the problem — or seems to be causing any new problems — please let me know.

Thanks again very much for having taken time to report this.
