### ISSUE TITLE
latest docker image contains a vnu script which references a missing shell

### ISSUE THREAD

**Issue by abuisine** [validator/validator#998]
The latest docker images (like a0cddd37da103a00d49758b960287c12ba8bd20335b6ca8f8639220f65e824d3) do include a vnu script located at `vnu-runtime-image/bin/vnu` which references `/bin/sh`.
`/bin/sh` is not present in the container which leads to the vnu script being unusable.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. It’s a consequence of b3c30b0 that I hadn’t anticipated — because I wasn’t aware anybody was actually using that `vnu` script from the Docker image. 

You probably already know this but a workaround for now is to instead run the following:

```
vnu-runtime-image/bin/java -m vnu/nu.validator.client.SimpleCommandLineValidator FOO.html
```

I recognize that might not be a super-satisfactory solution for the long term, and could revert the b3c30b0 change easily enough to get us back to where we were — but before doing that, I’d first like to understand how you had been using that  `vnu-runtime-image/bin/vnu` script from the Docker image.

Can you provide that full command-line invocation that you’d be using to call that script? I guess it must be something like:

```
docker run -v <something>:<otherthing> validator/validator vnu-runtime-image/bin/vnu TEST.html
```

In particular I mean that I would guess you must be using the `-v` argument to `docker run`, to mount some path from the host filesystem into the container.

I’ve actually never myself run the `vnu-runtime-image/bin/vnu` script from the Docker image, so I’m not completely clear on how to actually do it — and would like to know in part just so that I can test it myself (and test any changes I make).

**Comment by sideshowbarker** [comment]
I pushed an updated image — 0e5e980deb28982ef6674df8a959d16f3175f7a2d77ddb152c2be94b8ebd1134 — so if do a `docker pull validator/validator:latest` you should now get that back.

The only difference is that I changed the build to add/copy `/bin/sh` and `/usr/bin/dirname` binaries back into the image.

So please test with that and let me know if you have any problems.

(I’m still interested in hearing what invocation you’re using to run it…)

**Comment by abuisine** [comment]
Hi there, sorry for the latency :)
I basically scan a static HTML website through the container within a continuous integration pipeline :
```
docker run --rm -v $TEST_VOLUME:/html validator/validator $VNU_COMMAND_LINE --skip-non-html --errors-only /html/fr
```

I do confirm that the new `latest` tag works as expected, thanks a lot !

**Comment by sideshowbarker** [comment]
> I do confirm that the new `latest` tag works as expected, thanks a lot !

Cheers — thanks again much for having raised the issue
