### ISSUE TITLE
IO Error: Premature end of chunk coded message body: closing chunk expected

### ISSUE THREAD

**Issue by J-A-M-E-5** [validator/validator#999]
Happens on my own site and even amazon.com.

[https://validator.w3.org/nu/?doc=https%3A%2F%2Famazon.com](https://validator.w3.org/nu/?doc=https%3A%2F%2Famazon.com)

**Comment by sideshowbarker** [comment]
I’ve fixed this and pushed the fix to https://validator.w3.org/nu/. Please re-check and let me know if you’re still running into the problem.

The root cause of the problem is that the web server from which you’re serving the document is technically in violation of the HTTP spec. That’s because the HTTP spec requires every `Transfer-Encoding: chunked` message to have a “closing chunk” that’s zero-length — but the web server from which you’re serving your document doesn’t add such a closing chunk.

However, that particular violation of the HTTP spec doesn’t seem to be something that causes any real problems in practice — so browsers and most other client tools that send and receive HTTP requests and responses just ignore that problem. But the HTTP client which the HTML checker uses follows the HTTP spec more strictly; hence the error report.

So the “fix” I made was to basically just internally suppress the error so that it doesn’t end up getting reported to you as an end user. That seems appropriate in the case — given that you unless you’re a web-server admin, you likely don’t have any way to prevent the error (other than switching to a new web server/hosting provider).

**Comment by J-A-M-E-5** [comment]
Thanks, all working fine now.

**Comment by Ayiruss** [comment]
> I’ve fixed this and pushed the fix to https://validator.w3.org/nu/. Please re-check and let me know if you’re still running into the problem.
> 
> The root cause of the problem is that the web server from which you’re serving the document is technically in violation of the HTTP spec. That’s because the HTTP spec requires every `Transfer-Encoding: chunked` message to have a “closing chunk” that’s zero-length — but the web server from which you’re serving your document doesn’t add such a closing chunk.
> 
> However, that particular violation of the HTTP spec doesn’t seem to be something that causes any real problems in practice — so browsers and most other client tools that send and receive HTTP requests and responses just ignore that problem. But the HTTP client which the HTML checker uses follows the HTTP spec more strictly; hence the error report.
> 
> So the “fix” I made was to basically just internally suppress the error so that it doesn’t end up getting reported to you as an end user. That seems appropriate in the case — given that unless you’re a web-server admin, you likely don’t have any way to prevent the error (other than switching to a new web server/hosting provider).

I am also facing the same issue after doing spring upgrade. How did you suppress the error? By matching the error Message.

Thanks in Advance.

**Comment by splch** [comment]
I'm curious as well, because I'm receiving the same error: `IO Error: Premature end of chunk coded message body: closing chunk expected`. The validation of my [site](https://slc.is) works on other validators, but not this one.
